# Generated by Django 6.0.5 on 2026-08-08 20:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KDSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(unique=True, verbose_name='ref')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('prep', 'Preparo'), ('picking', 'Separação'), ('expedition', 'Expedição')], max_length=20, verbose_name='tipo')),
                ('target_time_minutes', models.PositiveIntegerField(default=10, help_text='Timer fica amarelo após este tempo, vermelho após 2x.', verbose_name='tempo alvo (min)')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='som ativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('config', models.JSONField(blank=True, default=dict, help_text='text_size, dark_mode, refresh_interval, etc.', verbose_name='configurações')),
            ],
            options={
                'verbose_name': 'estação KDS',
                'verbose_name_plural': 'estações KDS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KDSTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Resolve para a Session aberta (comanda) ou o Order selado.', max_length=64, verbose_name='chave da venda')),
                ('items', models.JSONField(default=list, help_text='[{"sku", "name", "qty", "notes", "checked": false}]', verbose_name='items')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Operador deu baixa no card cancelado — sai do board.', null=True, verbose_name='ciente em')),
            ],
            options={
                'verbose_name': 'ticket KDS',
                'verbose_name_plural': 'tickets KDS',
                'ordering': ['created_at'],
                'permissions': [('operate_kds', 'Pode operar telas KDS (check, done, expedition)')],
            },
        ),
        migrations.CreateModel(
            name='OperationChecklistRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data operacional')),
                ('shift_ref', models.CharField(blank=True, default='', max_length=50, verbose_name='turno')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='open', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='contexto')),
            ],
            options={
                'verbose_name': 'execução de checklist operacional',
                'verbose_name_plural': 'execuções de checklists operacionais',
                'ordering': ['-business_date', 'template__sort_order', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=80, unique=True, verbose_name='ref')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição curta')),
                ('moment', models.CharField(choices=[('opening', 'Abertura'), ('routine', 'Rotina'), ('closing', 'Fechamento')], max_length=20, verbose_name='momento')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'modelo de checklist',
                'verbose_name_plural': 'modelos de checklist',
                'ordering': ['moment', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OperationChecklistTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_required_override', models.BooleanField(blank=True, null=True, verbose_name='obrigatória neste checklist')),
            ],
            options={
                'verbose_name': 'tarefa do modelo de checklist',
                'verbose_name_plural': 'tarefas do modelo de checklist',
                'ordering': ['sort_order', 'task_template__title'],
            },
        ),
        migrations.CreateModel(
            name='OperationTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluída'), ('skipped', 'Ignorada'), ('blocked', 'Bloqueada')], default='pending', max_length=20, verbose_name='status')),
                ('is_required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('evidence_required', models.CharField(choices=[('none', 'Nenhuma'), ('text', 'Texto'), ('number', 'Número'), ('photo', 'Foto'), ('double_check', 'Dupla conferência')], default='none', max_length=20, verbose_name='evidência exigida')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='executada em')),
                ('supervised_at', models.DateTimeField(blank=True, null=True, verbose_name='supervisionada em')),
                ('evidence_text', models.TextField(blank=True, verbose_name='evidência textual')),
                ('evidence_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='evidência numérica')),
                ('evidence_data', models.JSONField(blank=True, default=dict, verbose_name='evidência estruturada')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('linked_domain', models.CharField(blank=True, max_length=80, verbose_name='domínio vinculado')),
                ('linked_ref', models.CharField(blank=True, max_length=120, verbose_name='ref vinculada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'execução de tarefa operacional',
                'verbose_name_plural': 'execuções de tarefas operacionais',
                'ordering': ['checklist_run', 'template__sort_order', 'template__title'],
            },
        ),
        migrations.CreateModel(
            name='OperationTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=80, unique=True, verbose_name='ref')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição curta')),
                ('moment', models.CharField(choices=[('opening', 'Abertura'), ('routine', 'Rotina'), ('closing', 'Fechamento')], max_length=20, verbose_name='momento')),
                ('area', models.CharField(choices=[('cash', 'Caixa'), ('room', 'Salão'), ('production', 'Produção'), ('stock', 'Estoque'), ('cleaning', 'Limpeza'), ('management', 'Gestão')], max_length=20, verbose_name='área')),
                ('evidence_required', models.CharField(choices=[('none', 'Nenhuma'), ('text', 'Texto'), ('number', 'Número'), ('photo', 'Foto'), ('double_check', 'Dupla conferência')], default='none', max_length=20, verbose_name='evidência exigida')),
                ('expected_role', models.CharField(blank=True, max_length=80, verbose_name='responsável esperado')),
                ('is_required', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('is_system', models.BooleanField(default=False, verbose_name='tarefa do sistema')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='configuração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'modelo de tarefa',
                'verbose_name_plural': 'modelos de tarefa',
                'ordering': ['moment', 'sort_order', 'title'],
                'permissions': [('manage_operation_checklists', 'Pode configurar checklists operacionais'), ('perform_operation_task', 'Pode executar tarefas operacionais'), ('supervise_operation_task', 'Pode supervisionar tarefas operacionais'), ('view_operation_reports', 'Pode ver relatórios operacionais')],
            },
        ),
        migrations.CreateModel(
            name='OperatorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('payment_insufficient', 'Pagamento abaixo do total'), ('payment_reconciliation_failed', 'Reconciliação de pagamento falhou'), ('webhook_failed', 'Webhook falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('coupon_over_redeemed', 'Cupom resgatado acima do limite'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível'), ('stale_new_order', 'Pedido parado aguardando confirmação'), ('production_late', 'Produção atrasada'), ('production_low_yield', 'Produção com yield baixo'), ('production_stock_short', 'Produção sem insumo suficiente'), ('directive_failed_spike', 'Tarefas de fundo falhando'), ('directive_backlog', 'Fila de tarefas de fundo acumulada'), ('directive_worker_stale', 'Worker de tarefas de fundo parado'), ('lifecycle_phase_stuck', 'Fase do pedido travada'), ('low_rating', 'Avaliação baixa recebida')], max_length=50, verbose_name='tipo')),
                ('severity', models.CharField(choices=[('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='warning', max_length=10, verbose_name='severidade')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('order_ref', models.CharField(blank=True, max_length=50, verbose_name='ref do pedido')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='reconhecido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'alerta operacional',
                'verbose_name_plural': 'alertas operacionais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='Referência curta da comanda. Números continuam normalizados com 8 dígitos; texto livre é aceito para identificação operacional.', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^(?!\\s*$)[^/\\\\?#%\\r\\n\\t]{1,64}$', 'Use até 64 caracteres, sem barras ou caracteres de URL.')], verbose_name='referência')),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='rótulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'comanda do PDV',
                'verbose_name_plural': 'comandas do PDV',
                'ordering': ['ref'],
            },
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=80, unique=True, verbose_name='ref')),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='rotulo')),
                ('channel_ref', models.CharField(default='pdv', max_length=80, verbose_name='canal')),
                ('location_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='local')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'terminal do PDV',
                'verbose_name_plural': 'terminais do PDV',
                'ordering': ['ref'],
            },
        ),
        migrations.CreateModel(
            name='BlindPrepCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('recipe_ref', models.SlugField(max_length=100, verbose_name='preparo')),
                ('code', models.CharField(max_length=2, verbose_name='código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'código de pesagem cega',
                'verbose_name_plural': 'códigos de pesagem cega',
                'constraints': [models.UniqueConstraint(fields=('date', 'recipe_ref'), name='blindprep_date_recipe_uq'), models.UniqueConstraint(fields=('date', 'code'), name='blindprep_date_code_uq')],
            },
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_amount_q', models.IntegerField(default=0, help_text='Valor de abertura em centavos (fundo de troco).')),
                ('blind_closing_amount_q', models.IntegerField(blank=True, help_text='Valor contado no fechamento cego em centavos.', null=True)),
                ('expected_amount_q', models.IntegerField(blank=True, help_text='Calculado: abertura + vendas_dinheiro + suprimentos - sangrias.', null=True)),
                ('difference_q', models.IntegerField(blank=True, help_text='Diferenca: contado - esperado (positivo = sobra).', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado'), ('void', 'Cancelado')], default='open', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'turno de caixa',
                'verbose_name_plural': 'turnos de caixa',
                'ordering': ['-opened_at'],
                'permissions': [('operate_pos', 'Pode operar o PDV (abrir/fechar caixa, sangria, balcão)'), ('audit_cashshift', 'Pode auditar turnos de caixa'), ('adjust_cashshift', 'Pode ajustar turnos de caixa'), ('manage_operators', 'Pode gerir operadores (resetar PIN, provisionar)')],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sangria', 'Sangria'), ('suprimento', 'Suprimento'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('amount_q', models.IntegerField(help_text='Valor em centavos (sempre positivo).')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='backstage.cashshift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'movimentação de caixa',
                'verbose_name_plural': 'movimentações de caixa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='data')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='fechado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('data', models.JSONField(blank=True, default=list, help_text='Snapshot de fechamento do dia. Schema definido pela instância.', verbose_name='snapshot')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
            ],
            options={
                'verbose_name': 'fechamento do dia',
                'verbose_name_plural': 'fechamentos do dia',
                'ordering': ['-date'],
                'permissions': [('perform_closing', 'Pode executar fechamento do dia'), ('view_production_reports', 'Pode ver relatórios de produção'), ('view_dayclosing_management', 'Pode ver agregados gerenciais do fechamento'), ('operate_production', 'Pode operar a produção (chão + planejamento) no app dedicado')],
            },
        ),
    ]
