# Generated by Django 6.0.5 on 2026-08-08 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backstage', '0001_initial'),
        ('offerman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kdsinstance',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Categorias de produto que esta estação processa. Vazio = catch-all.', to='offerman.collection', verbose_name='coleções'),
        ),
        migrations.AddField(
            model_name='kdsticket',
            name='kds_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='backstage.kdsinstance', verbose_name='estação KDS'),
        ),
        migrations.AddField(
            model_name='operationchecklistrun',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_checklists_completed', to=settings.AUTH_USER_MODEL, verbose_name='concluído por'),
        ),
        migrations.AddField(
            model_name='operationchecklistrun',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_checklists_started', to=settings.AUTH_USER_MODEL, verbose_name='iniciado por'),
        ),
        migrations.AddField(
            model_name='operationchecklistrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='backstage.operationchecklisttemplate', verbose_name='template'),
        ),
        migrations.AddField(
            model_name='operationchecklisttemplatetask',
            name='checklist_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='backstage.operationchecklisttemplate', verbose_name='checklist'),
        ),
        migrations.AddField(
            model_name='operationtaskrun',
            name='checklist_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='backstage.operationchecklistrun', verbose_name='checklist'),
        ),
        migrations.AddField(
            model_name='operationtaskrun',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_tasks_executed', to=settings.AUTH_USER_MODEL, verbose_name='executada por'),
        ),
        migrations.AddField(
            model_name='operationtaskrun',
            name='supervised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_tasks_supervised', to=settings.AUTH_USER_MODEL, verbose_name='supervisionada por'),
        ),
        migrations.AddField(
            model_name='operationtaskrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='backstage.operationtasktemplate', verbose_name='template'),
        ),
        migrations.AddField(
            model_name='operationchecklisttemplatetask',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_links', to='backstage.operationtasktemplate', verbose_name='tarefa'),
        ),
        migrations.AddField(
            model_name='operationchecklisttemplate',
            name='tasks',
            field=models.ManyToManyField(related_name='checklist_templates', through='backstage.OperationChecklistTemplateTask', to='backstage.operationtasktemplate', verbose_name='tarefas'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='backstage.posterminal', verbose_name='Terminal'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_q__gt', 0), models.Q(('movement_type', 'ajuste'), models.Q(('amount_q', 0), _negated=True)), _connector='OR'), name='backstage_cashmovement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='operationchecklistrun',
            constraint=models.UniqueConstraint(fields=('template', 'business_date', 'shift_ref'), name='backstage_operation_checklist_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationtaskrun',
            constraint=models.UniqueConstraint(fields=('checklist_run', 'template'), name='backstage_operation_task_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationchecklisttemplatetask',
            constraint=models.UniqueConstraint(fields=('checklist_template', 'task_template'), name='backstage_operation_template_task_unique'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('operator',), name='backstage_cashshift_open_operator_uq'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('terminal',), name='backstage_cashshift_open_terminal_uq'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_amount_q__gte', 0)), name='backstage_cashshift_opening_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('blind_closing_amount_q__isnull', True), ('blind_closing_amount_q__gte', 0), _connector='OR'), name='backstage_cashshift_blind_close_nonnegative'),
        ),
    ]
