# Generated by Django 6.0.5 on 2026-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='approved_by',
            field=models.CharField(blank=True, default='', help_text='Gerente que autorizou a retirada (sangria e ajuste negativo).', max_length=150),
        ),
    ]
