# Generated by Django 6.0.5 on 2026-08-14 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_cashmovement_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvenRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_ref', models.CharField(db_index=True, help_text='WorkOrder.ref (string ref, nunca FK cross-domain — ADR-004).', max_length=64, verbose_name='ordem de produção')),
                ('oven_ref', models.CharField(blank=True, help_text='Snapshot de WorkOrder.position_ref no momento do arm.', max_length=64, verbose_name='forno')),
                ('operator_ref', models.CharField(blank=True, max_length=64, verbose_name='operador')),
                ('planned_seconds', models.PositiveIntegerField(help_text='Duração do timer no arm. Referência, não medição.', verbose_name='duração armada (s)')),
                ('armed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='enfornou em')),
                ('concluded_at', models.DateTimeField(blank=True, help_text='Só o Concluir declarado escreve aqui.', null=True, verbose_name='retirou em')),
                ('status', models.CharField(choices=[('open', 'no forno'), ('concluded', 'concluída'), ('abandoned', 'sem medição')], db_index=True, default='open', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'medição de forno',
                'verbose_name_plural': 'medições de forno',
                'ordering': ['-armed_at'],
                'indexes': [models.Index(fields=['status', 'armed_at'], name='backstage_ov_status_armed_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('work_order_ref',), name='backstage_ovenrun_one_open_per_wo'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'concluded'), _negated=True), ('concluded_at__isnull', False), _connector='OR'), name='backstage_ovenrun_concluded_has_timestamp')],
            },
        ),
    ]
