# Generated by Django 6.0.5 on 2026-08-14 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_alter_dayclosing_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='yooga', max_length=16, verbose_name='origem')),
                ('external_id', models.BigIntegerField(help_text='Chave natural no sistema de origem (ex.: pedido do Yooga).', verbose_name='id externo')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='vendido em')),
                ('total_q', models.BigIntegerField(verbose_name='total (centavos)')),
                ('discount_q', models.BigIntegerField(default=0, verbose_name='desconto (centavos)')),
                ('surcharge_q', models.BigIntegerField(default=0, verbose_name='acréscimo (centavos)')),
                ('payment', models.CharField(blank=True, max_length=100, verbose_name='forma de pagamento (crua)')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='operador')),
                ('modality', models.CharField(blank=True, max_length=32, verbose_name='modalidade (crua)')),
                ('origin', models.CharField(blank=True, max_length=32, verbose_name='origem da venda (crua)')),
                ('table_label', models.CharField(blank=True, max_length=32, verbose_name='mesa (crua)')),
                ('is_delivery', models.BooleanField(default=False, help_text='Único rótulo de canal confiável do histórico.', verbose_name='é delivery')),
                ('customer_external_id', models.BigIntegerField(blank=True, null=True, verbose_name='cliente (id externo)')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='cliente')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('ingested_at', models.DateTimeField(auto_now_add=True, verbose_name='ingerido em')),
            ],
            options={
                'verbose_name': 'venda histórica',
                'verbose_name_plural': 'vendas históricas',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['source', 'occurred_at'], name='backstage_hs_src_when_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='backstage_histsale_source_external')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='linha')),
                ('product_name', models.CharField(max_length=200, verbose_name='produto')),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Resolvido pelo catálogo da origem quando a linha não traz.', max_length=64, verbose_name='sku')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='categoria')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('unit_price_q', models.BigIntegerField(verbose_name='preço unitário (centavos)')),
                ('discount_q', models.BigIntegerField(default=0, verbose_name='desconto (centavos)')),
                ('line_total_q', models.BigIntegerField(verbose_name='total da linha (centavos)')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backstage.historicalsale', verbose_name='venda')),
            ],
            options={
                'verbose_name': 'item de venda histórica',
                'verbose_name_plural': 'itens de venda histórica',
                'ordering': ['sale', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('sale', 'seq'), name='backstage_histitem_sale_seq')],
            },
        ),
    ]
