# Generated by Django 6.0.5 on 2026-08-14 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_historicalsale_historicalsaleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BIView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('config', models.JSONField(help_text='{metric, by, by2, window} — validado pela gramática do explorador.', verbose_name='configuração')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bi_views', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'cenário de B.I.',
                'verbose_name_plural': 'cenários de B.I.',
                'ordering': ['-is_favorite', 'name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='backstage_biview_owner_name')],
            },
        ),
    ]
