# Generated by Django 6.0.5 on 2026-08-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0007_biview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='data')),
                ('holiday_name', models.CharField(blank=True, max_length=120, verbose_name='feriado')),
                ('holiday_scope', models.CharField(blank=True, choices=[('national', 'Nacional'), ('state', 'Estadual'), ('city', 'Municipal')], max_length=16, verbose_name='abrangência')),
                ('is_holiday_eve', models.BooleanField(default=False, help_text='Derivado na carga do calendário: o dia anterior a um feriado.', verbose_name='véspera de feriado')),
                ('is_post_holiday', models.BooleanField(default=False, help_text='Derivado na carga do calendário: o dia seguinte a um feriado.', verbose_name='volta de feriado')),
                ('has_calendar', models.BooleanField(default=False, help_text='Se falso, esta data não foi coberta por nenhum calendário — não afirmamos que é dia comum, apenas não sabemos.', verbose_name='calendário carregado')),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperatura mínima (°C)')),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperatura máxima (°C)')),
                ('temp_avg_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='temperatura média (°C)')),
                ('rain_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='chuva (mm)')),
                ('sources', models.JSONField(blank=True, default=dict, help_text='De onde veio cada bloco, ex.: {"holiday": "calendario-2026.json", "weather": "inmet-londrina.csv"}.', verbose_name='origens')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'contexto do dia',
                'verbose_name_plural': 'contextos do dia',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='backstage_daycontext_date')],
            },
        ),
    ]
