# Generated by Django 6.0.5 on 2026-08-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0008_day_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='sku')),
                ('channel_ref', models.CharField(db_index=True, max_length=64, verbose_name='canal')),
                ('started_at', models.DateTimeField(verbose_name='ficou indisponível em')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Vazio = ainda indisponível agora.', null=True, verbose_name='voltou em')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'indisponibilidade',
                'verbose_name_plural': 'indisponibilidades',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sku', 'started_at'], name='backstage_outage_sku_start'), models.Index(fields=['channel_ref', 'started_at'], name='backstage_outage_ch_start')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('sku', 'channel_ref'), name='backstage_outage_one_open_per_sku_channel')],
            },
        ),
    ]
