# Generated by Django 6.0.5 on 2026-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0008_day_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshift',
            name='difference_q',
            field=models.IntegerField(blank=True, help_text='Diferença: contado - esperado (positivo = sobra).', null=True),
        ),
    ]
