# Generated by Django 6.0.5 on 2026-08-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0009_shelf_outage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfoutage',
            name='reason',
            field=models.CharField(choices=[('sold_out', 'Esgotado'), ('paused', 'Pausado')], db_index=True, default='sold_out', help_text='Por que não dava para comprar. Pausa tem precedência sobre falta: produto pausado não é vendável nem com estoque cheio.', max_length=16, verbose_name='motivo'),
        ),
    ]
