# Generated by Django 6.0.5 on 2026-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0010_outage_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycontext',
            name='closed_reason',
            field=models.CharField(blank=True, help_text='Por que não abriu: feriado, férias coletivas, dia sem expediente regular. Vazio quando abriu.', max_length=120, verbose_name='motivo do fechamento'),
        ),
        migrations.AddField(
            model_name='daycontext',
            name='closes_at',
            field=models.TimeField(blank=True, null=True, verbose_name='fechou às'),
        ),
        migrations.AddField(
            model_name='daycontext',
            name='open_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Quanto tempo a casa esteve aberta NESTE dia, congelado. 0 = não abriu. Nulo = não sabemos (dia anterior à medição).', null=True, verbose_name='minutos de expediente'),
        ),
        migrations.AddField(
            model_name='daycontext',
            name='opens_at',
            field=models.TimeField(blank=True, null=True, verbose_name='abriu às'),
        ),
    ]
