# Generated by Django 6.0.5 on 2026-08-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0011_business_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationEpisodeKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=32, unique=True, verbose_name='ref')),
                ('label', models.CharField(max_length=80, verbose_name='rótulo')),
                ('hint', models.CharField(blank=True, help_text='Segunda linha do botão, para o operador escolher sem pensar.', max_length=140, verbose_name='dica')),
                ('affects_demand', models.BooleanField(default=True, help_text='Se sim, o dia sai da amostra que ensina quanto produzir — um dia atípico não deve virar previsão.', verbose_name='atrapalhou a venda')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'tipo de episódio',
                'verbose_name_plural': 'tipos de episódio',
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OperationEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='começou em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='terminou em')),
                ('status', models.CharField(choices=[('suspected', 'A confirmar'), ('confirmed', 'Confirmado'), ('dismissed', 'Descartado')], db_index=True, default='suspected', max_length=16, verbose_name='situação')),
                ('detected_signal', models.CharField(blank=True, help_text="O que o sistema mediu, em português, para a pergunta fazer sentido: 'nenhuma venda entre 14h e 16h'.", max_length=200, verbose_name='sinal detectado')),
                ('detector', models.CharField(blank=True, db_index=True, help_text='Quem levantou a lebre — usado para não duplicar o mesmo sinal.', max_length=32, verbose_name='detector')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('resolved_by', models.CharField(blank=True, max_length=100, verbose_name='respondido por')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('kind', models.ForeignKey(blank=True, help_text='Vazio enquanto ninguém explicou. O sistema nunca preenche.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='backstage.operationepisodekind', verbose_name='o que houve')),
            ],
            options={
                'verbose_name': 'episódio de operação',
                'verbose_name_plural': 'episódios de operação',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='backstage_episode_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('detector__gt', '')), fields=('detector', 'started_at'), name='backstage_episode_one_per_detection')],
            },
        ),
    ]
