# Generated by Django 6.0.5 on 2026-08-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0012_operation_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='receipt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='impresso em'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='receipt_detail',
            field=models.CharField(blank=True, default='', help_text='Por que não imprimiu, quando não imprimiu.', max_length=200, verbose_name='detalhe do comprovante'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='receipt_status',
            field=models.CharField(choices=[('pending', 'Sem confirmação'), ('printed', 'Impresso'), ('failed', 'Falhou'), ('skipped', 'Sem impressora')], default='pending', max_length=10, verbose_name='comprovante'),
        ),
    ]
