# Generated by Django 6.0.5 on 2026-08-15 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0014_alter_cashshift_difference_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='amount_q',
            field=models.IntegerField(help_text='Valor em centavos (sempre positivo).', verbose_name='valor (centavos)'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='approved_by',
            field=models.CharField(blank=True, default='', help_text='Gerente que autorizou a retirada (sangria e ajuste negativo).', max_length=150, verbose_name='aprovado por'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='motivo'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='blind_closing_amount_q',
            field=models.IntegerField(blank=True, help_text='Valor contado no fechamento cego em centavos.', null=True, verbose_name='contagem cega (centavos)'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fechado em'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='difference_q',
            field=models.IntegerField(blank=True, help_text='Diferença: contado - esperado (positivo = sobra).', null=True, verbose_name='diferença (centavos)'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='expected_amount_q',
            field=models.IntegerField(blank=True, help_text='Calculado: abertura + vendas_dinheiro + suprimentos - sangrias.', null=True, verbose_name='valor esperado (centavos)'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='aberto em'),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='opening_amount_q',
            field=models.IntegerField(default=0, help_text='Valor de abertura em centavos (fundo de troco).', verbose_name='valor de abertura (centavos)'),
        ),
        migrations.AlterField(
            model_name='operationchecklistrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='backstage.operationchecklisttemplate', verbose_name='modelo de checklist'),
        ),
        migrations.AlterField(
            model_name='operationtaskrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='backstage.operationtasktemplate', verbose_name='modelo de tarefa'),
        ),
        migrations.AlterField(
            model_name='operatoralert',
            name='type',
            field=models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('payment_insufficient', 'Pagamento abaixo do total'), ('payment_reconciliation_failed', 'Reconciliação de pagamento falhou'), ('webhook_failed', 'Webhook falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('coupon_over_redeemed', 'Cupom resgatado acima do limite'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível'), ('stale_new_order', 'Pedido parado aguardando confirmação'), ('production_late', 'Produção atrasada'), ('production_low_yield', 'Produção com yield baixo'), ('production_stock_short', 'Produção sem insumo suficiente'), ('directive_failed_spike', 'Tarefas de fundo falhando'), ('directive_backlog', 'Fila de tarefas de fundo acumulada'), ('directive_worker_stale', 'Processador de tarefas de fundo parado'), ('lifecycle_phase_stuck', 'Fase do pedido travada'), ('low_rating', 'Avaliação baixa recebida')], max_length=50, verbose_name='tipo'),
        ),
    ]
