# Generated by Django 6.0.5 on 2026-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0014_rotulos_em_portugues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationepisode',
            name='detector',
            field=models.CharField(blank=True, db_index=True, help_text='Quem levantou a lebre — usado para não duplicar o mesmo sinal.', max_length=32, verbose_name='quem detectou'),
        ),
    ]
