# Generated by Django 6.0.5 on 2026-08-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0016_rotulos_em_portugues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycontext',
            name='is_holiday_eve',
        ),
        migrations.RemoveField(
            model_name='daycontext',
            name='is_post_holiday',
        ),
        migrations.AddField(
            model_name='daycontext',
            name='commercial_name',
            field=models.CharField(blank=True, help_text='Data que move o movimento sem ser feriado (ou além de ser).', max_length=120, verbose_name='data comercial'),
        ),
        migrations.AddField(
            model_name='daycontext',
            name='is_post_special',
            field=models.BooleanField(default=False, help_text='Derivado na carga: o dia seguinte a um feriado ou data comercial.', verbose_name='volta de data especial'),
        ),
        migrations.AddField(
            model_name='daycontext',
            name='is_special_eve',
            field=models.BooleanField(default=False, help_text='Derivado na carga: o dia anterior a um feriado ou data comercial.', verbose_name='véspera de data especial'),
        ),
    ]
