# Generated by Django 6.0.5 on 2026-08-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0017_remove_daycontext_is_holiday_eve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycontext',
            name='eve_of',
            field=models.CharField(blank=True, help_text='Nome da data especial do dia seguinte. Derivado na carga.', max_length=120, verbose_name='véspera de'),
        ),
    ]
