# Generated by Django 6.0.5 on 2026-08-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0018_daycontext_eve_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=32, unique=True, verbose_name='ref')),
                ('label', models.CharField(max_length=80, verbose_name='rótulo')),
                ('hint', models.CharField(blank=True, help_text='Para quem etiqueta escolher sem pensar duas vezes.', max_length=140, verbose_name='dica')),
                ('anchors_dine_in', models.BooleanField(default=False, help_text='Item cuja presença indica que a pessoa consumiu aqui — bebida preparada, bebida pronta, prato quente. Na Nelson, levar bebida é desprezível, e é isso que faz a âncora funcionar.', verbose_name='ancora consumo local')),
                ('travels', models.BooleanField(default=False, help_text="Pão, varejo, mercearia. Junto de uma âncora vira 'consumiu e levou'; sozinho, é uma compra para levar.", verbose_name='é item de levar')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'papel de consumo',
                'verbose_name_plural': 'papéis de consumo',
                'ordering': ['ordering', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ProductConsumptionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='sku')),
                ('note', models.CharField(blank=True, help_text='Por que este papel, quando o nome do produto engana.', max_length=140, verbose_name='observação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='backstage.consumptionrole', verbose_name='papel')),
            ],
            options={
                'verbose_name': 'etiqueta de consumo',
                'verbose_name_plural': 'etiquetas de consumo',
                'ordering': ['sku'],
            },
        ),
    ]
