"""Aposenta o tipo `ajuste` do movimento de caixa.

`ajuste` era aritmeticamente idêntico aos outros dois: entrava com sinal na
fórmula do fechamento (`+X` somava como suprimento, `−X` subtraía como sangria).
Não existia terceira coisa — dinheiro entra ou dinheiro sai.

Pior que redundante: seus motivos eram "Sobra" e "Falta", que são o RESULTADO
que `CashShift.close()` calcula (`diferença = contado − esperado`). Lançar a
diferença como movimento empurrava o esperado até bater com a contagem e zerava
a divergência que a contagem cega existe para revelar.

⚠️ Nenhum `ajuste` foi gravado até aqui (conferido no staging: zero registros dos
três tipos), então esta migração não precisa converter dado nenhum. Se um dia
precisar, a conversão é direta: `+X` vira suprimento, `−X` vira sangria.
"""

# Generated by Django 6.0.5 on 2026-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0018_daycontext_eve_of'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashmovement',
            name='backstage_cashmovement_amount_positive',
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='approved_by',
            field=models.CharField(blank=True, default='', help_text='Gerente que autorizou a retirada (sangria).', max_length=150, verbose_name='aprovado por'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('sangria', 'Sangria'), ('suprimento', 'Suprimento')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_q__gt', 0)), name='backstage_cashmovement_amount_positive'),
        ),
    ]
