# Generated by Django 6.0.5 on 2026-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0019_consumptionrole_productconsumptiontag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=32, unique=True, verbose_name='ref')),
                ('label', models.CharField(max_length=80, verbose_name='rótulo')),
                ('kind', models.CharField(choices=[('table', 'Mesa'), ('counter', 'Lugar de balcão')], default='table', max_length=16, verbose_name='tipo')),
                ('area', models.CharField(blank=True, help_text='Salão interno, calçada, balcão. Só para o gestor se localizar.', max_length=40, verbose_name='área')),
                ('seats', models.PositiveSmallIntegerField(default=2, help_text='Quantas pessoas cabem com conforto. A casa aperta mais; isto é o nominal.', verbose_name='lugares')),
                ('counts_in_capacity', models.BooleanField(default=True, help_text='Desmarque o que só é usado em dia cheio (bistrô em pé, bancão externo). Fora da conta, eles não escondem o momento em que a casa bateu no teto — que é o que interessa medir.', verbose_name='conta na capacidade oficial')),
                ('active_from', models.DateField(blank=True, help_text='Vazio = sempre existiu. Preencher evita reescrever o passado.', null=True, verbose_name='existe desde')),
                ('active_until', models.DateField(blank=True, null=True, verbose_name='existiu até')),
            ],
            options={
                'verbose_name': 'lugar do salão',
                'verbose_name_plural': 'lugares do salão',
                'ordering': ['kind', 'ref'],
            },
        ),
    ]
