# Generated by Django 6.0.5 on 2026-08-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0019_retire_cash_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('sangria', 'Saída de caixa'), ('suprimento', 'Entrada de caixa')], max_length=20, verbose_name='Tipo'),
        ),
    ]
