# Generated by Django 6.0.5 on 2026-08-17 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0020_cash_movement_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=32, unique=True, verbose_name='ref')),
                ('label', models.CharField(max_length=80, verbose_name='rótulo')),
                ('hint', models.CharField(blank=True, help_text='Para quem etiqueta escolher sem pensar duas vezes.', max_length=140, verbose_name='dica')),
                ('reading', models.CharField(choices=[('anchor', 'Consome aqui'), ('takeaway', 'Leva'), ('hybrid', 'Híbrido')], default='hybrid', help_text="Consome aqui: bebida, prato, lanche — a presença indica alguém que sentou (nesta casa, levar bebida é desprezível). Leva: pão, varejo — junto de uma âncora vira 'consumiu e levou'. Híbrido: croissant, doce, pão japonês — serve aos dois usos, então não decide sozinho, mas tira a cesta do balde 'sem etiqueta'.", max_length=16, verbose_name='o que diz sobre a cesta')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'papel de consumo',
                'verbose_name_plural': 'papéis de consumo',
                'ordering': ['ordering', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SeatingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=32, unique=True, verbose_name='ref')),
                ('label', models.CharField(max_length=80, verbose_name='rótulo')),
                ('kind', models.CharField(choices=[('table', 'Mesa'), ('counter', 'Lugar de balcão')], default='table', max_length=16, verbose_name='tipo')),
                ('area', models.CharField(blank=True, help_text='Salão interno, calçada, balcão. Só para o gestor se localizar.', max_length=40, verbose_name='área')),
                ('seats', models.PositiveSmallIntegerField(default=2, help_text='Quantas pessoas cabem com conforto. A casa aperta mais; isto é o nominal.', verbose_name='lugares')),
                ('counts_in_capacity', models.BooleanField(default=True, help_text='Desmarque o que só é usado em dia cheio (bistrô em pé, bancão externo). Fora da conta, eles não escondem o momento em que a casa bateu no teto — que é o que interessa medir.', verbose_name='conta na capacidade oficial')),
                ('active_from', models.DateField(blank=True, help_text='Vazio = sempre existiu. Preencher evita reescrever o passado.', null=True, verbose_name='existe desde')),
                ('active_until', models.DateField(blank=True, null=True, verbose_name='existiu até')),
            ],
            options={
                'verbose_name': 'lugar do salão',
                'verbose_name_plural': 'lugares do salão',
                'ordering': ['kind', 'ref'],
            },
        ),
        migrations.CreateModel(
            name='ProductConsumptionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='sku')),
                ('note', models.CharField(blank=True, help_text='Por que este papel, quando o nome do produto engana.', max_length=140, verbose_name='observação')),
                ('reviewed', models.BooleanField(default=False, help_text="Etiqueta proposta pela coleção do catálogo entra FALSA. Proposta não é curadoria: o nome engana (o 'Hambúrguer 100g' é o pão), e número calculado sobre palpite não pode parecer conferido.", verbose_name='revisada por gente')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='backstage.consumptionrole', verbose_name='papel')),
            ],
            options={
                'verbose_name': 'etiqueta de consumo',
                'verbose_name_plural': 'etiquetas de consumo',
                'ordering': ['sku'],
            },
        ),
    ]
