# Generated by Django 6.0.5 on 2026-08-18 13:25
"""O log de eventos do PDV nasce, e leva junto a trilha que já existia.

Aberturas de gaveta (``drawer_openings``) e pedidos de troco (``change_requests``)
viviam como listas em ``CashShift.metadata``. Criar a tabela e deixar as listas
para trás apagaria a única trilha que o balcão tinha até aqui: o dado vira
evento e sai do metadata na mesma migração, para não haver dois lugares.

Sem espelho no ``reverse``: voltar apagaria a tabela e a trilha junto. Quem
precisar voltar restaura o backup.
"""

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.dateparse import parse_datetime


def _when(raw, fallback):
    parsed = parse_datetime(str(raw or "")) if raw else None
    if parsed is None:
        return fallback
    if timezone.is_naive(parsed):
        parsed = timezone.make_aware(parsed)
    return parsed


def carry_metadata_trails_into_the_log(apps, schema_editor):
    CashShift = apps.get_model("backstage", "CashShift")
    POSEvent = apps.get_model("backstage", "POSEvent")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    users = {}

    def user_for(username):
        username = str(username or "").strip()
        if not username:
            return None
        if username not in users:
            users[username] = User.objects.filter(username=username).first()
        return users[username]

    for shift in CashShift.objects.exclude(metadata={}).iterator():
        metadata = dict(shift.metadata or {})
        openings = metadata.pop("drawer_openings", None) or []
        requests = metadata.pop("change_requests", None) or []
        if not openings and not requests:
            continue
        for entry in openings:
            POSEvent.objects.create(
                kind="drawer_opened",
                at=_when(entry.get("at"), shift.opened_at),
                shift=shift,
                terminal_id=shift.terminal_id,
                operator=user_for(entry.get("by")),
                payload={"reason": str(entry.get("reason") or "")},
            )
        for entry in requests:
            ref = str(entry.get("ref") or "")
            POSEvent.objects.create(
                kind="change_requested",
                at=_when(entry.get("requested_at"), shift.opened_at),
                shift=shift,
                terminal_id=shift.terminal_id,
                operator=user_for(entry.get("requested_by")),
                payload={
                    "ref": ref,
                    "kind": str(entry.get("kind") or ""),
                    "amount_q": int(entry.get("amount_q") or 0),
                    "note": str(entry.get("note") or ""),
                    "requested_by": str(entry.get("requested_by") or ""),
                },
            )
            status = entry.get("status")
            if status == "served":
                POSEvent.objects.create(
                    kind="change_served",
                    at=_when(entry.get("served_at"), shift.opened_at),
                    shift=shift,
                    terminal_id=shift.terminal_id,
                    operator=user_for(entry.get("requested_by")),
                    payload={"ref": ref, "served_by": str(entry.get("served_by") or "")},
                )
            elif status == "cancelled":
                POSEvent.objects.create(
                    kind="change_cancelled",
                    at=_when(entry.get("cancelled_at"), shift.opened_at),
                    shift=shift,
                    terminal_id=shift.terminal_id,
                    operator=user_for(entry.get("requested_by")),
                    payload={"ref": ref},
                )
        shift.metadata = metadata
        shift.save(update_fields=["metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0021_consumptionrole_seatingspot_productconsumptiontag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='quando')),
                ('kind', models.CharField(choices=[('shift_opened', 'Caixa aberto'), ('shift_closed', 'Caixa fechado'), ('cash_in', 'Entrada de caixa'), ('cash_out', 'Saída de caixa'), ('drawer_opened', 'Gaveta aberta sem venda'), ('drawer_unlocked', 'Trava da gaveta liberada'), ('change_requested', 'Troco pedido'), ('change_served', 'Troco atendido'), ('change_cancelled', 'Pedido de troco cancelado'), ('day_closed', 'Dia fechado'), ('reconciliation_failed', 'Reconciliação com divergência')], max_length=32, verbose_name='tipo')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='O específico de cada tipo. Schema em docs/reference/data-schemas.md.', verbose_name='detalhe')),
                ('order_ref', models.CharField(blank=True, default='', max_length=50, verbose_name='ref do pedido')),
                ('movement', models.ForeignKey(blank=True, help_text='A linha do dinheiro, quando o evento é sangria ou suprimento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='backstage.cashmovement', verbose_name='movimentação')),
                ('operator', models.ForeignKey(blank=True, help_text='Quem causou o evento. Vazio quando foi o sistema (reconciliação, varredura).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_events', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='backstage.cashshift', verbose_name='turno')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='backstage.posterminal', verbose_name='terminal')),
            ],
            options={
                'verbose_name': 'evento do PDV',
                'verbose_name_plural': 'eventos do PDV',
                'ordering': ['at', 'id'],
                'indexes': [models.Index(fields=['at'], name='posevent_at_idx'), models.Index(fields=['operator', 'at'], name='posevent_op_at_idx'), models.Index(fields=['shift', 'at'], name='posevent_shift_at_idx'), models.Index(fields=['kind', 'at'], name='posevent_kind_at_idx')],
            },
        ),
        migrations.RunPython(carry_metadata_trails_into_the_log, migrations.RunPython.noop),
    ]
