# Generated by Django 6.0.5 on 2026-08-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0021_consumptionrole_seatingspot_productconsumptiontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrole',
            name='beverage',
            field=models.CharField(blank=True, choices=[('', 'Não é bebida'), ('prepared', 'Bebida preparada'), ('ready', 'Bebida pronta')], default='', help_text="Preparada: café, chá, frappé — feita na casa. Pronta: água, refrigerante, suco de garrafa. Conta só o que se bebe aqui; café em grão e chá em lata ficam como 'não é bebida'.", max_length=16, verbose_name='bebida'),
        ),
        migrations.AlterField(
            model_name='productconsumptiontag',
            name='sku',
            field=models.CharField(help_text="SKU do produto. Linha do histórico SEM sku (ex.: os combos do Yooga) se etiqueta pelo nome exato, com o prefixo 'nome:' — 'nome:Combo Cola + Hotdog'. É a mesma chave que o B.I. usa para essas linhas.", max_length=64, unique=True, verbose_name='sku'),
        ),
    ]
