# Generated by Django 6.0.5 on 2026-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0022_consumptionrole_beverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrole',
            name='eat_in_weight',
            field=models.PositiveSmallIntegerField(default=50, help_text="Probabilidade de o produto ser consumido na casa quando aparece na cesta, de 0 a 100. É o que transforma a vocação (0 ou 1) numa estimativa: 'consome aqui' perto de 100, 'leva' perto de 0, 'híbrido' no meio. Cada SKU pode ter o seu próprio peso.", verbose_name='peso de consumo local (%)'),
        ),
        migrations.AddField(
            model_name='productconsumptiontag',
            name='eat_in_weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Vazio = herda o peso do papel. Preencha para dizer, deste produto, quantas vezes em 100 ele é consumido aqui quando está na cesta. A dica ao lado mostra o que o histórico sabe: % das vendas dele com bebida e % em lote (4+).', null=True, verbose_name='peso de consumo local (%)'),
        ),
    ]
