# De-paras do B.I. como dado (BI-DATA-FOUNDATION-PLAN, P1). Só schema: as regras
# padrão da loja entram pelo seed / `setup_bi_reference`, nunca por migração.
# Generated by Django 6.0.5 on 2026-08-19 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0024_importbatch'),
        ('offerman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'proposto'), ('confirmed', 'confirmado'), ('rejected', 'rejeitado')], default='proposed', max_length=10, verbose_name='estado')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='0–100 quando a máquina sugeriu; vazio quando alguém escreveu à mão.', null=True, verbose_name='confiança da sugestão')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('pattern', models.CharField(help_text="Minúsculo; casa por 'contém'. A primeira linha que casa (menor posição) vence.", max_length=100, unique=True, verbose_name='trecho da categoria')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="O específico vem antes do genérico: 'pães finos' antes de 'pão'.", verbose_name='posição')),
                ('reading', models.CharField(blank=True, choices=[('anchor', 'Consome aqui'), ('takeaway', 'Leva'), ('hybrid', 'Híbrido')], help_text='Reserva para linha sem etiqueta de SKU. Vazio = a categoria não decide.', max_length=16, verbose_name='o que diz sobre a cesta')),
                ('collection', models.ForeignKey(blank=True, help_text='A categoria canônica, quando existe. Opcional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_category_aliases', to='offerman.collection', verbose_name='coleção do catálogo')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
            ],
            options={
                'verbose_name': 'de-para de categoria',
                'verbose_name_plural': 'de-paras de categoria',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'proposto'), ('confirmed', 'confirmado'), ('rejected', 'rejeitado')], default='proposed', max_length=10, verbose_name='estado')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='0–100 quando a máquina sugeriu; vazio quando alguém escreveu à mão.', null=True, verbose_name='confiança da sugestão')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('pattern', models.CharField(help_text="Minúsculo; casa por 'contém'. A primeira linha que casa (menor posição) vence.", max_length=100, unique=True, verbose_name='trecho da forma de pagamento')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="O específico vem antes do genérico: 'vale refeição' antes de 'vale'.", verbose_name='posição')),
                ('method_key', models.CharField(blank=True, help_text='Chave da casa: cash, pix, credit, debit, voucher, ifood, card, external.', max_length=32, verbose_name='forma canônica')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
            ],
            options={
                'verbose_name': 'de-para de forma de pagamento',
                'verbose_name_plural': 'de-paras de forma de pagamento',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'proposto'), ('confirmed', 'confirmado'), ('rejected', 'rejeitado')], default='proposed', max_length=10, verbose_name='estado')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='0–100 quando a máquina sugeriu; vazio quando alguém escreveu à mão.', null=True, verbose_name='confiança da sugestão')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('source', models.CharField(db_index=True, max_length=16, verbose_name='origem')),
                ('external_sku', models.CharField(blank=True, db_index=True, help_text='Vazio quando a linha da origem não traz SKU: aí o de-para é pelo nome.', max_length=64, verbose_name='SKU na origem')),
                ('external_name', models.CharField(blank=True, max_length=200, verbose_name='nome na origem')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por')),
                ('product', models.ForeignKey(blank=True, help_text='Vazio = produto extinto ou ainda sem correspondência.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_aliases', to='offerman.product', verbose_name='produto do catálogo')),
            ],
            options={
                'verbose_name': 'de-para de produto',
                'verbose_name_plural': 'de-paras de produto',
                'ordering': ['source', 'external_sku', 'external_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_sku', ''), _negated=True), fields=('source', 'external_sku'), name='backstage_productalias_source_sku'), models.UniqueConstraint(condition=models.Q(('external_sku', '')), fields=('source', 'external_name'), name='backstage_productalias_source_name'), models.CheckConstraint(condition=models.Q(('external_name', ''), ('external_sku', ''), _negated=True), name='backstage_productalias_has_key')],
            },
        ),
    ]
