# A série diária materializada do B.I. (BI-DATA-FOUNDATION-PLAN, P3): tabela
# derivada, recomputável do zero por `refresh_bi_daily_series --all`.
# Generated by Django 6.0.5 on 2026-08-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0025_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='dia')),
                ('source', models.CharField(blank=True, help_text='Quem respondeu pelo dia: shopman, yooga, seed… Vazio quando o dia não teve venda.', max_length=16, verbose_name='origem')),
                ('revenue_q', models.BigIntegerField(default=0, verbose_name='faturamento (centavos)')),
                ('orders', models.PositiveIntegerField(default=0, verbose_name='vendas')),
                ('cash_orders', models.PositiveIntegerField(default=0, help_text='Vendas com alguma parcela em espécie, entre as de forma conhecida.', verbose_name='vendas com dinheiro')),
                ('payments_known', models.PositiveIntegerField(default=0, help_text='Denominador da fatia de dinheiro. Zero conhecido é ausência, não zero.', verbose_name='vendas com forma conhecida')),
                ('historical_dropped', models.PositiveIntegerField(default=0, help_text='Vendas históricas que ficaram de fora porque o dia teve pedido nativo (o dia nativo vence).', verbose_name='histórico descartado')),
                ('refreshed_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'venda do dia (materializada)',
                'verbose_name_plural': 'vendas por dia (materializadas)',
                'ordering': ['-date'],
            },
        ),
    ]
