# Generated by Django 6.0.5 on 2026-08-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0026_dailysalesfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=48, unique=True, verbose_name='ref')),
                ('label', models.CharField(max_length=120, verbose_name='rótulo')),
                ('metric', models.CharField(choices=[('import_silence', 'Importação esperada não chegou'), ('daily_revenue_vs_baseline', 'Faturamento do dia abaixo do esperado')], max_length=32, verbose_name='métrica')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('severity', models.CharField(choices=[('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='warning', max_length=10, verbose_name='severidade')),
                ('cooldown_minutes', models.PositiveIntegerField(help_text='Obrigatório. Depois de disparar, a regra não avisa de novo antes disto — alarme que grita a cada ciclo vira ruído e o aviso legítimo morre junto.', verbose_name='silêncio após disparar (minutos)')),
                ('source', models.CharField(blank=True, help_text="Só para 'importação esperada não chegou': a origem (ex.: yooga).", max_length=16, verbose_name='origem esperada')),
                ('expected_every_days', models.PositiveSmallIntegerField(blank=True, help_text="Só para 'importação esperada não chegou': a cadência esperada de lote concluído.", null=True, verbose_name='a cada quantos dias')),
                ('threshold_percent', models.PositiveSmallIntegerField(blank=True, help_text="Só para 'faturamento abaixo do esperado': ontem < X% da média do mesmo dia da semana.", null=True, verbose_name='dispara abaixo de (% do esperado)')),
                ('baseline_weeks', models.PositiveSmallIntegerField(default=4, help_text='Quantas semanas para trás entram na média do mesmo dia da semana.', verbose_name='semanas de baseline')),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='avaliado em')),
                ('last_fired_at', models.DateTimeField(blank=True, null=True, verbose_name='disparou em')),
                ('last_reading', models.JSONField(blank=True, default=dict, help_text='{value, baseline, fired, message} da última avaliação. Ausência de valor = a regra não opinou.', verbose_name='última leitura')),
            ],
            options={
                'verbose_name': 'alarme do B.I.',
                'verbose_name_plural': 'alarmes do B.I.',
                'ordering': ['label'],
            },
        ),
        migrations.AlterField(
            model_name='operatoralert',
            name='type',
            field=models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('payment_insufficient', 'Pagamento abaixo do total'), ('payment_reconciliation_failed', 'Reconciliação de pagamento falhou'), ('webhook_failed', 'Webhook falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('coupon_over_redeemed', 'Cupom resgatado acima do limite'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível'), ('stale_new_order', 'Pedido parado aguardando confirmação'), ('production_late', 'Produção atrasada'), ('production_low_yield', 'Produção com yield baixo'), ('production_stock_short', 'Produção sem insumo suficiente'), ('directive_failed_spike', 'Tarefas de fundo falhando'), ('directive_backlog', 'Fila de tarefas de fundo acumulada'), ('directive_worker_stale', 'Processador de tarefas de fundo parado'), ('lifecycle_phase_stuck', 'Fase do pedido travada'), ('low_rating', 'Avaliação baixa recebida'), ('bi_import_silence', 'B.I.: importação esperada não chegou'), ('bi_below_baseline', 'B.I.: movimento abaixo do esperado')], max_length=50, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='BIAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='disparou em')),
                ('severity', models.CharField(choices=[('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], max_length=10, verbose_name='severidade')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='valor medido')),
                ('baseline', models.FloatField(blank=True, null=True, verbose_name='esperado')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('operator_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bi_alert_events', to='backstage.operatoralert', verbose_name='aviso ao operador')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='backstage.bialertrule', verbose_name='alarme')),
            ],
            options={
                'verbose_name': 'disparo de alarme do B.I.',
                'verbose_name_plural': 'disparos de alarme do B.I.',
                'ordering': ['-fired_at'],
            },
        ),
    ]
