# Generated by Django 6.0.5 on 2026-08-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0027_bi_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bialertrule',
            name='lookback_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Janela das métricas acumuladas: histórico apagado, quebra de caixa.', verbose_name='olhar para trás (dias)'),
        ),
        migrations.AddField(
            model_name='bialertrule',
            name='max_native_orders',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Só para 'pedido nativo apagou histórico': dia com ATÉ isto de pedidos nativos…", null=True, verbose_name='até quantos pedidos nativos'),
        ),
        migrations.AddField(
            model_name='bialertrule',
            name='min_historical_dropped',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='…que apagou mais de quantas vendas históricas'),
        ),
        migrations.AddField(
            model_name='bialertrule',
            name='threshold_q',
            field=models.BigIntegerField(blank=True, help_text="Só para 'quebra de caixa acumulada': |Σ quebra| de um operador na janela acima disto dispara.", null=True, verbose_name='régua em centavos'),
        ),
        migrations.AlterField(
            model_name='bialertrule',
            name='metric',
            field=models.CharField(choices=[('import_silence', 'Importação esperada não chegou'), ('daily_revenue_vs_baseline', 'Faturamento do dia abaixo do esperado'), ('native_overrides_history', 'Pedido nativo apagou histórico'), ('cash_variance_by_operator', 'Quebra de caixa acumulada por operador'), ('curation_pending', 'De-para de produto pendente')], max_length=32, verbose_name='métrica'),
        ),
        migrations.AlterField(
            model_name='operatoralert',
            name='type',
            field=models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('payment_insufficient', 'Pagamento abaixo do total'), ('payment_reconciliation_failed', 'Reconciliação de pagamento falhou'), ('webhook_failed', 'Webhook falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('coupon_over_redeemed', 'Cupom resgatado acima do limite'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível'), ('stale_new_order', 'Pedido parado aguardando confirmação'), ('production_late', 'Produção atrasada'), ('production_low_yield', 'Produção com yield baixo'), ('production_stock_short', 'Produção sem insumo suficiente'), ('directive_failed_spike', 'Tarefas de fundo falhando'), ('directive_backlog', 'Fila de tarefas de fundo acumulada'), ('directive_worker_stale', 'Processador de tarefas de fundo parado'), ('lifecycle_phase_stuck', 'Fase do pedido travada'), ('low_rating', 'Avaliação baixa recebida'), ('bi_import_silence', 'B.I.: importação esperada não chegou'), ('bi_below_baseline', 'B.I.: movimento abaixo do esperado'), ('bi_source_conflict', 'B.I.: pedido nativo apagou histórico'), ('bi_cash_variance', 'B.I.: quebra de caixa acumulada passou da régua'), ('bi_curation_pending', 'B.I.: de-para de produto pendente')], max_length=50, verbose_name='tipo'),
        ),
    ]
