# Generated by Django 6.0.5 on 2026-08-19 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0028_bi_alerts_3_to_5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BIScenarioReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='gerado em')),
                ('focus', models.CharField(choices=[('sales', 'Vendas'), ('production', 'Produção')], max_length=16, verbose_name='foco')),
                ('window_from', models.DateField(verbose_name='janela de')),
                ('window_to', models.DateField(verbose_name='janela até')),
                ('model', models.CharField(blank=True, max_length=64, verbose_name='modelo')),
                ('status', models.CharField(choices=[('done', 'concluído'), ('failed', 'falhou')], default='done', max_length=8, verbose_name='estado')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duração (ms)')),
                ('inputs_hash', models.CharField(blank=True, help_text='sha256 dos agregados enviados: duas rodadas com o mesmo hash viram a mesma pergunta.', max_length=64, verbose_name='hash das entradas')),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Os agregados que a IA viu — só camada de leitura, com unidade. Nunca dado pessoal.', verbose_name='entradas')),
                ('scenarios', models.JSONField(blank=True, default=list, help_text='[{title, basis[], proposal, unknowns[]}] como a IA devolveu, validado.', verbose_name='cenários')),
                ('raw_text', models.TextField(blank=True, verbose_name='resposta crua')),
                ('error', models.TextField(blank=True, verbose_name='erro')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='pedido por')),
            ],
            options={
                'verbose_name': 'cenários gerados pela IA',
                'verbose_name_plural': 'cenários gerados pela IA',
                'ordering': ['-generated_at'],
            },
        ),
    ]
