"""Novo tipo de alerta: venda que entrou depois do fechamento do turno.

Só a lista de `choices` muda. O caso: o pedido commitou, a cobrança liquidou, e
entre um e outro o turno de caixa fechou — o livro-caixa é append-only num turno
ABERTO, então a linha da venda é recusada e o dinheiro fica sem lançamento.
Nenhum tipo existente serve: `payment_failed` é cobrança que não passou (esta
passou) e `payment_reconciliation_failed` é divergência achada no dia seguinte.
Este alerta é do instante, com o pedido no nome, para alguém conferir a gaveta
antes de o valor virar diferença anônima na contagem cega.
Ver `shopman/shop/services/pos.py::_settle_after_shift_closed`.
"""

# Generated by Django 6.0.5 on 2026-08-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0032_alert_payment_disputed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatoralert',
            name='type',
            field=models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('payment_insufficient', 'Pagamento abaixo do total'), ('payment_reconciliation_failed', 'Reconciliação de pagamento falhou'), ('payment_disputed', 'Cartão contestado (disputa)'), ('webhook_failed', 'Webhook falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('coupon_over_redeemed', 'Cupom resgatado acima do limite'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível'), ('stale_new_order', 'Pedido parado aguardando confirmação'), ('production_late', 'Produção atrasada'), ('production_low_yield', 'Produção com yield baixo'), ('production_stock_short', 'Produção sem insumo suficiente'), ('directive_failed_spike', 'Tarefas de fundo falhando'), ('directive_backlog', 'Fila de tarefas de fundo acumulada'), ('directive_worker_stale', 'Processador de tarefas de fundo parado'), ('lifecycle_phase_stuck', 'Fase do pedido travada'), ('low_rating', 'Avaliação baixa recebida'), ('cash_shift_open_at_closing', 'Caixa aberto no fechamento do dia'), ('cash_sale_after_shift_close', 'Venda entrou depois do fechamento do turno'), ('bi_import_silence', 'B.I.: importação esperada não chegou'), ('bi_below_baseline', 'B.I.: movimento abaixo do esperado'), ('bi_source_conflict', 'B.I.: pedido nativo apagou histórico'), ('bi_cash_variance', 'B.I.: quebra de caixa acumulada passou da régua'), ('bi_curation_pending', 'B.I.: de-para de produto pendente')], max_length=50, verbose_name='tipo'),
        ),
    ]
