# Generated by Django 6.0.5 on 2026-09-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0041_integration_failed_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatoralert',
            name='type',
            field=models.CharField(choices=[('notification_failed', 'Notificação falhou'), ('payment_failed', 'Pagamento falhou'), ('payment_insufficient', 'Pagamento abaixo do total'), ('payment_reconciliation_failed', 'Reconciliação de pagamento falhou'), ('payment_disputed', 'Cartão contestado (disputa)'), ('webhook_failed', 'Webhook falhou'), ('integration_failed', 'Integração externa falhou'), ('stock_discrepancy', 'Discrepância de estoque'), ('payment_after_cancel', 'Pagamento após cancelamento'), ('stock_low', 'Estoque baixo'), ('marketplace_rejected_unavailable', 'Marketplace rejeitado: indisponível'), ('marketplace_rejected_oos', 'Marketplace rejeitado: sem estoque'), ('coupon_over_redeemed', 'Cupom resgatado acima do limite'), ('pos_rejected_unavailable', 'POS rejeitado: produto indisponível'), ('stale_new_order', 'Pedido parado aguardando confirmação'), ('production_late', 'Produção atrasada'), ('production_low_yield', 'Produção com yield baixo'), ('production_stock_short', 'Produção sem insumo suficiente'), ('directive_failed_spike', 'Tarefas de fundo falhando'), ('directive_backlog', 'Fila de tarefas de fundo acumulada'), ('directive_worker_stale', 'Processador de tarefas de fundo parado'), ('lifecycle_phase_stuck', 'Fase do pedido travada'), ('low_rating', 'Avaliação baixa recebida'), ('cash_shift_open_at_closing', 'Caixa aberto no fechamento do dia'), ('cash_sale_after_shift_close', 'Venda entrou depois do fechamento do turno'), ('pos_drawer_sensor_blind', 'Sensor da gaveta parou de responder'), ('pos_drawer_left_open', 'Gaveta ficou aberta sem ninguém vender'), ('waitlist_released', 'Fila: vaga liberada'), ('bi_import_silence', 'B.I.: importação esperada não chegou'), ('bi_below_baseline', 'B.I.: movimento abaixo do esperado'), ('bi_source_conflict', 'B.I.: pedido nativo apagou histórico'), ('bi_cash_variance', 'B.I.: quebra de caixa acumulada passou da régua'), ('bi_curation_pending', 'B.I.: de-para de produto pendente'), ('concierge_handoff', 'WhatsApp: cliente pediu a equipe'), ('concierge_unavailable', 'WhatsApp: concierge fora do ar')], max_length=50, verbose_name='tipo'),
        ),
    ]
