# Generated by Django 6.0.5 on 2026-09-10.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backstage", "0057_quality_hold_risk_alerts"),
        ("cashman", "0005_shift_custody_is_the_drawer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintAgentCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="referência")),
                ("label", models.CharField(blank=True, default="", max_length=120, verbose_name="rótulo")),
                ("token_digest", models.CharField(editable=False, max_length=64, verbose_name="digest do token")),
                ("token_hint", models.CharField(editable=False, max_length=8, verbose_name="final do token")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                ("last_seen_at", models.DateTimeField(blank=True, null=True, verbose_name="vista por último em")),
                ("last_build", models.CharField(blank=True, default="", max_length=120, verbose_name="último build")),
                ("last_remote_addr", models.GenericIPAddressField(blank=True, null=True, verbose_name="último IP")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                ("rotated_at", models.DateTimeField(auto_now_add=True, verbose_name="rotacionada em")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="revogada em")),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_agent_credentials",
                        to="cashman.terminal",
                        verbose_name="terminal",
                    ),
                ),
            ],
            options={
                "verbose_name": "credencial do agente de impressão",
                "verbose_name_plural": "credenciais dos agentes de impressão",
                "ordering": ["terminal__ref", "label", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="referência")),
                ("kind", models.CharField(choices=[("production_weighing", "Pesagem cega"), ("production_preparation", "Etiqueta de preparo")], max_length=40, verbose_name="tipo")),
                ("transport", models.CharField(choices=[("relay", "Relay"), ("browser", "Navegador")], max_length=12, verbose_name="transporte")),
                ("status", models.CharField(choices=[("prepared", "Preparada no navegador"), ("queued", "Na fila"), ("leased", "Em envio"), ("spooled", "Enviada à impressora"), ("awaiting_confirmation", "Aguardando confirmação"), ("confirmed", "Confirmada"), ("failed", "Falhou"), ("uncertain", "Resultado incerto"), ("cancelled", "Cancelada"), ("expired", "Expirada")], default="queued", max_length=24, verbose_name="status")),
                ("requested_by_ref", models.CharField(max_length=150, verbose_name="identificação do solicitante")),
                ("requested_station_ref", models.CharField(blank=True, default="", max_length=80, verbose_name="estação solicitante")),
                ("source_revision", models.CharField(max_length=256, verbose_name="revisão de origem")),
                ("document", models.JSONField(verbose_name="documento congelado")),
                ("document_sha256", models.CharField(max_length=64, verbose_name="hash do documento")),
                ("renderer_version", models.PositiveSmallIntegerField(default=1, verbose_name="versão do renderizador")),
                ("payload", models.BinaryField(verbose_name="bytes ESC/POS")),
                ("payload_sha256", models.CharField(max_length=64, verbose_name="hash dos bytes")),
                ("payload_size", models.PositiveIntegerField(verbose_name="tamanho dos bytes")),
                ("label_count", models.PositiveSmallIntegerField(verbose_name="quantidade de etiquetas")),
                ("series_ref", models.UUIDField(default=uuid.uuid4, editable=False, verbose_name="série")),
                ("copy_number", models.PositiveSmallIntegerField(default=1, verbose_name="via")),
                ("confirmation", models.CharField(blank=True, choices=[("confirmed", "Impressão confirmada"), ("incomplete", "Impressão incompleta"), ("not_printed", "Não imprimiu")], default="", max_length=20, verbose_name="resultado confirmado")),
                ("confirmation_detail", models.CharField(blank=True, default="", max_length=500, verbose_name="detalhe da confirmação")),
                ("confirmed_at", models.DateTimeField(blank=True, null=True, verbose_name="confirmado em")),
                ("confirmed_by_ref", models.CharField(blank=True, default="", max_length=150, verbose_name="identificação de quem confirmou")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="expira em")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="backstage_print_jobs_confirmed", to=settings.AUTH_USER_MODEL, verbose_name="confirmado por")),
                ("reprint_of", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reprints", to="backstage.printjob", verbose_name="reimpressão de")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="backstage_print_jobs_requested", to=settings.AUTH_USER_MODEL, verbose_name="solicitado por")),
                ("target_terminal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="backstage_print_jobs", to="cashman.terminal", verbose_name="terminal de destino")),
            ],
            options={
                "verbose_name": "trabalho de impressão",
                "verbose_name_plural": "trabalhos de impressão",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="tentativa")),
                ("status", models.CharField(choices=[("leased", "Em envio"), ("spooled", "Enviada à impressora"), ("failed", "Falhou"), ("uncertain", "Resultado incerto"), ("expired", "Lease expirado"), ("browser_opened", "Diálogo do navegador aberto"), ("browser_unavailable", "Diálogo do navegador indisponível")], default="leased", max_length=24, verbose_name="status")),
                ("lease_token_digest", models.CharField(blank=True, default="", editable=False, max_length=64, verbose_name="digest do lease")),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True, verbose_name="lease expira em")),
                ("claimed_at", models.DateTimeField(auto_now_add=True, verbose_name="capturada em")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True, verbose_name="respondida em")),
                ("spooler_job_id", models.CharField(blank=True, default="", max_length=160, verbose_name="job do spooler")),
                ("agent_version", models.CharField(blank=True, default="", max_length=80, verbose_name="versão do agente")),
                ("agent_build", models.CharField(blank=True, default="", max_length=120, verbose_name="build do agente")),
                ("queue_name", models.CharField(blank=True, default="", max_length=160, verbose_name="fila observada")),
                ("health", models.CharField(blank=True, default="", max_length=40, verbose_name="saúde observada")),
                ("detail", models.CharField(blank=True, default="", max_length=500, verbose_name="detalhe")),
                ("ack_digest", models.CharField(blank=True, default="", editable=False, max_length=64, verbose_name="digest do ACK")),
                ("credential", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="attempts", to="backstage.printagentcredential", verbose_name="credencial")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attempts", to="backstage.printjob", verbose_name="trabalho")),
            ],
            options={
                "verbose_name": "tentativa de impressão",
                "verbose_name_plural": "tentativas de impressão",
                "ordering": ["job_id", "sequence"],
            },
        ),
        migrations.AddIndex(model_name="printjob", index=models.Index(fields=["target_terminal", "status", "created_at"], name="backstage_pj_target_status_idx")),
        migrations.AddConstraint(model_name="printjob", constraint=models.UniqueConstraint(fields=("series_ref", "copy_number"), name="backstage_printjob_unique_copy")),
        migrations.AddConstraint(model_name="printjob", constraint=models.CheckConstraint(condition=models.Q(("copy_number__gte", 1)), name="backstage_printjob_copy_positive")),
        migrations.AddConstraint(model_name="printjob", constraint=models.CheckConstraint(condition=models.Q(("label_count__gte", 1)), name="backstage_printjob_labels_positive")),
        migrations.AddConstraint(model_name="printattempt", constraint=models.UniqueConstraint(fields=("job", "sequence"), name="backstage_printattempt_unique_sequence")),
        migrations.AddConstraint(model_name="printattempt", constraint=models.CheckConstraint(condition=models.Q(("sequence__gte", 1)), name="backstage_printattempt_sequence_positive")),
    ]
