# Generated by Django 6.0.5 on 2026-09-11 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0060_merge_20260910_2002'),
        ('orderman', '0004_alter_sessionitem_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=100, verbose_name='nome/apelido')),
                ('identification', models.CharField(max_length=100, unique=True, verbose_name='identificação')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('current_order', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_device', to='orderman.order', verbose_name='entrega atual')),
            ],
            options={
                'verbose_name': 'maquininha de entrega',
                'verbose_name_plural': 'maquininhas de entrega',
                'ordering': ('label', 'pk'),
            },
        ),
    ]
