# Generated by Django 6.0.5 on 2026-09-12 21:00

import shopman.backstage.models.alerts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0066_merge_pos_concierge_identity_alerts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatoralert",
            name="type",
            field=models.CharField(
                choices=shopman.backstage.models.alerts.operator_alert_type_choices,
                max_length=50,
                verbose_name="tipo",
            ),
        ),
    ]
