# Generated by Django 6.0.5 on 2026-09-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0068_admin_two_factor_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdsticket',
            name='items',
            field=models.JSONField(default=list, help_text='[{"sku", "name", "qty", "notes", "line_id"}]', verbose_name='items'),
        ),
    ]
