# Generated by Django 6.1.1 on 2026-09-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0071_permissao_de_qc_fala_em_lote"),
    ]

    operations = [
        migrations.CreateModel(
            name="AliasBenchmarkReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="medido em"),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True, max_length=16, verbose_name="origem"
                    ),
                ),
                (
                    "cases",
                    models.PositiveIntegerField(verbose_name="de-paras confirmados"),
                ),
                (
                    "contenders",
                    models.CharField(max_length=240, verbose_name="concorrentes"),
                ),
                (
                    "skipped",
                    models.TextField(blank=True, verbose_name="fora do placar"),
                ),
                ("report", models.TextField(verbose_name="placar")),
            ],
            options={
                "verbose_name": "placar do de-para",
                "verbose_name_plural": "placares do de-para",
                "ordering": ["-created_at"],
            },
        ),
    ]
