# Generated by Django 6.1.1 on 2026-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0073_superusuario_perde_pin_do_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='order_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='kind',
            field=models.CharField(choices=[('production_weighing', 'Pesagem cega'), ('production_preparation', 'Etiqueta de preparo'), ('order_danfe', 'DANFE da entrega')], max_length=40, verbose_name='tipo'),
        ),
    ]
