# Generated by Django 6.1.1 on 2026-09-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0074_danfe_da_entrega_pelo_relay'),
        ('cashman', '0006_alter_terminal_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdsinstance',
            name='print_terminal',
            field=models.ForeignKey(blank=True, help_text='Estação sem tela: os pedidos desta estação saem impressos nesta impressora. Deixe vazio quando a estação acompanha os pedidos pela tela do KDS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kds_print_stations', to='cashman.terminal', verbose_name='impressora da estação'),
        ),
        migrations.AlterField(
            model_name='kdsinstance',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='text_size, dark_mode, refresh_interval, on_print, etc.', verbose_name='configurações'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='kind',
            field=models.CharField(choices=[('production_weighing', 'Pesagem cega'), ('production_preparation', 'Etiqueta de preparo'), ('order_danfe', 'DANFE da entrega'), ('kitchen_ticket', 'Via Cozinha')], max_length=40, verbose_name='tipo'),
        ),
    ]
