# Generated by Django 6.1.1 on 2026-09-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0076_estacao_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdsticket',
            name='completed_by',
            field=models.CharField(blank=True, default='', help_text='Quem deu a baixa (usuário do operador, ou o ator do sistema).', max_length=150, verbose_name='concluído por'),
        ),
        migrations.AddField(
            model_name='kdsticket',
            name='completed_via',
            field=models.CharField(blank=True, choices=[('station', 'Tela da estação'), ('exit', 'Saída'), ('pos', 'PDV'), ('scanner', 'Leitor de código'), ('order_advanced', 'Pedido avançado fora do KDS')], default='', max_length=20, verbose_name='concluído pela'),
        ),
    ]
