# Generated by Django 6.1.1 on 2026-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0078_importbatch_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorRecipeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_ref', models.CharField(db_index=True, max_length=150, verbose_name='operador')),
                ('entry_ref', models.CharField(max_length=50, verbose_name='receita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='marcada em')),
            ],
            options={
                'verbose_name': 'receita favorita',
                'verbose_name_plural': 'receitas favoritas',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('operator_ref', 'entry_ref'), name='uniq_operator_recipe_favorite')],
            },
        ),
    ]
