# Generated by Django 6.1.1 on 2026-10-01 10:15

import django.db.models.deletion
from django.db import migrations, models

#: Critérios iniciais da nota de receita (decisão D7, 01/10/2026). Ponto de
#: partida, não regra: o gestor renomeia, reordena ou desativa no Admin.
INITIAL_CRITERIA = (
    ("Sabor", "Gosto, sal, doçura e acidez, e o equilíbrio entre eles.", 10),
    ("Textura", "Miolo, casca, crocância ou cremosidade, do jeito que a receita pede.", 20),
    ("Aparência", "Cor, forma e acabamento.", 30),
)


def seed_initial_criteria(apps, schema_editor):
    criterion = apps.get_model("backstage", "RecipeRatingCriterion")
    for name, description, position in INITIAL_CRITERIA:
        criterion.objects.get_or_create(
            name=name, defaults={"description": description, "position": position, "is_active": True},
        )



class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0079_operatorrecipefavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRatingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('description', models.CharField(blank=True, default='', help_text='O que o operador olha para dar a nota. Aparece embaixo do nome, na tela de avaliar.', max_length=200, verbose_name='descrição')),
                ('position', models.IntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, help_text='Critério inativo sai da tela de avaliar e das médias; as notas antigas ficam guardadas.', verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'critério da nota de receita',
                'verbose_name_plural': 'critérios da nota de receita',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RecipeVersionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_ref', models.CharField(db_index=True, max_length=50, verbose_name='receita')),
                ('version_number', models.PositiveIntegerField(verbose_name='versão')),
                ('operator_ref', models.CharField(max_length=150, verbose_name='operador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='avaliada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'nota de receita',
                'verbose_name_plural': 'notas de receita',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('entry_ref', 'version_number', 'operator_ref'), name='uniq_recipe_version_rating_per_operator')],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersionRatingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='nota')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='backstage.reciperatingcriterion', verbose_name='critério')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='backstage.recipeversionrating', verbose_name='avaliação')),
            ],
            options={
                'verbose_name': 'nota por critério',
                'verbose_name_plural': 'notas por critério',
                'ordering': ('criterion__position', 'criterion__name'),
                'constraints': [models.UniqueConstraint(fields=('rating', 'criterion'), name='uniq_recipe_rating_score_per_criterion'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 5)), name='recipe_rating_score_between_0_and_5')],
            },
        ),
        migrations.RunPython(seed_initial_criteria, migrations.RunPython.noop),
    ]
