# Generated by Django 6.1.1 on 2026-10-04 10:14

import django.db.models.deletion
from django.db import migrations, models


def counter_seats_are_stools(apps, schema_editor):
    """O lugar de balcão já cadastrado se desenha como banqueta (um assento, sem cadeiras)."""
    SeatingSpot = apps.get_model("backstage", "SeatingSpot")
    SeatingSpot.objects.filter(kind="counter").update(shape="stool")


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0082_cenarios_de_bi_falam_aproveitamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatingspot",
            name="plan_x",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="posição na planta (x)"
            ),
        ),
        migrations.AddField(
            model_name="seatingspot",
            name="plan_y",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="posição na planta (y)"
            ),
        ),
        migrations.AddField(
            model_name="seatingspot",
            name="replaces",
            field=models.OneToOneField(
                blank=True,
                help_text="A mesma mesa antes de mudar lugares ou capacidade. O passado segue contado com ela.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replaced_by",
                to="backstage.seatingspot",
                verbose_name="versão anterior",
            ),
        ),
        migrations.AddField(
            model_name="seatingspot",
            name="rotation",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="giro (graus)"
            ),
        ),
        migrations.AddField(
            model_name="seatingspot",
            name="shape",
            field=models.CharField(
                choices=[
                    ("round", "Redonda"),
                    ("square", "Quadrada"),
                    ("long", "Comprida"),
                    ("stool", "Banqueta"),
                ],
                default="square",
                max_length=8,
                verbose_name="forma",
            ),
        ),
        migrations.AddField(
            model_name="seatingspot",
            name="short_label",
            field=models.CharField(
                blank=True,
                help_text="O que aparece dentro da mesa na planta (M1, B2). Vazio = sai do rótulo.",
                max_length=8,
                verbose_name="sigla na planta",
            ),
        ),
        migrations.RunPython(counter_seats_are_stools, migrations.RunPython.noop),
    ]
