# Generated by Django 6.1.1 on 2026-10-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0083_seating_spot_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="kdsticket",
            name="seen_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="visto em"),
        ),
        migrations.AddField(
            model_name="kdsticket",
            name="seen_by",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="visto por"
            ),
        ),
    ]
