# Generated by Django 6.1.1 on 2026-10-04 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0083_seating_spot_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanCarryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(db_index=True, verbose_name="dia do plano"),
                ),
                ("sku", models.CharField(max_length=100, verbose_name="sku")),
                ("source_day", models.DateField(verbose_name="dia lido no B.I.")),
                (
                    "verdict",
                    models.CharField(
                        choices=[("short", "faltou"), ("over", "sobrou")],
                        max_length=8,
                        verbose_name="veredito",
                    ),
                ),
                (
                    "facts",
                    models.JSONField(blank=True, default=dict, verbose_name="fatos"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="levado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="levado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota do B.I. no plano",
                "verbose_name_plural": "notas do B.I. no plano",
                "ordering": ["target_date", "sku", "-source_day"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_date", "sku", "source_day"),
                        name="backstage_plan_carry_one_per_day",
                    )
                ],
            },
        ),
    ]
