# Generated by Django 6.1.1 on 2026-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backstage", "0083_seating_spot_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatingFixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("showcase", "Vitrine e caixa"),
                            ("entrance", "Entrada"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                ("label", models.CharField(max_length=60, verbose_name="rótulo")),
                (
                    "plan_x",
                    models.PositiveIntegerField(
                        default=0, verbose_name="posição na planta (x)"
                    ),
                ),
                (
                    "plan_y",
                    models.PositiveIntegerField(
                        default=0, verbose_name="posição na planta (y)"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(default=40, verbose_name="largura"),
                ),
                (
                    "height",
                    models.PositiveIntegerField(default=320, verbose_name="altura"),
                ),
            ],
            options={
                "verbose_name": "elemento fixo do salão",
                "verbose_name_plural": "elementos fixos do salão",
                "ordering": ["kind", "pk"],
            },
        ),
    ]
