# Generated by Django 6.1.1 on 2026-10-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0090_saved_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdsticket',
            name='known_ref',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='conhecido na cozinha como'),
        ),
    ]
