# Generated by Django 6.0.5 on 2026-08-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='audience_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Por evento (exigem SKU): {"favorites": true, "alerts": true, "bought_within_days": 90}. Escolhidos pelo gestor: {"customer_refs": [], "groups": [], "rfm_segments": ["champion"], "churn_risk_min": 0.7, "bought_skus": [], "bought_collections": [], "birthday_today": true}. Entrega: {"vip_first_minutes": 15, "preferred_hour_window_hours": 4}.', verbose_name='regras de audiência'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='trigger',
            field=models.CharField(choices=[('production_finished', 'fornada concluída'), ('low_stock', 'estoque baixo'), ('stock_back', 'voltou ao estoque'), ('product_created', 'produto novo'), ('manual', 'disparo manual')], max_length=64, verbose_name='gatilho'),
        ),
    ]
