# Generated by Django 6.0.5 on 2026-08-10 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_campaign_audience_rules_alter_campaign_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='occurrence_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identidade da ocasião agendada (campanha + instante). Vazio = nasceu de evento.', max_length=120, verbose_name='ocasião'),
        ),
        migrations.AlterField(
            model_name='announcementtemplate',
            name='body',
            field=models.TextField(help_text='Use {{product_name}}, {{price}}, {{hashtags}}, {{link}}, {{store_name}}…', verbose_name='corpo'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='trigger',
            field=models.CharField(choices=[('production_finished', 'fornada concluída'), ('low_stock', 'estoque baixo'), ('stock_back', 'voltou ao estoque'), ('product_created', 'produto novo'), ('manual', 'disparo manual'), ('schedule', 'agendado')], max_length=64, verbose_name='gatilho'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.UniqueConstraint(condition=models.Q(('occurrence_key__gt', '')), fields=('occurrence_key',), name='shop_announcement_occurrence_uq'),
        ),
    ]
