# Generated by Django 6.0.5 on 2026-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_announcement_occurrence_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Adiar o que o evento criou: {"type": "immediate"} ou {"type": "preferred_hours", "windows": [["07:00", "11:00"]]}. Disparar sozinho (exige gatilho "agendado"): {"type": "once", "at": "2026-08-15T17:30:00-03:00"} ou {"type": "recurring", "windows": [["17:30", "18:30"]], "weekdays": [4, 5], "starts_on": "2026-08-15", "ends_on": "2026-12-31"}.', verbose_name='agendamento'),
        ),
    ]
