# Generated by Django 6.0.5 on 2026-08-10 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_campaign_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recusado em'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_announcements', to=settings.AUTH_USER_MODEL, verbose_name='recusado por'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='rejected_reason',
            field=models.CharField(blank=True, help_text='O que estava errado. Vazio é permitido: exigir justificativa empurra o gestor a digitar qualquer coisa para se livrar do campo.', max_length=200, verbose_name='motivo da recusa'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'rascunho'), ('pending_review', 'aguardando aprovação'), ('approved', 'aprovado'), ('publishing', 'publicando'), ('published', 'publicado'), ('failed', 'falhou'), ('rejected', 'recusado'), ('expired', 'expirado')], default='draft', max_length=16, verbose_name='situação'),
        ),
    ]
