# Generated by Django 6.0.5 on 2026-08-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_announcement_rejected_at_announcement_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='promotion_ref',
            field=models.SlugField(blank=True, help_text='`ref` da promoção anunciada. Vazio = anúncio sem desconto atrás.', max_length=64, verbose_name='oferta'),
        ),
    ]
