# Generated by Django 6.0.5 on 2026-08-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_campaign_promotion_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='brand_voice',
            field=models.TextField(blank=True, help_text='Instrução de estilo entregue à IA quando ela escreve para a loja: pessoa, tom, o que evitar. Vale para o catálogo e para os anúncios. Vazio = a IA usa a voz padrão do sistema.', verbose_name='voz da marca (IA)'),
        ),
    ]
