# Generated by Django 6.0.5 on 2026-08-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_campaign_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='audience_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Por evento (exigem SKU): {"favorites": true, "alerts": true, "bought_within_days": 90}. Escolhidos pelo gestor: {"customer_refs": [], "groups": [], "rfm_segments": ["champion"], "churn_risk_min": 0.7, "bought_skus": [], "bought_collections": [], "birthday_today": true}. Combinação: {"match": "any"} soma as regras, {"match": "all"} cruza. Entrega: {"vip_first_minutes": 15, "preferred_hour_window_hours": 4}.', verbose_name='regras de audiência'),
        ),
    ]
