# Generated by Django 6.0.5 on 2026-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_campaign_audience_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=32, unique=True, verbose_name='código')),
                ('label', models.CharField(max_length=50, verbose_name='rótulo')),
                ('hint', models.CharField(blank=True, help_text='O sintoma que o padeiro vê — segunda linha do botão.', max_length=100, verbose_name='dica')),
                ('forces_discard', models.BooleanField(default=False, help_text='SÓ segurança alimentar (matéria estranha). Defeito cosmético nunca veta: vende com desconto.', verbose_name='obriga descarte')),
                ('position', models.IntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'defeito de fornada',
                'verbose_name_plural': 'defeitos de fornada',
                'ordering': ('position', 'ref'),
            },
        ),
        migrations.CreateModel(
            name='QualityGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='excellent | standard | fair | minimal — fixo, o rótulo é que edita', max_length=32, unique=True, verbose_name='código')),
                ('label', models.CharField(max_length=50, verbose_name='rótulo')),
                ('rank', models.IntegerField(help_text='Maior = melhor. A ordem tem que ser óbvia num relance.', unique=True, verbose_name='hierarquia')),
                ('markdown_percent', models.PositiveSmallIntegerField(default=0, help_text='Resolvido no fechamento da fornada e congelado no lote.', verbose_name='desconto (%)')),
                ('is_default', models.BooleanField(default=False, help_text='O grau pré-selecionado ao fechar a fornada.', verbose_name='padrão')),
            ],
            options={
                'verbose_name': 'grau de qualidade',
                'verbose_name_plural': 'graus de qualidade',
                'ordering': ('-rank',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='quality_grade_single_default')],
            },
        ),
    ]
