# Generated by Django 6.0.5 on 2026-08-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_quality_refs_to_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='trigger_filter',
            field=models.JSONField(blank=True, default=dict, help_text='Condições extras, ex: {"collections": ["paes"], "quality_min": "standard"}', verbose_name='filtro do gatilho'),
        ),
    ]
