# Generated by Django 6.0.5 on 2026-08-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_campaign_trigger_filter'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='qualitygrade',
            constraint=models.CheckConstraint(condition=models.Q(('markdown_percent__lte', 100)), name='quality_grade_markdown_at_most_100'),
        ),
    ]
