# Generated by Django 6.0.8 on 2026-08-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_qualitygrade_quality_grade_markdown_at_most_100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalruleconfig',
            name='rule_path',
            field=models.CharField(help_text='Dotted path to the rule class (e.g. shopman.shop.rules.pricing.EmployeeRule)', max_length=200, verbose_name='caminho da regra'),
        ),
        migrations.AlterField(
            model_name='ruleconfig',
            name='rule_path',
            field=models.CharField(help_text='Dotted path to the rule class (e.g. shopman.shop.rules.pricing.EmployeeRule)', max_length=200, verbose_name='caminho da regra'),
        ),
    ]
