# Generated by Django 6.0.5 on 2026-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_ruleconfig_help_text_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalomotenashicopy',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='historicalomotenashicopy',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='omotenashicopy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='omotenashicopy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, verbose_name='slogan'),
        ),
    ]
