# Generated by Django 6.0.5 on 2026-08-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_quality_defect_hints_sentence_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='trigger',
            field=models.CharField(choices=[('production_finished', 'Fornada concluída'), ('low_stock', 'Estoque baixo'), ('stock_back', 'Voltou ao estoque'), ('product_created', 'Produto novo'), ('manual', 'Disparo manual'), ('schedule', 'Agendado')], max_length=64, verbose_name='gatilho'),
        ),
    ]
