# Generated by Django 6.0.5 on 2026-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rotulos_em_portugues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='ref',
            field=models.CharField(max_length=64, unique=True, verbose_name='código'),
        ),
    ]
