# Generated by Django 6.0.5 on 2026-08-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_channel_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPurchase',
            fields=[
            ],
            options={
                'verbose_name': 'Compras',
                'verbose_name_plural': 'Compras',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
    ]
