# Generated by Django 6.0.5 on 2026-08-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_shoppurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('campaign', 'campanha'), ('production', 'produção'), ('order', 'pedidos'), ('sign_in', 'acesso'), ('system', 'sistema')], default='system', max_length=32, verbose_name='categoria'),
        ),
    ]
