# Generated by Django 6.0.5 on 2026-08-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_usernotification_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': [('manage_orders', 'Pode confirmar/rejeitar/avançar/cancelar pedidos'), ('cancel_advanced_order', 'Pode cancelar pedido já pronto ou já fechado'), ('manage_production', 'Pode criar WorkOrders e avançar produção'), ('view_production_suggested', 'Pode ver sugestão de produção'), ('edit_production_suggested', 'Pode transformar sugestão em planejamento'), ('view_production_planned', 'Pode ver produção planejada'), ('edit_production_planned', 'Pode editar produção planejada'), ('view_production_started', 'Pode ver produção iniciada'), ('edit_production_started', 'Pode informar entrada em produção'), ('view_production_finished', 'Pode ver produção concluída'), ('edit_production_finished', 'Pode informar produção concluída'), ('view_production_unsold', 'Pode ver não vendidos da produção'), ('edit_production_unsold', 'Pode informar não vendidos da produção'), ('manage_catalog', 'Pode criar/editar Product, Listing e Collection'), ('manage_customers', 'Pode criar/editar Customer, grupos e loyalty'), ('view_reports', 'Pode acessar dashboard e relatórios analíticos')], 'verbose_name': 'loja', 'verbose_name_plural': 'loja'},
        ),
    ]
