# Generated by Django 6.0.5 on 2026-07-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_broadcastpost_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='realtime',
            field=models.JSONField(blank=True, default=dict, help_text='De quanto em quanto tempo as telas do cliente se atualizam sozinhas, em segundos. Vale como reserva: quando o cliente está logado, a tela recebe as mudanças na hora e nem chega a esperar esse intervalo.\nDeixe vazio para usar o padrão.\n\nChaves disponíveis:\n  "tracking_poll_seconds" — acompanhamento do pedido (padrão 30)\n  "payment_poll_seconds" — tela de pagamento (padrão 8)\n  "min_poll_seconds" — intervalo mínimo, protege o servidor (padrão 5)\n', verbose_name='atualização das telas'),
        ),
    ]
