# Generated by Django 6.0.5 on 2026-09-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_cancel_advanced_order_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.CharField(max_length=32, unique=True, verbose_name='assinante ManyChat')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('customer_ref', models.CharField(blank=True, max_length=64, verbose_name='ref do cliente')),
                ('customer_name', models.CharField(blank=True, max_length=120, verbose_name='nome do cliente')),
                ('channel_ref', models.CharField(default='whatsapp', max_length=64, verbose_name='canal de venda')),
                ('state', models.CharField(choices=[('active', 'Ativa'), ('handoff', 'Com a equipe'), ('closed', 'Encerrada')], default='active', max_length=16, verbose_name='estado')),
                ('handoff_reason', models.CharField(blank=True, max_length=200, verbose_name='motivo do handoff')),
                ('handoff_at', models.DateTimeField(blank=True, null=True, verbose_name='handoff em')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='sacola')),
                ('quote', models.JSONField(blank=True, default=dict, verbose_name='orçamento vigente')),
                ('summary', models.TextField(blank=True, verbose_name='resumo')),
                ('summary_until_id', models.BigIntegerField(blank=True, null=True, verbose_name='resumo cobre até')),
                ('turns_day', models.DateField(blank=True, null=True, verbose_name='dia dos turnos')),
                ('turns_today', models.IntegerField(default=0, verbose_name='turnos no dia')),
                ('consecutive_failures', models.IntegerField(default=0, verbose_name='falhas seguidas')),
                ('input_tokens', models.BigIntegerField(default=0, verbose_name='tokens de entrada')),
                ('output_tokens', models.BigIntegerField(default=0, verbose_name='tokens de saída')),
                ('cache_read_tokens', models.BigIntegerField(default=0, verbose_name='tokens lidos do cache')),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True, verbose_name='última mensagem do cliente')),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True, verbose_name='última resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'conversa do concierge',
                'verbose_name_plural': 'conversas do concierge',
                'ordering': ('-last_inbound_at', '-id'),
                'indexes': [models.Index(fields=['state', 'last_inbound_at'], name='shop_conv_state_inbound_idx'), models.Index(fields=['customer_ref'], name='shop_conv_customer_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Cliente'), ('assistant', 'Concierge')], max_length=16, verbose_name='papel')),
                ('kind', models.CharField(choices=[('inbound', 'Mensagem do cliente'), ('reply', 'Resposta'), ('tool_call', 'Chamada de ferramenta'), ('tool_result', 'Resultado de ferramenta'), ('note', 'Nota da casa')], max_length=16, verbose_name='tipo')),
                ('text', models.TextField(blank=True, verbose_name='texto')),
                ('content', models.JSONField(blank=True, default=list, verbose_name='conteúdo')),
                ('external_id', models.CharField(blank=True, max_length=80, verbose_name='id externo')),
                ('delivered', models.BooleanField(blank=True, null=True, verbose_name='entregue')),
                ('usage', models.JSONField(blank=True, default=dict, verbose_name='consumo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criada em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop.conversation', verbose_name='conversa')),
            ],
            options={
                'verbose_name': 'mensagem do concierge',
                'verbose_name_plural': 'mensagens do concierge',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('conversation', 'external_id'), name='shop_convmsg_external_id_unique')],
            },
        ),
    ]
