# Generated by Django 6.0.5 on 2026-09-08 22:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_marketing_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTestReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('artifact_hash', models.CharField(max_length=64)),
                ('target_ref', models.SlugField(max_length=80)),
                ('backend', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('processing', 'processando'), ('accepted_unconfirmed', 'aceito, não confirmado'), ('failed_final', 'recusado'), ('unknown', 'resultado desconhecido'), ('denied', 'negado')], default='processing', max_length=24)),
                ('failure_code', models.CharField(blank=True, max_length=48)),
                ('sandbox', models.BooleanField(default=True)),
                ('max_targets', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_test_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='shop_market_actor_i_05d2f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'idempotency_key_hash'), name='shop_marketing_test_actor_idempotency_uq'), models.CheckConstraint(condition=models.Q(('sandbox', True)), name='shop_marketing_test_must_be_sandbox'), models.CheckConstraint(condition=models.Q(('max_targets', 1)), name='shop_marketing_test_max_one_target')],
            },
        ),
    ]
