# Generated by Django 6.0.5 on 2026-09-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_concierge_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='flags',
            field=models.JSONField(blank=True, default=dict, verbose_name='marcas da conversa'),
        ),
    ]
