# Generated by Django 6.0.5 on 2026-09-08 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_marketing_test_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name='MarketingCommandReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('approve', 'aprovar'), ('reject', 'recusar'), ('reschedule', 'reagendar'), ('publish_now', 'publicar agora'), ('cancel', 'cancelar'), ('fire', 'disparar campanha')], max_length=24)),
                ('state', models.CharField(choices=[('accepted', 'aceito'), ('completed', 'concluído'), ('rejected', 'recusado'), ('conflict', 'conflito'), ('unknown', 'resultado desconhecido')], default='accepted', max_length=16)),
                ('resource_ref', models.CharField(max_length=120)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('base_version', models.PositiveIntegerField()),
                ('resulting_version', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_receipts', to='shop.announcement')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['announcement', 'created_at'], name='shop_market_announc_3ae277_idx'), models.Index(fields=['state', 'created_at'], name='shop_market_state_105fb8_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'idempotency_key_hash'), name='shop_marketing_command_actor_idem_uq')],
            },
        ),
    ]
