# Generated by Django 6.0.5 on 2026-09-08 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_marketing_command_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingContentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('artifact_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_artifacts', to='shop.announcement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('approved', 'aprovado'), ('rejected', 'recusado'), ('rescheduled', 'reagendado'), ('cancelled', 'cancelado'), ('expired', 'expirado')], max_length=24)),
                ('base_version', models.PositiveIntegerField()),
                ('resulting_version', models.PositiveIntegerField()),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_audit_events', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_audit_events', to='shop.announcement')),
                ('command', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audit_event', to='shop.marketingcommandreceipt')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='shop.audiencesnapshot')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='shop.marketingcontentartifact')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MarketingOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(max_length=32)),
                ('wave_key', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('pending', 'pendente'), ('claimed', 'reservado'), ('dispatched', 'despachado'), ('cancelled', 'cancelado'), ('failed', 'falhou')], default='pending', max_length=16)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_owner', models.CharField(blank=True, max_length=100)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_outbox_entries', to='shop.announcement')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_entries', to='shop.marketingcontentartifact')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_entries', to='shop.marketingcommandreceipt')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_entries', to='shop.audiencesnapshot')),
            ],
            options={
                'ordering': ['available_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='marketingcontentartifact',
            constraint=models.UniqueConstraint(fields=('announcement', 'version'), name='shop_marketing_artifact_announcement_version_uq'),
        ),
        migrations.AddIndex(
            model_name='marketingauditevent',
            index=models.Index(fields=['announcement', 'occurred_at'], name='shop_market_announc_94c51f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingoutbox',
            index=models.Index(fields=['state', 'available_at'], name='shop_market_state_ec4f6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketingoutbox',
            constraint=models.UniqueConstraint(fields=('command', 'platform', 'wave_key'), name='shop_marketing_outbox_command_lane_uq'),
        ),
    ]
