# Generated by Django 6.0.5 on 2026-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_conversation_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(help_text='Identificador usado nas regras de sugestão. Ex.: sabor, natureza.', max_length=40, unique=True, verbose_name='ref')),
                ('label', models.CharField(max_length=80, verbose_name='rótulo')),
                ('hint', models.CharField(blank=True, help_text='Para quem preenche o produto escolher sem pensar duas vezes.', max_length=200, verbose_name='dica')),
                ('type', models.CharField(choices=[('choice', 'Escolha única'), ('multi_choice', 'Escolha múltipla'), ('multi_text', 'Lista de termos'), ('number', 'Número'), ('text', 'Texto'), ('boolean', 'Sim / Não')], default='choice', max_length=16, verbose_name='tipo')),
                ('options', models.JSONField(blank=True, default=list, help_text='Lista de {"value", "label", "meta"} — obrigatória para escolha única e múltipla, vazia para os demais tipos.', verbose_name='opções')),
                ('unit', models.CharField(blank=True, help_text='Só para número. Ex.: g, porções.', max_length=16, verbose_name='unidade')),
                ('purposes', models.JSONField(blank=True, default=list, help_text='Subconjunto de: facet, rule, feed, variant, label.', verbose_name='serve para')),
                ('storage', models.CharField(default='attributes', help_text='attributes (padrão) · column:<campo do Product> · metadata:<chave solta do metadata>.', max_length=60, verbose_name='onde o valor mora')),
                ('required', models.BooleanField(default=False, help_text='O Admin acusa os produtos que estão sem valor.', verbose_name='obrigatório')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'atributo de produto',
                'verbose_name_plural': 'atributos de produto',
                'ordering': ['ordering', 'ref'],
            },
        ),
    ]
