# Generated by Django 6.0.5 on 2026-08-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_notification_event_order_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='tracking_copy',
            field=models.JSONField(blank=True, default=dict, help_text='Mensagens exibidas ao cliente na página de acompanhamento do pedido.\nDeixe vazio para usar os textos padrão. Preencha apenas as que quiser personalizar.\n\nChaves disponíveis:\n  "new" — pedido recebido, aguardando o aceite da loja\n  "new_countdown" — texto acima do timer de aceite\n  "accepted" — pedido aceito\n  "preparing" — pedido em preparo\n  "ready" — pedido pronto para retirada/entrega\n  "dispatched" — pedido saiu para entrega\n  "delivered" — pedido entregue\n  "completed" — pedido concluído\n  "cancelled" — pedido cancelado\n  "confirmed_celebration" — texto ao confirmar (timer zerou)\n', verbose_name='textos do acompanhamento'),
        ),
    ]
