# Generated by Django 6.0.5 on 2026-09-09 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_actor_refs(apps, schema_editor):
    Receipt = apps.get_model("shop", "MarketingCommandReceipt")
    Audit = apps.get_model("shop", "MarketingAuditEvent")
    for receipt in Receipt.objects.filter(actor__isnull=False, actor_ref="").iterator():
        receipt.actor_ref = f"user:{receipt.actor_id}"
        receipt.save(update_fields=["actor_ref"])
    for event in Audit.objects.filter(actor__isnull=False, actor_ref="").iterator():
        event.actor_ref = f"user:{event.actor_id}"
        event.save(update_fields=["actor_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_marketing_approval_outbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingauditevent',
            name='actor_ref',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='marketingcommandreceipt',
            name='actor_ref',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.RunPython(backfill_actor_refs, migrations.RunPython.noop),
        migrations.AddField(
            model_name='marketingoutbox',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingoutbox',
            name='cancelled_by_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_outbox_entries', to='shop.marketingcommandreceipt'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'rascunho'), ('pending_review', 'aguardando aprovação'), ('approved', 'aprovado'), ('publishing', 'publicando'), ('published', 'publicado'), ('failed', 'falhou'), ('rejected', 'recusado'), ('expired', 'expirado'), ('cancelled', 'cancelado')], default='draft', max_length=16, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='marketingauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketingcommandreceipt',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_command_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketingcommandreceipt',
            name='kind',
            field=models.CharField(choices=[('approve', 'aprovar'), ('reject', 'recusar'), ('reschedule', 'reagendar'), ('publish_now', 'publicar agora'), ('cancel', 'cancelar'), ('fire', 'disparar campanha'), ('expire', 'expirar')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='marketingcommandreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('actor__isnull', True), ('actor_ref__gt', '')), fields=('actor_ref', 'idempotency_key_hash'), name='shop_marketing_command_system_idem_uq'),
        ),
    ]
