# Generated by Django 6.0.5 on 2026-09-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_marketing_transactional_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingoutbox',
            name='dispatch_ref',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='marketingoutbox',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='marketingoutbox',
            constraint=models.UniqueConstraint(condition=models.Q(('dispatch_ref__gt', '')), fields=('dispatch_ref',), name='shop_marketing_outbox_dispatch_ref_uq'),
        ),
        migrations.AddConstraint(
            model_name='marketingoutbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_owner__gt', ''), ('lease_until__isnull', False), ('state', 'claimed')), models.Q(models.Q(('state', 'claimed'), _negated=True), ('lease_owner', ''), ('lease_until__isnull', True)), _connector='OR'), name='shop_marketing_outbox_lease_state_ck'),
        ),
        migrations.AddConstraint(
            model_name='marketingoutbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dispatch_ref__gt', ''), ('dispatched_at__isnull', False), ('state', 'dispatched')), models.Q(models.Q(('state', 'dispatched'), _negated=True), ('dispatch_ref', ''), ('dispatched_at__isnull', True)), _connector='OR'), name='shop_marketing_outbox_dispatch_state_ck'),
        ),
    ]
