# Generated by Django 6.0.5 on 2026-09-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_seed_attribute_definitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_a', models.CharField(db_index=True, max_length=64, verbose_name='sku')),
                ('sku_b', models.CharField(max_length=64, verbose_name='sku par')),
                ('together_count', models.PositiveIntegerField(help_text='Cestas cruas que trazem os dois. É o piso de suporte, não o peso.', verbose_name='cestas em comum')),
                ('score', models.FloatField(help_text='Cestas em comum, com a cesta de ontem pesando mais que a do ano passado.', verbose_name='co-ocorrência com peso')),
                ('lift', models.FloatField(help_text='Quantas vezes o par acontece mais do que aconteceria por acaso. Acima de 1 é afinidade; perto de 1 é coincidência.', verbose_name='lift')),
                ('window_days', models.PositiveIntegerField(verbose_name='janela (dias)')),
                ('computed_at', models.DateTimeField(db_index=True, verbose_name='calculado em')),
            ],
            options={
                'verbose_name': 'afinidade entre produtos',
                'verbose_name_plural': 'afinidades entre produtos',
                'ordering': ['sku_a', '-lift'],
                'indexes': [models.Index(fields=['sku_a', '-lift'], name='shop_affinity_a_lift_idx')],
                'constraints': [models.UniqueConstraint(fields=('sku_a', 'sku_b'), name='shop_affinity_pair')],
            },
        ),
    ]
