# Generated by Django 6.0.5 on 2026-09-09 00:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_marketing_outbox_recovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(max_length=32)),
                ('wave_key', models.CharField(blank=True, max_length=64)),
                ('target_fingerprint', models.CharField(max_length=64)),
                ('fingerprint_key_version', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('planned', 'planejado'), ('suppressed', 'suprimido'), ('queued', 'enfileirado'), ('sending', 'enviando'), ('accepted', 'aceito, não confirmado'), ('confirmed', 'confirmado'), ('failed_retryable', 'falha repetível'), ('failed_final', 'falha final'), ('unknown', 'resultado desconhecido'), ('cancelled', 'cancelado'), ('expired', 'expirado')], default='planned', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('lease_owner', models.CharField(blank=True, max_length=100)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('provider_receipt_ref', models.CharField(blank=True, max_length=128)),
                ('provider_ref_retention_until', models.DateTimeField(blank=True, null=True)),
                ('identity_retention_until', models.DateTimeField()),
                ('record_retention_until', models.DateTimeField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_targets', to='shop.announcement')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_targets', to='shop.marketingcontentartifact')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_targets', to='shop.audiencesnapshotmember')),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_targets', to='shop.marketingoutbox')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_targets', to='shop.audiencesnapshot')),
            ],
            options={
                'ordering': ['next_attempt_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('started', 'iniciada'), ('completed', 'concluída')], default='started', max_length=16)),
                ('outcome_kind', models.CharField(blank=True, choices=[('not_attempted', 'não tentado'), ('accepted_unconfirmed', 'aceito, não confirmado'), ('confirmed', 'confirmado'), ('failed_retryable', 'falha repetível'), ('failed_final', 'falha final'), ('unknown', 'resultado desconhecido')], max_length=32)),
                ('idempotency_token_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('provider_receipt_ref', models.CharField(blank=True, max_length=128)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('retry_after_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='shop.deliverytarget')),
            ],
            options={
                'ordering': ['target', 'ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverytarget',
            index=models.Index(fields=['state', 'next_attempt_at'], name='shop_delive_state_7b523b_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytarget',
            index=models.Index(fields=['outbox', 'state'], name='shop_delive_outbox__9cb873_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverytarget',
            constraint=models.UniqueConstraint(fields=('snapshot', 'platform', 'target_fingerprint'), name='shop_delivery_target_snapshot_platform_fp_uq'),
        ),
        migrations.AddConstraint(
            model_name='deliverytarget',
            constraint=models.CheckConstraint(condition=models.Q(('fingerprint_key_version__gt', 0)), name='shop_delivery_target_key_version_ck'),
        ),
        migrations.AddConstraint(
            model_name='deliverytarget',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='shop_delivery_target_version_ck'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['state', 'started_at'], name='shop_delive_state_ec17e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('target', 'ordinal'), name='shop_delivery_attempt_target_ordinal_uq'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('target', 'idempotency_token_hash'), name='shop_delivery_attempt_target_idem_uq'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gt', 0)), name='shop_delivery_attempt_ordinal_ck'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('outcome_kind', ''), ('state', 'started')), models.Q(('completed_at__isnull', False), ('outcome_kind__gt', ''), ('state', 'completed')), _connector='OR'), name='shop_delivery_attempt_completion_ck'),
        ),
    ]
