# Generated by Django 6.0.5 on 2026-09-09 01:03

from django.db import migrations, models


def split_started_attempts(apps, schema_editor):
    DeliveryAttempt = apps.get_model("shop", "DeliveryAttempt")
    DeliveryAttempt.objects.filter(state="started").update(state="calling")


def restore_started_attempts(apps, schema_editor):
    DeliveryAttempt = apps.get_model("shop", "DeliveryAttempt")
    DeliveryAttempt.objects.filter(state__in=("prepared", "calling")).update(
        state="started"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_marketing_delivery_ledger'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliveryattempt',
            name='shop_delivery_attempt_completion_ck',
        ),
        migrations.RunPython(split_started_attempts, restore_started_attempts),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='state',
            field=models.CharField(choices=[('prepared', 'preparada'), ('calling', 'chamada iniciada'), ('completed', 'concluída')], default='prepared', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('outcome_kind', ''), ('state__in', ('prepared', 'calling'))), models.Q(('completed_at__isnull', False), ('outcome_kind__gt', ''), ('state', 'completed')), _connector='OR'), name='shop_delivery_attempt_completion_ck'),
        ),
    ]
