# Generated by Django 6.0.5 on 2026-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_campaign_rename_indexes_and_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='notify_users',
            field=models.JSONField(blank=True, default=list, help_text='IDs de usuário a notificar. Vazio = todos com a permissão de gerenciar campanhas.', verbose_name='avisar usuários'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='action_data',
            field=models.JSONField(blank=True, default=dict, help_text='Payload da ação, ex: {"announcement_id": 12}', verbose_name='dados da ação'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('campaign', 'campanha'), ('production', 'produção'), ('order', 'pedidos'), ('system', 'sistema')], default='system', max_length=32, verbose_name='categoria'),
        ),
    ]
