# Generated by Django 6.0.5 on 2026-09-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_marketing_attempt_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingoutbox',
            name='fanout_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingoutbox',
            name='fanout_expected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingoutbox',
            name='fanout_materialized',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingoutbox',
            name='fanout_selection_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='deliverytarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_owner', ''), ('lease_until__isnull', True)), models.Q(('lease_owner__gt', ''), ('lease_until__isnull', False), ('state', 'queued')), _connector='OR'), name='shop_delivery_target_lease_state_ck'),
        ),
        migrations.AddConstraint(
            model_name='marketingoutbox',
            constraint=models.CheckConstraint(condition=models.Q(('fanout_materialized__lte', models.F('fanout_expected'))), name='shop_marketing_outbox_fanout_count_ck'),
        ),
        migrations.AddConstraint(
            model_name='marketingoutbox',
            constraint=models.CheckConstraint(condition=models.Q(('fanout_completed_at__isnull', True), models.Q(('fanout_completed_at__isnull', False), ('fanout_materialized', models.F('fanout_expected')), ('fanout_selection_hash__gt', '')), _connector='OR'), name='shop_marketing_outbox_fanout_complete_ck'),
        ),
    ]
