# Generated by Django 6.0.5 on 2026-08-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_campaign_rename_field_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='commerce_policy',
            field=models.CharField(choices=[('display', 'somente exibição'), ('order', 'venda completa')], db_index=True, default='order', help_text="'Venda completa': recebe pedido. 'Somente exibição': mostra catálogo com preço e nunca transaciona (menuboard, catálogo do Google/Meta) — o preço vem do canal apontado em configuração.", max_length=16, verbose_name='política comercial'),
        ),
    ]
