# Generated by Django 6.0.5 on 2026-09-09 01:45

from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Coalesce


def mark_untracked_legacy_results(apps, schema_editor):
    Announcement = apps.get_model("shop", "Announcement")
    Announcement.objects.filter(status__in=("published", "failed")).update(
        delivery_state="legacy_untracked",
        delivery_state_updated_at=Coalesce("published_at", "created_at"),
        delivery_settled_at=Coalesce("published_at", "created_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_marketing_delivery_leases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='delivery_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='delivery_state',
            field=models.CharField(choices=[('not_started', 'não iniciada'), ('fanout_pending', 'preparando entregas'), ('delivering', 'em andamento'), ('succeeded', 'concluída'), ('completed_with_failures', 'concluída com falhas'), ('unknown', 'resultado desconhecido'), ('cancelled', 'cancelada'), ('expired', 'expirada'), ('legacy_untracked', 'legado sem ledger')], default='not_started', max_length=32),
        ),
        migrations.AddField(
            model_name='announcement',
            name='delivery_state_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'rascunho'), ('pending_review', 'aguardando aprovação'), ('approved', 'aprovado'), ('publishing', 'publicando'), ('settled', 'execução encerrada'), ('published', 'publicado'), ('failed', 'falhou'), ('rejected', 'recusado'), ('expired', 'expirado'), ('cancelled', 'cancelado')], default='draft', max_length=16, verbose_name='situação'),
        ),
        migrations.RunPython(mark_untracked_legacy_results, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_settled_at__isnull', True), ('delivery_state__in', ('not_started', 'fanout_pending', 'delivering'))), models.Q(('delivery_settled_at__isnull', False), ('delivery_state__in', ('succeeded', 'completed_with_failures', 'unknown', 'cancelled', 'expired', 'legacy_untracked'))), _connector='OR'), name='shop_announcement_delivery_settlement_ck'),
        ),
        migrations.AddConstraint(
            model_name='deliverytarget',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('planned', 'suppressed', 'queued', 'sending', 'accepted', 'confirmed', 'failed_retryable', 'failed_final', 'unknown', 'cancelled', 'expired'))), name='shop_delivery_target_state_ck'),
        ),
        migrations.AddConstraint(
            model_name='marketingoutbox',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('pending', 'claimed', 'dispatched', 'cancelled', 'failed'))), name='shop_marketing_outbox_state_ck'),
        ),
    ]
