# Generated by Django 6.0.5 on 2026-09-09 02:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_marketing_delivery_aggregate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingauditevent',
            name='event_type',
            field=models.CharField(choices=[('approved', 'aprovado'), ('rejected', 'recusado'), ('rescheduled', 'reagendado'), ('cancelled', 'cancelado'), ('expired', 'expirado'), ('delivery_retried', 'entrega repetida'), ('reconcile_requested', 'reconciliação solicitada')], max_length=24),
        ),
        migrations.AlterField(
            model_name='marketingcommandreceipt',
            name='kind',
            field=models.CharField(choices=[('approve', 'aprovar'), ('reject', 'recusar'), ('reschedule', 'reagendar'), ('publish_now', 'publicar agora'), ('cancel', 'cancelar'), ('fire', 'disparar campanha'), ('expire', 'expirar'), ('retry_delivery', 'repetir falhas de entrega'), ('reconcile_delivery', 'reconciliar entrega desconhecida')], max_length=24),
        ),
        migrations.CreateModel(
            name='DeliveryReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('pending', 'pendente'), ('claimed', 'reservada'), ('completed', 'concluída')], default='pending', max_length=16)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('lookup_attempts', models.PositiveIntegerField(default=0)),
                ('lease_owner', models.CharField(blank=True, max_length=100)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('outcome_kind', models.CharField(blank=True, choices=[('not_attempted', 'não tentado'), ('accepted_unconfirmed', 'aceito, não confirmado'), ('confirmed', 'confirmado'), ('failed_retryable', 'falha repetível'), ('failed_final', 'falha final'), ('unknown', 'resultado desconhecido')], max_length=32)),
                ('provider_receipt_ref', models.CharField(blank=True, max_length=128)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='shop.deliveryattempt')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_reconciliations', to='shop.marketingcommandreceipt')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='shop.deliverytarget')),
            ],
            options={
                'ordering': ['available_at', 'pk'],
                'indexes': [models.Index(fields=['state', 'available_at'], name='shop_delive_state_dd944c_idx')],
                'constraints': [models.UniqueConstraint(fields=('command', 'target'), name='shop_delivery_reconcile_command_target_uq'), models.UniqueConstraint(condition=models.Q(('state__in', ('pending', 'claimed'))), fields=('target',), name='shop_delivery_reconcile_active_target_uq'), models.CheckConstraint(condition=models.Q(models.Q(('lease_owner__gt', ''), ('lease_until__isnull', False), ('state', 'claimed')), models.Q(models.Q(('state', 'claimed'), _negated=True), ('lease_owner', ''), ('lease_until__isnull', True)), _connector='OR'), name='shop_delivery_reconcile_lease_state_ck'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('outcome_kind', ''), ('state__in', ('pending', 'claimed'))), models.Q(('completed_at__isnull', False), ('outcome_kind__gt', ''), ('state', 'completed')), _connector='OR'), name='shop_delivery_reconcile_completion_ck')],
            },
        ),
    ]
