# Generated by Django 6.0.5 on 2026-09-09 03:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_marketing_delivery_recovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingauditevent',
            name='decision_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='MarketingConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('action', models.CharField(max_length=32)),
                ('capability', models.CharField(max_length=64)),
                ('resource_ref', models.CharField(max_length=120)),
                ('base_version', models.PositiveIntegerField()),
                ('context_hash', models.CharField(max_length=64)),
                ('artifact_hash', models.CharField(blank=True, max_length=64)),
                ('audience_hash', models.CharField(blank=True, max_length=64)),
                ('audience_count', models.PositiveIntegerField(default=0)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('consequence', models.CharField(max_length=64)),
                ('confirmation_mode', models.CharField(choices=[('summary', 'resumo'), ('typed', 'digitada')], max_length=16)),
                ('step_up_level', models.CharField(choices=[('none', 'nenhum'), ('password', 'senha'), ('totp', 'TOTP')], max_length=16)),
                ('dual_control', models.BooleanField(default=False)),
                ('permission_fingerprint', models.CharField(max_length=64)),
                ('second_permission_fingerprint', models.CharField(blank=True, max_length=64)),
                ('freeze_generation', models.PositiveIntegerField()),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_confirmations', to=settings.AUTH_USER_MODEL)),
                ('command', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='shop.marketingcommandreceipt')),
                ('second_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_second_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingQuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('resource_ref', models.CharField(max_length=120)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('retention_until', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_quota_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingSafetyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='default', max_length=32, unique=True)),
                ('frozen', models.BooleanField(default=False)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_freezes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=32)),
                ('action', models.CharField(blank=True, max_length=32)),
                ('resource_ref', models.CharField(blank=True, max_length=120)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('retention_until', models.DateTimeField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_security_events', to=settings.AUTH_USER_MODEL)),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_events', to='shop.marketingconfirmation')),
                ('second_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketing_second_security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketingconfirmation',
            index=models.Index(fields=['actor', 'created_at'], name='shop_market_actor_i_6566b9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingconfirmation',
            index=models.Index(fields=['resource_ref', 'created_at'], name='shop_market_resourc_8ff6a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketingconfirmation',
            constraint=models.CheckConstraint(condition=models.Q(('base_version__gte', 1)), name='shop_marketing_confirmation_version_ck'),
        ),
        migrations.AddConstraint(
            model_name='marketingconfirmation',
            constraint=models.CheckConstraint(condition=models.Q(('freeze_generation__gte', 1)), name='shop_marketing_confirmation_generation_ck'),
        ),
        migrations.AddConstraint(
            model_name='marketingconfirmation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dual_control', False), ('second_actor__isnull', True), ('second_approved_at__isnull', True), ('second_permission_fingerprint', '')), models.Q(('dual_control', True), ('second_actor__isnull', False), ('second_approved_at__isnull', False), ('second_permission_fingerprint__gt', '')), models.Q(('dual_control', True), ('second_actor__isnull', True), ('second_approved_at__isnull', True), ('second_permission_fingerprint', '')), _connector='OR'), name='shop_marketing_confirmation_dual_ck'),
        ),
        migrations.AddIndex(
            model_name='marketingquotausage',
            index=models.Index(fields=['actor', 'action', 'occurred_at'], name='shop_market_actor_i_5ec942_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingquotausage',
            index=models.Index(fields=['action', 'occurred_at'], name='shop_market_action_ccffcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketingsafetystate',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 1)), name='shop_marketing_safety_generation_ck'),
        ),
        migrations.AddConstraint(
            model_name='marketingsafetystate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='shop_marketing_safety_version_ck'),
        ),
        migrations.AddConstraint(
            model_name='marketingsafetystate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frozen', True), ('frozen_at__isnull', False), ('frozen_by__isnull', False), ('reason__gt', '')), models.Q(('frozen', False), ('frozen_at__isnull', True), ('frozen_by__isnull', True), ('reason', '')), _connector='OR'), name='shop_marketing_safety_frozen_evidence_ck'),
        ),
        migrations.AddIndex(
            model_name='marketingsecurityevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='shop_market_event_t_7fe021_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingsecurityevent',
            index=models.Index(fields=['resource_ref', 'occurred_at'], name='shop_market_resourc_6739aa_idx'),
        ),
    ]
