# Generated by Django 6.0.5 on 2026-09-09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0035_marketing_security_authorization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtemplate",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                help_text="Versão usada para impedir sobrescrita concorrente da configuração.",
                verbose_name="versão operacional",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="kind",
            field=models.CharField(
                choices=[
                    ("approve", "aprovar"),
                    ("reject", "recusar"),
                    ("reschedule", "reagendar"),
                    ("publish_now", "publicar agora"),
                    ("cancel", "cancelar"),
                    ("fire", "disparar campanha"),
                    ("expire", "expirar"),
                    ("retry_delivery", "repetir falhas de entrega"),
                    ("reconcile_delivery", "reconciliar entrega desconhecida"),
                    ("configure_platform", "configurar plataforma"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="MarketingPlatformAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("flow_configured", "flow configurado"),
                            ("flow_cleared", "flow removido"),
                        ],
                        max_length=24,
                    ),
                ),
                ("platform", models.CharField(max_length=32)),
                ("actor_ref", models.CharField(db_index=True, max_length=128)),
                ("base_version", models.PositiveIntegerField()),
                ("resulting_version", models.PositiveIntegerField()),
                ("previous_flow_ref", models.CharField(blank=True, max_length=120)),
                ("resulting_flow_ref", models.CharField(blank=True, max_length=120)),
                ("catalog_hash", models.CharField(max_length=64)),
                ("catalog_as_of", models.DateTimeField()),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retention_until", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketing_platform_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_audit_event",
                        to="shop.marketingcommandreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="marketingplatformauditevent",
            index=models.Index(
                fields=["platform", "occurred_at"],
                name="shop_market_platfor_fb7e6f_idx",
            ),
        ),
    ]
