# Generated by Django 6.0.5 on 2026-09-09

from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import shopman.shop.models.user_notification


def backfill_notification_lifecycle(apps, schema_editor):
    UserNotification = apps.get_model("shop", "UserNotification")
    UserNotificationEvent = apps.get_model("shop", "UserNotificationEvent")
    Announcement = apps.get_model("shop", "Announcement")
    now = django.utils.timezone.now()
    retention_until = now + timedelta(days=365 * 5)
    claimed_dedupe_keys = set()

    for notification in UserNotification.objects.order_by("-created_at", "-pk").iterator():
        lifecycle = "seen" if notification.is_read else "unseen"
        severity = "action_required" if notification.is_actionable else "information"
        source_condition = ""
        source_ref = ""
        source_version = 1
        group_key = ""
        dedupe_key = ""
        owner_role = ""
        escalation_role = ""
        expires_at = None
        resolved_at = None
        outcome = "legacy_backfill_unmapped"

        raw_id = (
            (notification.action_data or {}).get("announcement_id")
            if notification.category == "campaign" and isinstance(notification.action_data, dict)
            else None
        )
        try:
            announcement_id = int(raw_id)
        except (TypeError, ValueError):
            announcement_id = 0
        announcement = Announcement.objects.filter(pk=announcement_id).first() if announcement_id > 0 else None

        if announcement is not None:
            source_condition = "announcement_review"
            source_ref = f"announcement:{announcement.pk}"
            source_version = max(1, int(announcement.version or 1))
            group_key = f"{source_condition}:{source_ref}:v{source_version}"
            canonical_dedupe = f"{group_key}:owner:{notification.user_id}"
            owner_role = "product"
            escalation_role = "ops"
            expires_at = announcement.expires_at
            outcome = "legacy_backfill_mapped"

            expired = bool(expires_at and expires_at <= now)
            if announcement.status != "pending_review" or expired:
                lifecycle = "expired" if announcement.status == "expired" or expired else "resolved"
                resolved_at = now
                notification.is_read = True
                notification.is_actionable = False
                outcome = f"source_{announcement.status}"
            elif canonical_dedupe in claimed_dedupe_keys:
                lifecycle = "expired"
                resolved_at = now
                notification.is_read = True
                notification.is_actionable = False
                dedupe_key = f"legacy-duplicate:notification:{notification.pk}"
                outcome = "legacy_duplicate_expired"
            else:
                dedupe_key = canonical_dedupe
                claimed_dedupe_keys.add(canonical_dedupe)
        else:
            lifecycle = "expired"
            resolved_at = now
            notification.is_read = True
            notification.is_actionable = False
            source_condition = "legacy_unmapped"
            source_ref = f"notification:{notification.pk}"
            group_key = f"legacy_unmapped:notification:{notification.pk}:v1"
            dedupe_key = f"{group_key}:owner:{notification.user_id}"

        notification.lifecycle = lifecycle
        notification.severity = severity
        notification.source_condition = source_condition
        notification.source_ref = source_ref
        notification.source_version = source_version
        notification.group_key = group_key
        notification.dedupe_key = dedupe_key
        notification.owner_role = owner_role
        notification.escalation_role = escalation_role
        notification.expires_at = expires_at
        notification.resolved_at = resolved_at
        notification.lifecycle_updated_at = notification.read_at or notification.created_at or now
        notification.retention_until = retention_until
        notification.save(update_fields=[
            "is_read",
            "is_actionable",
            "lifecycle",
            "severity",
            "source_condition",
            "source_ref",
            "source_version",
            "group_key",
            "dedupe_key",
            "owner_role",
            "escalation_role",
            "expires_at",
            "resolved_at",
            "lifecycle_updated_at",
            "retention_until",
        ])
        UserNotificationEvent.objects.create(
            notification_id=notification.pk,
            event_type="expired" if lifecycle == "expired" else "resolved" if lifecycle == "resolved" else "created",
            from_state=lifecycle,
            to_state=lifecycle,
            actor_ref="migration",
            outcome_code=outcome,
            source_condition=source_condition,
            source_ref=source_ref,
            source_version=source_version,
            occurred_at=now,
            retention_until=retention_until,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0036_marketing_platform_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("created", "criado"), ("deduped", "duplicado evitado"), ("seen", "visto"), ("acknowledged", "assumido"), ("refreshed", "origem atualizada"), ("action_chosen", "ação escolhida"), ("action_succeeded", "ação concluída"), ("action_failed", "ação falhou"), ("resolved", "resolvido"), ("expired", "expirado")], max_length=24)),
                ("from_state", models.CharField(choices=[("unseen", "não visto"), ("seen", "visto"), ("acknowledged", "assumido"), ("resolved", "resolvido"), ("expired", "expirado")], max_length=16)),
                ("to_state", models.CharField(choices=[("unseen", "não visto"), ("seen", "visto"), ("acknowledged", "assumido"), ("resolved", "resolvido"), ("expired", "expirado")], max_length=16)),
                ("actor_ref", models.CharField(blank=True, db_index=True, max_length=64)),
                ("action_code", models.CharField(blank=True, max_length=40)),
                ("outcome_code", models.CharField(blank=True, max_length=64)),
                ("source_condition", models.CharField(blank=True, max_length=64)),
                ("source_ref", models.CharField(blank=True, max_length=120)),
                ("source_version", models.PositiveIntegerField(default=1)),
                ("facts", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("retention_until", models.DateTimeField(default=shopman.shop.models.user_notification.notification_retention_until)),
            ],
            options={"ordering": ["-occurred_at", "-pk"]},
        ),
        migrations.AlterModelOptions(
            name="usernotification",
            options={"ordering": ["-created_at", "-pk"], "verbose_name": "notificação", "verbose_name_plural": "notificações"},
        ),
        migrations.AddField(model_name="usernotification", name="acknowledged_at", field=models.DateTimeField(blank=True, null=True, verbose_name="assumida em")),
        migrations.AddField(model_name="usernotification", name="dedupe_key", field=models.CharField(blank=True, max_length=320, verbose_name="chave de deduplicação")),
        migrations.AddField(model_name="usernotification", name="escalates_at", field=models.DateTimeField(blank=True, null=True, verbose_name="escala em")),
        migrations.AddField(model_name="usernotification", name="escalation_role", field=models.CharField(blank=True, max_length=32, verbose_name="função de escalação")),
        migrations.AddField(model_name="usernotification", name="expires_at", field=models.DateTimeField(blank=True, null=True, verbose_name="expira em")),
        migrations.AddField(model_name="usernotification", name="group_key", field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name="grupo de reconciliação")),
        migrations.AddField(model_name="usernotification", name="lifecycle", field=models.CharField(choices=[("unseen", "não visto"), ("seen", "visto"), ("acknowledged", "assumido"), ("resolved", "resolvido"), ("expired", "expirado")], default="unseen", max_length=16, verbose_name="ciclo de vida")),
        migrations.AddField(model_name="usernotification", name="lifecycle_updated_at", field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="estado atualizado em")),
        migrations.AddField(model_name="usernotification", name="owner_role", field=models.CharField(blank=True, max_length=32, verbose_name="função responsável")),
        migrations.AddField(model_name="usernotification", name="resolved_at", field=models.DateTimeField(blank=True, null=True, verbose_name="resolvida em")),
        migrations.AddField(model_name="usernotification", name="retention_until", field=models.DateTimeField(default=shopman.shop.models.user_notification.notification_retention_until)),
        migrations.AddField(model_name="usernotification", name="severity", field=models.CharField(choices=[("information", "informação"), ("action_required", "ação necessária"), ("warning", "atenção"), ("critical", "crítico")], default="information", max_length=24, verbose_name="severidade")),
        migrations.AddField(model_name="usernotification", name="source_condition", field=models.CharField(blank=True, max_length=64, verbose_name="condição de origem")),
        migrations.AddField(model_name="usernotification", name="source_ref", field=models.CharField(blank=True, max_length=120, verbose_name="referência de origem")),
        migrations.AddField(model_name="usernotification", name="source_version", field=models.PositiveIntegerField(default=1, verbose_name="versão da origem")),
        migrations.AddField(model_name="usernotification", name="version", field=models.PositiveIntegerField(default=1, editable=False, verbose_name="versão")),
        migrations.AlterField(model_name="usernotification", name="action_data", field=models.JSONField(blank=True, default=dict, help_text="Compatibilidade; somente campos allowlisted são projetados.", verbose_name="dados da ação")),
        migrations.AlterField(model_name="usernotification", name="action_url", field=models.CharField(blank=True, help_text="Compatibilidade; Actions canônicas nunca executam este valor.", max_length=500, verbose_name="link")),
        migrations.AlterField(model_name="usernotification", name="is_actionable", field=models.BooleanField(default=False, help_text="Compatibilidade; a Action real é resolvida no servidor.", verbose_name="acionável")),
        migrations.AddField(model_name="usernotificationevent", name="actor", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notification_lifecycle_events", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="usernotificationevent", name="command", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="notification_lifecycle_events", to="shop.marketingcommandreceipt")),
        migrations.AddField(model_name="usernotificationevent", name="notification", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_events", to="shop.usernotification")),
        migrations.RunPython(backfill_notification_lifecycle, migrations.RunPython.noop),
        migrations.AddIndex(model_name="usernotification", index=models.Index(fields=["user", "lifecycle", "severity", "-created_at"], name="shop_userno_user_id_59d878_idx")),
        migrations.AddIndex(model_name="usernotification", index=models.Index(fields=["source_condition", "source_ref", "source_version"], name="shop_userno_source__87c024_idx")),
        migrations.AddConstraint(model_name="usernotification", constraint=models.UniqueConstraint(condition=models.Q(("dedupe_key", ""), _negated=True), fields=("dedupe_key",), name="shop_user_notification_dedupe_key_uq")),
        migrations.AddIndex(model_name="usernotificationevent", index=models.Index(fields=["notification", "occurred_at"], name="shop_userno_notific_0030ef_idx")),
        migrations.AddIndex(model_name="usernotificationevent", index=models.Index(fields=["event_type", "occurred_at"], name="shop_userno_event_t_58c7bb_idx")),
        migrations.AddIndex(model_name="usernotificationevent", index=models.Index(fields=["source_condition", "source_ref", "occurred_at"], name="shop_userno_source__459dc5_idx")),
    ]
