# Generated by Django 6.0.5 on 2026-09-09 15:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0037_user_notification_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementtemplate",
            name="use_ai_generation",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Quando ligado, oferece uma sugestão separada durante a revisão. "
                    "Nunca altera nem publica o anúncio automaticamente."
                ),
                verbose_name="oferecer sugestão de IA",
            ),
        ),
        migrations.CreateModel(
            name="MarketingAISuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("actor_ref", models.CharField(blank=True, db_index=True, max_length=128)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("generated", "gerada"),
                            ("rejected", "bloqueada pela política"),
                            ("provider_failed", "provedor indisponível"),
                        ],
                        max_length=24,
                    ),
                ),
                ("outcome_code", models.CharField(max_length=64)),
                ("base_version", models.PositiveIntegerField()),
                ("provider_ref", models.CharField(max_length=32)),
                ("model_ref", models.CharField(max_length=100)),
                ("policy_version", models.CharField(max_length=32)),
                ("facts_hash", models.CharField(max_length=64)),
                ("prompt_hash", models.CharField(max_length=64)),
                ("suggestion_hash", models.CharField(blank=True, max_length=64)),
                ("body_hash", models.CharField(blank=True, max_length=64)),
                ("hashtags_hash", models.CharField(blank=True, max_length=64)),
                ("used_fact_ids", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("latency_bucket", models.CharField(blank=True, max_length=24)),
                ("cost_bucket", models.CharField(blank=True, max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retention_until", models.DateTimeField()),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_suggestions",
                        to="shop.announcement",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketing_ai_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-pk"]},
        ),
        migrations.CreateModel(
            name="MarketingAISuggestionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("draft_accepted", "usada no rascunho"),
                            ("discarded", "descartada"),
                            ("approved_unedited", "aprovada sem edição"),
                            ("approved_edited", "aprovada após edição"),
                        ],
                        max_length=24,
                    ),
                ),
                ("actor_ref", models.CharField(blank=True, db_index=True, max_length=128)),
                ("result_hash", models.CharField(blank=True, max_length=64)),
                ("diff_fields", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField()),
                ("retention_until", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketing_ai_suggestion_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_suggestion_events",
                        to="shop.marketingcommandreceipt",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="human_events",
                        to="shop.marketingaisuggestion",
                    ),
                ),
            ],
            options={"ordering": ["-occurred_at", "-pk"]},
        ),
        migrations.AddIndex(
            model_name="marketingaisuggestion",
            index=models.Index(fields=["announcement", "created_at"], name="shop_market_announc_ad502c_idx"),
        ),
        migrations.AddIndex(
            model_name="marketingaisuggestion",
            index=models.Index(fields=["state", "created_at"], name="shop_market_state_6c690b_idx"),
        ),
        migrations.AddIndex(
            model_name="marketingaisuggestionevent",
            index=models.Index(fields=["suggestion", "occurred_at"], name="shop_market_suggest_2fc5bf_idx"),
        ),
    ]
