# Generated by Django 6.0.5 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("shop", "0038_alter_announcementtemplate_use_ai_generation_and_more")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("campaign_fired", "disparo de campanha criado"),
                    ("approved", "aprovado"),
                    ("rejected", "recusado"),
                    ("rescheduled", "reagendado"),
                    ("cancelled", "cancelado"),
                    ("expired", "expirado"),
                    ("delivery_retried", "entrega repetida"),
                    ("reconcile_requested", "reconciliação solicitada"),
                ],
                max_length=24,
            ),
        ),
    ]
