# Generated by Django 6.0.5 on 2026-09-10 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_announcement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiencesnapshot',
            options={'ordering': ['-sealed_at'], 'verbose_name': 'público selado', 'verbose_name_plural': 'públicos selados'},
        ),
        migrations.AlterModelOptions(
            name='marketingauditevent',
            options={'ordering': ['-occurred_at', '-pk'], 'verbose_name': 'evento de decisão de Marketing', 'verbose_name_plural': 'eventos de decisão de Marketing'},
        ),
        migrations.AlterModelOptions(
            name='marketingcommandreceipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'comprovante de comando de Marketing', 'verbose_name_plural': 'comprovantes de comando de Marketing'},
        ),
        migrations.AlterModelOptions(
            name='marketingplatformauditevent',
            options={'ordering': ['-occurred_at', '-pk'], 'verbose_name': 'evento de configuração de plataforma', 'verbose_name_plural': 'eventos de configuração de plataforma'},
        ),
        migrations.AlterModelOptions(
            name='marketingsecurityevent',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'evento de segurança de Marketing', 'verbose_name_plural': 'eventos de segurança de Marketing'},
        ),
        migrations.AlterModelOptions(
            name='marketingtestreceipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'comprovante de teste de Marketing', 'verbose_name_plural': 'comprovantes de teste de Marketing'},
        ),
    ]
