# Generated by Django 6.0.5 on 2026-09-11 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0046_rotulos_auditoria_marketing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="delivery_settled_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="entrega concluída em",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="delivery_state",
            field=models.CharField(
                choices=[
                    ("not_started", "não iniciada"),
                    ("fanout_pending", "preparando entregas"),
                    ("delivering", "em andamento"),
                    ("succeeded", "concluída"),
                    ("completed_with_failures", "concluída com falhas"),
                    ("unknown", "resultado desconhecido"),
                    ("cancelled", "cancelada"),
                    ("expired", "expirada"),
                    ("legacy_untracked", "legado sem ledger"),
                ],
                default="not_started",
                max_length=32,
                verbose_name="situação da entrega",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="delivery_state_updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="situação da entrega atualizada em",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                verbose_name="versão",
            ),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audience_snapshots",
                to="shop.announcement",
                verbose_name="anúncio",
            ),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="calculated_at",
            field=models.DateTimeField(verbose_name="calculado em"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="cohort_hash",
            field=models.CharField(max_length=64, verbose_name="hash do público"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expira em"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="policy_version",
            field=models.CharField(max_length=64, verbose_name="versão da política"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="retention_until",
            field=models.DateTimeField(verbose_name="reter até"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="rule_hash",
            field=models.CharField(max_length=64, verbose_name="hash da regra"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="rule_summary",
            field=models.JSONField(default=dict, verbose_name="resumo da regra"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="sealed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="selado em"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="summary",
            field=models.JSONField(default=dict, verbose_name="resumo"),
        ),
        migrations.AlterField(
            model_name="audiencesnapshot",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="versão"),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marketing_audit_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsável",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="actor_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                verbose_name="referência do responsável",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="announcement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marketing_audit_events",
                to="shop.announcement",
                verbose_name="anúncio",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="shop.marketingcontentartifact",
                verbose_name="artefato",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="base_version",
            field=models.PositiveIntegerField(verbose_name="versão de origem"),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="command",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_event",
                to="shop.marketingcommandreceipt",
                verbose_name="comando",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="decision_reason",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="motivo da decisão",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("campaign_fired", "disparo de campanha criado"),
                    ("approved", "aprovado"),
                    ("rejected", "recusado"),
                    ("rescheduled", "reagendado"),
                    ("cancelled", "cancelado"),
                    ("expired", "expirado"),
                    ("delivery_retried", "entrega repetida"),
                    ("reconcile_requested", "reconciliação solicitada"),
                ],
                max_length=24,
                verbose_name="tipo de evento",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="facts",
            field=models.JSONField(blank=True, default=dict, verbose_name="fatos"),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="occurred_at",
            field=models.DateTimeField(verbose_name="ocorrido em"),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="reason_code",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="código do motivo",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="request_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="referência da requisição",
            ),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="resulting_version",
            field=models.PositiveIntegerField(verbose_name="versão resultante"),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="retention_until",
            field=models.DateTimeField(verbose_name="reter até"),
        ),
        migrations.AlterField(
            model_name="marketingauditevent",
            name="snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to="shop.audiencesnapshot",
                verbose_name="público selado",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marketing_command_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsável",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="actor_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=128,
                verbose_name="referência do responsável",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="command_receipts",
                to="shop.announcement",
                verbose_name="anúncio",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="base_version",
            field=models.PositiveIntegerField(verbose_name="versão de origem"),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="concluído em",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="idempotency_key_hash",
            field=models.CharField(
                max_length=64,
                verbose_name="hash da chave de idempotência",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="kind",
            field=models.CharField(
                choices=[
                    ("approve", "aprovar"),
                    ("reject", "recusar"),
                    ("reschedule", "reagendar"),
                    ("publish_now", "publicar agora"),
                    ("cancel", "cancelar"),
                    ("fire", "disparar campanha"),
                    ("expire", "expirar"),
                    ("retry_delivery", "repetir falhas de entrega"),
                    ("reconcile_delivery", "reconciliar entrega desconhecida"),
                    ("configure_platform", "configurar plataforma"),
                ],
                max_length=24,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="outcome",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="resultado",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="payload_hash",
            field=models.CharField(max_length=64, verbose_name="hash dos dados"),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="request_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="referência da requisição",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="resource_ref",
            field=models.CharField(
                max_length=120,
                verbose_name="referência do recurso",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="resulting_version",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="versão resultante",
            ),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="retention_until",
            field=models.DateTimeField(verbose_name="reter até"),
        ),
        migrations.AlterField(
            model_name="marketingcommandreceipt",
            name="state",
            field=models.CharField(
                choices=[
                    ("accepted", "aceito"),
                    ("completed", "concluído"),
                    ("rejected", "recusado"),
                    ("conflict", "conflito"),
                    ("unknown", "resultado desconhecido"),
                ],
                default="accepted",
                max_length=16,
                verbose_name="situação",
            ),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marketing_platform_audit_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsável",
            ),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="actor_ref",
            field=models.CharField(
                db_index=True,
                max_length=128,
                verbose_name="referência do responsável",
            ),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="base_version",
            field=models.PositiveIntegerField(verbose_name="versão de origem"),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="catalog_as_of",
            field=models.DateTimeField(verbose_name="catálogo verificado em"),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="catalog_hash",
            field=models.CharField(max_length=64, verbose_name="hash do catálogo"),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="command",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform_audit_event",
                to="shop.marketingcommandreceipt",
                verbose_name="comando",
            ),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("flow_configured", "flow configurado"),
                    ("flow_cleared", "flow removido"),
                ],
                max_length=24,
                verbose_name="tipo de evento",
            ),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="occurred_at",
            field=models.DateTimeField(verbose_name="ocorrido em"),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="platform",
            field=models.CharField(max_length=32, verbose_name="plataforma"),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="previous_flow_ref",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="flow anterior",
            ),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="request_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="referência da requisição",
            ),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="resulting_flow_ref",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="flow resultante",
            ),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="resulting_version",
            field=models.PositiveIntegerField(verbose_name="versão resultante"),
        ),
        migrations.AlterField(
            model_name="marketingplatformauditevent",
            name="retention_until",
            field=models.DateTimeField(verbose_name="reter até"),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="action",
            field=models.CharField(blank=True, max_length=32, verbose_name="ação"),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marketing_security_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsável",
            ),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="confirmation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_events",
                to="shop.marketingconfirmation",
                verbose_name="confirmação",
            ),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="event_type",
            field=models.CharField(max_length=32, verbose_name="tipo de evento"),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="facts",
            field=models.JSONField(blank=True, default=dict, verbose_name="fatos"),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="occurred_at",
            field=models.DateTimeField(verbose_name="ocorrido em"),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="reason_code",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="código do motivo",
            ),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="resource_ref",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="referência do recurso",
            ),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="retention_until",
            field=models.DateTimeField(verbose_name="reter até"),
        ),
        migrations.AlterField(
            model_name="marketingsecurityevent",
            name="second_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marketing_second_security_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="segundo responsável",
            ),
        ),
    ]
