# Generated by Django 6.0.5 on 2026-09-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_rotulos_campos_auditoria_marketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='envelope',
            field=models.JSONField(blank=True, default=dict, verbose_name='envelope de transporte'),
        ),
    ]
