# Generated by Django 6.0.5 on 2026-09-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_concierge_event_envelope'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='account',
            field=models.CharField(default='legacy_unverified', max_length=128),
        ),
        migrations.AddField(
            model_name='conversation',
            name='claim_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='handoff_sync_state',
            field=models.CharField(default='legacy', max_length=24),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_order_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='conversation',
            name='provider',
            field=models.CharField(default='manychat', max_length=40),
        ),
        migrations.AddField(
            model_name='conversation',
            name='transport_channel',
            field=models.CharField(default='whatsapp', max_length=40),
        ),
        migrations.AddField(
            model_name='conversation',
            name='turn_fence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='consumed_by',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='transport_state',
            field=models.CharField(db_index=True, default='legacy', max_length=24),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='subscriber_id',
            field=models.CharField(max_length=512, verbose_name='assinante ManyChat'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('provider', 'account', 'transport_channel', 'subscriber_id'), name='shop_conv_transport_identity_unique'),
        ),
    ]
