# Generated by Django 6.0.5 on 2026-09-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_concierge_turn_delivery_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='account',
            field=models.CharField(default='legacy_unverified', max_length=128, verbose_name='conta do provedor'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='claim_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='posse do turno até'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='handoff_sync_state',
            field=models.CharField(default='legacy', max_length=24, verbose_name='sincronização do atendimento humano'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_order_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='referência do último pedido'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='provider',
            field=models.CharField(default='manychat', max_length=40, verbose_name='provedor'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='transport_channel',
            field=models.CharField(default='whatsapp', max_length=40, verbose_name='canal de comunicação'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='turn_fence',
            field=models.PositiveBigIntegerField(default=0, verbose_name='versão de controle do turno'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='consumed_by',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='turno que processou a entrada'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='transport_state',
            field=models.CharField(db_index=True, default='legacy', max_length=24, verbose_name='estado do envio'),
        ),
    ]
