# Generated by Django 6.0.5 on 2026-09-12 19:30

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0051_concierge_transport_bindings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ref",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador estável gerado da pergunta no primeiro salvamento.",
                        max_length=96,
                        unique=True,
                        verbose_name="referência",
                    ),
                ),
                ("question", models.CharField(max_length=220, verbose_name="pergunta")),
                (
                    "answer",
                    models.TextField(
                        help_text="Até 2.000 caracteres. Não repita preço, estoque, taxa, cobertura ou horário operacional.",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                        verbose_name="resposta",
                    ),
                ),
                (
                    "search_terms",
                    models.CharField(
                        blank=True,
                        help_text="Sinônimos separados por vírgula usados pela busca da Concierge.",
                        max_length=300,
                        verbose_name="termos de busca",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Menor número aparece primeiro.", verbose_name="posição"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Publica a resposta no site e permite que a Concierge a use.",
                        verbose_name="publicada",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizada em")),
            ],
            options={
                "verbose_name": "pergunta frequente",
                "verbose_name_plural": "perguntas frequentes",
                "ordering": ("position", "id"),
                "indexes": [models.Index(fields=["is_published", "position"], name="shop_faqent_is_publ_c93a2b_idx")],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFAQEntry",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "ref",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador estável gerado da pergunta no primeiro salvamento.",
                        max_length=96,
                        verbose_name="referência",
                    ),
                ),
                ("question", models.CharField(max_length=220, verbose_name="pergunta")),
                (
                    "answer",
                    models.TextField(
                        help_text="Até 2.000 caracteres. Não repita preço, estoque, taxa, cobertura ou horário operacional.",
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                        verbose_name="resposta",
                    ),
                ),
                (
                    "search_terms",
                    models.CharField(
                        blank=True,
                        help_text="Sinônimos separados por vírgula usados pela busca da Concierge.",
                        max_length=300,
                        verbose_name="termos de busca",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Menor número aparece primeiro.", verbose_name="posição"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Publica a resposta no site e permite que a Concierge a use.",
                        verbose_name="publicada",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False, verbose_name="criada em")),
                ("updated_at", models.DateTimeField(blank=True, editable=False, verbose_name="atualizada em")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pergunta frequente",
                "verbose_name_plural": "historical perguntas frequentes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
