# Generated by Django 6.0.5 on 2026-09-15 03:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0003_collection_metadata'),
        ('shop', '0054_disable_remote_auto_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('account_ref', models.CharField(max_length=128)),
                ('catalog_ref', models.CharField(max_length=128)),
                ('context', models.CharField(max_length=128)),
                ('captured_at', models.DateTimeField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sha256', models.CharField(max_length=64)),
                ('raw_json', models.TextField()),
                ('source', models.CharField(max_length=32)),
                ('item_count', models.PositiveIntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_snapshots', to='shop.channel')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-imported_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CatalogBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('account_ref', models.CharField(max_length=128)),
                ('catalog_ref', models.CharField(max_length=128)),
                ('context', models.CharField(max_length=128)),
                ('resource_id', models.CharField(max_length=256)),
                ('external_product_ref', models.CharField(max_length=256)),
                ('category_ref', models.CharField(max_length=256)),
                ('item_context_ref', models.CharField(blank=True, max_length=256)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_bindings', to='shop.channel')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_bindings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_bindings', to='offerman.product')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='shop.catalogsnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='catalogsnapshot',
            index=models.Index(fields=['channel', 'provider', '-imported_at'], name='catalog_snapshot_channel_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogbinding',
            constraint=models.UniqueConstraint(fields=('provider', 'account_ref', 'catalog_ref', 'context', 'resource_id'), name='unique_catalog_remote_resource'),
        ),
    ]
