# Generated by Django 6.0.6 on 2026-09-16 07:19

import uuid

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import shopman.shop.models.privacy


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0056_concierge_message_observation_controls"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyRequestReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="referência")),
                (
                    "operation",
                    models.CharField(
                        choices=[("export", "exportação"), ("deletion", "exclusão")],
                        max_length=16,
                        verbose_name="operação",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("in_progress", "em andamento"), ("completed", "concluído"), ("failed", "falhou")],
                        default="in_progress",
                        max_length=16,
                        verbose_name="situação",
                    ),
                ),
                (
                    "key_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Versão opaca usada para validar o recibo após rotação de chave.",
                        verbose_name="versão da chave HMAC",
                    ),
                ),
                (
                    "subject_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Informe um digest HMAC hexadecimal de 64 caracteres.",
                                regex="\\A[0-9a-f]{64}\\Z",
                            )
                        ],
                        verbose_name="digest do titular",
                    ),
                ),
                (
                    "idempotency_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Informe um digest HMAC hexadecimal de 64 caracteres.",
                                regex="\\A[0-9a-f]{64}\\Z",
                            )
                        ],
                        verbose_name="digest da idempotência",
                    ),
                ),
                (
                    "request_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Informe um digest HMAC hexadecimal de 64 caracteres.",
                                regex="\\A[0-9a-f]{64}\\Z",
                            )
                        ],
                        verbose_name="digest da solicitação",
                    ),
                ),
                (
                    "authorization_method",
                    models.CharField(
                        help_text="Código estável do método, sem credenciais ou identificadores.",
                        max_length=32,
                        verbose_name="método de autorização",
                    ),
                ),
                ("authorized_at", models.DateTimeField(verbose_name="autorizado em")),
                (
                    "failure_stage",
                    models.CharField(
                        blank=True,
                        help_text="Código estável da etapa; nunca uma mensagem de exceção.",
                        max_length=48,
                        verbose_name="etapa da falha",
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        help_text="Código estável e seguro para exposição; nunca a exceção em claro.",
                        max_length=64,
                        verbose_name="código da falha",
                    ),
                ),
                (
                    "outcome_counts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Somente contagens agregadas, sem conteúdo ou identificadores.",
                        verbose_name="contagens do resultado",
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=1, verbose_name="tentativas")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="iniciado em")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="concluído em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "retention_until",
                    models.DateTimeField(
                        default=shopman.shop.models.privacy.privacy_receipt_retention_until, verbose_name="reter até"
                    ),
                ),
            ],
            options={
                "verbose_name": "recibo de solicitação de privacidade",
                "verbose_name_plural": "recibos de solicitações de privacidade",
                "ordering": ["-started_at", "-pk"],
                "indexes": [
                    models.Index(fields=["subject_digest", "operation"], name="shop_privacy_subject_op_idx"),
                    models.Index(fields=["state", "retention_until"], name="shop_privacy_state_ret_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation", "idempotency_digest"),
                        name="shop_privacy_receipt_operation_idem_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("completed_at__isnull", True), ("state", "in_progress")),
                            models.Q(("completed_at__isnull", False), ("state__in", ("completed", "failed"))),
                            _connector="OR",
                        ),
                        name="shop_privacy_receipt_terminal_completed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subject_digest__regex", "^[0-9a-f]{64}$"),
                            ("idempotency_digest__regex", "^[0-9a-f]{64}$"),
                            ("request_digest__regex", "^[0-9a-f]{64}$"),
                        ),
                        name="shop_privacy_receipt_hmac_digests_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__gte", 1)), name="shop_privacy_receipt_attempt_count_ck"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key_version__gte", 1)), name="shop_privacy_receipt_key_version_ck"
                    ),
                ],
            },
        ),
    ]
