# Generated by Django 6.0.5 on 2026-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_privacy_request_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSearch',
            fields=[
            ],
            options={
                'verbose_name': 'Busca e compartilhamento',
                'verbose_name_plural': 'Busca e compartilhamento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.shop',),
        ),
        migrations.AddField(
            model_name='shop',
            name='bing_site_verification',
            field=models.CharField(blank=True, help_text='Só o código da meta tag msvalidate.01.', max_length=100, verbose_name='verificação do Bing Webmaster'),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_type',
            field=models.CharField(choices=[('Bakery', 'Padaria'), ('CafeOrCoffeeShop', 'Café'), ('Restaurant', 'Restaurante'), ('FoodEstablishment', 'Estabelecimento de alimentação'), ('Store', 'Loja')], default='Bakery', help_text='Como o Google classifica o negócio nos dados estruturados.', max_length=40, verbose_name='tipo de negócio'),
        ),
        migrations.AddField(
            model_name='shop',
            name='facebook_domain_verification',
            field=models.CharField(blank=True, help_text='Só o código da meta tag facebook-domain-verification.', max_length=100, verbose_name='verificação de domínio do Facebook'),
        ),
        migrations.AddField(
            model_name='shop',
            name='founding_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano de fundação'),
        ),
        migrations.AddField(
            model_name='shop',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Só o código do atributo content da meta tag. Vazio se a propriedade já foi verificada pelo DNS.', max_length=100, verbose_name='verificação do Google Search Console'),
        ),
        migrations.AddField(
            model_name='shop',
            name='pinterest_domain_verification',
            field=models.CharField(blank=True, help_text='Só o código da meta tag p:domain_verify.', max_length=100, verbose_name='verificação de domínio do Pinterest'),
        ),
        migrations.AddField(
            model_name='shop',
            name='price_range',
            field=models.CharField(blank=True, help_text='Como o Google exibe o preço médio do negócio: "$", "$$" ou "$$$".', max_length=10, verbose_name='faixa de preço'),
        ),
        migrations.AddField(
            model_name='shop',
            name='seo_faq_description',
            field=models.CharField(blank=True, help_text='Aparece no Google para a página /faq.', max_length=170, verbose_name='descrição das perguntas frequentes'),
        ),
        migrations.AddField(
            model_name='shop',
            name='seo_home_description',
            field=models.CharField(blank=True, help_text='O texto cinza sob o título no Google. Até 155 caracteres aparecem inteiros.', max_length=170, verbose_name='descrição da página inicial'),
        ),
        migrations.AddField(
            model_name='shop',
            name='seo_home_title',
            field=models.CharField(blank=True, help_text='O título azul no resultado do Google. Até 60 caracteres aparecem inteiros. Vazio = marca · slogan em cidade.', max_length=70, verbose_name='título da página inicial'),
        ),
        migrations.AddField(
            model_name='shop',
            name='seo_menu_description',
            field=models.CharField(blank=True, help_text='Aparece no Google para a página /menu.', max_length=170, verbose_name='descrição do cardápio'),
        ),
        migrations.AddField(
            model_name='shop',
            name='seo_share_image_url',
            field=models.URLField(blank=True, help_text='Imagem do cartão quando alguém compartilha o site (WhatsApp, Instagram, Facebook). Ideal 1200×630. Vazio = foto do primeiro destaque do cardápio.', max_length=500, verbose_name='imagem de compartilhamento'),
        ),
    ]
