# Generated by Django 6.0.5 on 2026-09-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_shop_search_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingconfirmation',
            name='confirmation_mode',
            field=models.CharField(choices=[('none', 'dispensada'), ('summary', 'resumo'), ('typed', 'digitada')], max_length=16),
        ),
    ]
