# Generated by Django 6.0.5 on 2026-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_shop_search_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(verbose_name='segredo de autenticação do dispositivo'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='device_label',
            field=models.CharField(max_length=120, verbose_name='dispositivo'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(verbose_name='chave pública do dispositivo'),
        ),
    ]
