# Generated by Django 6.0.5 on 2026-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_alter_marketingconfirmation_confirmation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='surface_ref',
            field=models.CharField(choices=[('hub', 'Shopman Apps'), ('orders', 'Pedidos'), ('pos', 'PDV'), ('production', 'Produção'), ('marketing', 'Marketing'), ('purchase', 'Compras'), ('bi', 'BI')], max_length=32, verbose_name='surface'),
        ),
    ]
