# Generated by Django 6.1.1 on 2026-09-22 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_alter_pushsubscription_surface_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IFoodStoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=64, unique=True, verbose_name='loja no iFood')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='conferido em')),
                ('available', models.BooleanField(default=False, verbose_name='recebendo pedidos no iFood')),
                ('state', models.CharField(blank=True, max_length=16, verbose_name='estado no iFood')),
                ('problems', models.JSONField(blank=True, default=list, verbose_name='validações com problema')),
                ('expected_available', models.BooleanField(default=False, verbose_name='a casa esperava aberta')),
                ('divergent_since', models.DateTimeField(blank=True, null=True, verbose_name='divergente desde')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='horário gravado em')),
            ],
            options={
                'verbose_name': 'status da loja no iFood',
                'verbose_name_plural': 'status da loja no iFood',
            },
        ),
        migrations.CreateModel(
            name='IFoodInterruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('calendar', 'Calendário da loja'), ('manual', 'Pausa do gestor')], max_length=16, verbose_name='origem')),
                ('state', models.CharField(choices=[('pending_create', 'Pedindo ao iFood'), ('active', 'Em vigor no iFood'), ('pending_remove', 'Retomando no iFood'), ('removed', 'Retomada'), ('failed', 'Recusada pelo iFood')], default='pending_create', max_length=16, verbose_name='situação')),
                ('merchant_id', models.CharField(max_length=64, verbose_name='loja no iFood')),
                ('ifood_id', models.CharField(blank=True, max_length=100, verbose_name='id no iFood')),
                ('description', models.CharField(max_length=255, verbose_name='descrição enviada')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('starts_at', models.DateTimeField(verbose_name='início')),
                ('ends_at', models.DateTimeField(verbose_name='fim')),
                ('calendar_key', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='dias do calendário')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='pedida em')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='retomada em')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='retomada por')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='pedida por')),
            ],
            options={
                'verbose_name': 'interrupção no iFood',
                'verbose_name_plural': 'interrupções no iFood',
                'ordering': ('-requested_at',),
                'permissions': [('pause_ifood', 'Pode pausar e retomar a loja no iFood')],
            },
        ),
    ]
