# Generated by Django 6.1.1 on 2026-09-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_remote_channel_safety_margin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ifoodinterruption',
            options={'ordering': ('-requested_at',), 'verbose_name': 'interrupção no iFood', 'verbose_name_plural': 'interrupções no iFood'},
        ),
    ]
