# Generated by Django 6.1.1 on 2026-09-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_ifoodinterruption_sem_pausa_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='expires_after_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Anúncio não aprovado caduca depois disso. 0 = não expira. Frescor é efêmero: lote merece prazo curto.', verbose_name='expira em (min)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='trigger',
            field=models.CharField(choices=[('production_finished', 'Lote concluído'), ('low_stock', 'Estoque baixo'), ('stock_back', 'Voltou ao estoque'), ('product_created', 'Produto novo'), ('manual', 'Disparo manual'), ('schedule', 'Agendado')], max_length=64, verbose_name='gatilho'),
        ),
    ]
