# Generated by Django 6.1.1 on 2026-09-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_lote_no_gatilho_e_no_prazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiredProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('collection_refs', models.TextField(blank=True, help_text='Refs separadas por vírgula, na ordem em que a loja deve oferecer. Vazio = a tela só oferece o cardápio.', verbose_name='coleções')),
                ('note', models.CharField(blank=True, help_text='Por que saiu, para quem ler isto daqui a um ano.', max_length=200, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
            ],
            options={
                'verbose_name': 'produto aposentado',
                'verbose_name_plural': 'produtos aposentados',
                'ordering': ['sku'],
            },
        ),
    ]
