# Generated by Django 6.1.1 on 2026-09-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_access_link_button_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='trigger',
            field=models.CharField(choices=[('production_finished', 'Produção concluída'), ('low_stock', 'Estoque baixo'), ('stock_back', 'Voltou ao estoque'), ('product_created', 'Produto novo'), ('manual', 'Disparo manual'), ('schedule', 'Agendado')], max_length=64, verbose_name='gatilho'),
        ),
    ]
