# Generated by Django 6.1.1 on 2026-10-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0085_motivos_de_recusa_aprovados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="surface_ref",
            field=models.CharField(
                choices=[
                    ("hub", "Central"),
                    ("orders", "Pedidos"),
                    ("pos", "PDV"),
                    ("production", "Produção"),
                    ("marketing", "Marketing"),
                    ("purchase", "Compras"),
                    ("bi", "BI"),
                ],
                max_length=32,
                verbose_name="surface",
            ),
        ),
    ]
