# Generated by Django 6.1.1 on 2026-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0088_avisos_de_producao_por_lote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="surface_ref",
            field=models.CharField(
                choices=[
                    ("hub", "Central"),
                    ("orders", "Pedidos"),
                    ("pos", "PDV"),
                    ("production", "Produção"),
                    ("marketing", "Marketing"),
                    ("purchase", "Compras"),
                    ("bi", "BI"),
                    ("kds", "Cozinha"),
                ],
                max_length=32,
                verbose_name="surface",
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("campaign", "campanha"),
                    ("production", "produção"),
                    ("order", "pedidos"),
                    ("purchase", "compras"),
                    ("report", "relatórios"),
                    ("kitchen", "cozinha"),
                    ("sign_in", "acesso"),
                    ("system", "sistema"),
                ],
                default="system",
                max_length=32,
                verbose_name="categoria",
            ),
        ),
    ]
