# Generated by Django 6.1.1 on 2026-10-04 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0089_campanha_lote_pronto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorPasskey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        db_index=True,
                        max_length=512,
                        unique=True,
                        verbose_name="ID da credencial",
                    ),
                ),
                ("public_key", models.TextField(verbose_name="chave pública")),
                (
                    "sign_count",
                    models.BigIntegerField(
                        default=0, verbose_name="contador de assinatura"
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True, default=list, verbose_name="transportes"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="apelido"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="cadastrada em"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="usada em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_passkeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="operador",
                    ),
                ),
            ],
            options={
                "verbose_name": "digital do dispositivo",
                "verbose_name_plural": "digitais dos dispositivos",
                "ordering": ["-last_used_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="shop_oppasskey_user_created",
                    )
                ],
            },
        ),
    ]
