// Contrato gerado pelo Django (fonte única: projections bi_*). Regenerar com
// `python manage.py export_bi_schema`; o teste de drift falha se divergir.
export type {
  BICashDay,
  BICashMethodRow,
  BICashOperatorRow,
  BICashReport,
  BIChangeReport,
  BIConsumptionProfilesReport,
  BICustomerSegmentRow,
  BICustomersReport,
  BICustomersWeekRow,
  BIForecastReport,
  BIOvenTimeRow,
  BIProductionDay,
  BIProductionReport,
  BIProfileBand,
  BIProfileBeverage,
  BIProfileCategoryRow,
  BIProfileRange,
  BIProfileReading,
  BIProfileRow,
  BIProfileSensitivity,
  BIProfilesPrevious,
  BIRevpashRow,
  BISalesChannelRow,
  BISalesDay,
  BISalesReport,
  BIStrikeCell,
  BITopSkuRow,
  ChangeHabit,
  ChangeMix,
  DayChangeForecast,
  DayForecast,
  Expectation,
  ForecastBasis,
  ForecastBranch,
  ForecastOccasion,
  OccasionYear,
} from "~/generated/biContract";
