// Contrato gerado pelo Django (fonte única: projections bi_*). Regenerar com
// `python manage.py export_bi_schema`; o teste de drift falha se divergir.
export type {
  BICashDay,
  BICashMethodRow,
  BICashOperatorRow,
  BICashReport,
  BICustomerSegmentRow,
  BICustomersReport,
  BICustomersWeekRow,
  BIForecastReport,
  BIOvenTimeRow,
  BIProductionDay,
  BIProductionReport,
  BISalesChannelRow,
  BISalesDay,
  BISalesReport,
  BITopSkuRow,
  DayForecast,
  Expectation,
  ForecastBasis,
  ForecastBranch,
  ForecastOccasion,
  OccasionYear,
} from "~/generated/biContract";
