# Generated by Django 6.0.5 on 2026-08-08 20:26

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50, unique=True, verbose_name='Prefixo')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Último valor')),
            ],
            options={
                'verbose_name': 'sequência de referência',
                'verbose_name_plural': 'sequências de referência',
                'db_table': 'crafting_code_sequence',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(help_text='Identificador unico (ex: croissant-v1)', unique=True, verbose_name='Ref')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('output_sku', models.CharField(db_index=True, help_text='SKU ao qual esta ficha técnica/BOM se aplica.', max_length=100, verbose_name='SKU produzido')),
                ('batch_size', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Quantidade produzida pela ficha técnica base; usada para escalar insumos.', max_digits=12, verbose_name='Rendimento base')),
                ('steps', models.JSONField(blank=True, default=list, help_text='Etapas de produção. Ex: ["Mistura", "Fermentação", "Modelagem", "Forno"]', verbose_name='Etapas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Metadados da ficha técnica. Ex: {"prep_time_min": 30, "bake_temp_c": 220}', verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'ficha técnica',
                'verbose_name_plural': 'fichas técnicas',
                'db_table': 'crafting_recipe',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['output_sku'], name='crafting_re_output__c876a3_idx'), models.Index(fields=['is_active'], name='crafting_re_is_acti_16b7d2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('batch_size__gt', 0)), name='craft_recipe_batch_positive'), models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('output_sku', ''), _negated=True)), fields=('output_sku',), name='craft_recipe_active_output_uq')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Referência')),
                ('output_sku', models.CharField(help_text='Copiado da Recipe no plan', max_length=100, verbose_name='Produto')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Planejado atual (mutavel via adjust enquanto planned)', max_digits=12, verbose_name='Quantidade Planejada')),
                ('finished', models.DecimalField(blank=True, decimal_places=3, help_text='Set no finish, imutavel depois', max_digits=12, null=True, verbose_name='Quantidade Concluída')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('started', 'Iniciada'), ('finished', 'Concluída'), ('void', 'Cancelada')], default='planned', max_length=10, verbose_name='Status')),
                ('rev', models.PositiveIntegerField(default=0, help_text='Optimistic concurrency counter', verbose_name='Revisao')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Data Agendada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('source_ref', models.CharField(blank=True, help_text="'order:789', 'forecast:Q1'", max_length=100, verbose_name='Origem')),
                ('position_ref', models.CharField(blank=True, help_text="Ref da Position no Stockman (ex: 'producao')", max_length=100, verbose_name='Posição')),
                ('operator_ref', models.CharField(blank=True, help_text="'user:joao'", max_length=100, verbose_name='Responsavel')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='craftsman.recipe', verbose_name='Ficha técnica')),
            ],
            options={
                'verbose_name': 'ordem de produção',
                'verbose_name_plural': 'ordens de produção',
                'db_table': 'crafting_work_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='Sequencia')),
                ('kind', models.CharField(choices=[('planned', 'Planejado'), ('adjusted', 'Ajustado'), ('started', 'Iniciado'), ('finished', 'Concluído'), ('voided', 'Cancelado')], max_length=20, verbose_name='Tipo')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Dados do evento. Schema por kind documentado no módulo.', verbose_name='Dados')),
                ('actor', models.CharField(blank=True, max_length=100, verbose_name='Ator')),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Chave de Idempotencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='craftsman.workorder', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'evento da ordem',
                'verbose_name_plural': 'eventos da ordem',
                'db_table': 'crafting_work_order_event',
                'ordering': ['work_order', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('requirement', 'Requisito'), ('consumption', 'Consumo'), ('output', 'Saida'), ('waste', 'Perda')], max_length=15, verbose_name='Tipo')),
                ('item_ref', models.CharField(help_text='SKU ou identificador do material', max_length=100, verbose_name='Referencia')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unidade')),
                ('recorded_at', models.DateTimeField(verbose_name='Registrado em')),
                ('recorded_by', models.CharField(blank=True, max_length=100, verbose_name='Registrado por')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='lot, expires, reason, step, etc.', verbose_name='Metadados')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='craftsman.workorder', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'item da ordem',
                'verbose_name_plural': 'itens da ordem',
                'db_table': 'crafting_work_order_item',
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_sku', models.CharField(db_index=True, help_text='Referencia do material de entrada', max_length=100, verbose_name='Insumo')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantidade para o rendimento base da ficha técnica.', max_digits=12, verbose_name='Quantidade')),
                ('unit', models.CharField(choices=[('un', 'un.'), ('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('L', 'L'), ('ml', 'ml')], default='kg', max_length=20, verbose_name='Unidade')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_optional', models.BooleanField(default=False, help_text='Ingrediente alternativo', verbose_name='Opcional')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='craftsman.recipe', verbose_name='Ficha técnica')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'db_table': 'crafting_recipe_item',
                'ordering': ['sort_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='craft_recipeitem_qty_positive'), models.CheckConstraint(condition=models.Q(('unit__in', ['un', 'kg', 'g', 'mg', 'L', 'ml'])), name='craft_recipeitem_unit_known')],
                'unique_together': {('recipe', 'input_sku')},
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'target_date'], name='crafting_wo_status_7e4de4_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['output_sku', 'status'], name='crafting_wo_output__0c72f3_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['target_date'], name='crafting_wo_target__173b8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='craft_wo_quantity_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='workorderevent',
            unique_together={('work_order', 'seq')},
        ),
        migrations.AddIndex(
            model_name='workorderitem',
            index=models.Index(fields=['work_order', 'kind'], name='crafting_wo_work_or_d18282_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderitem',
            index=models.Index(fields=['item_ref', 'kind'], name='crafting_wo_item_re_aa0889_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderitem',
            index=models.Index(fields=['recorded_at'], name='crafting_wo_recorde_7781b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='craft_woitem_qty_positive'),
        ),
    ]
