# Generated by Django 6.0.5 on 2026-08-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='batch_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='quality_defect_ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Defeito'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='quality_grade_ref',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Grau de qualidade'),
        ),
    ]
