# Generated by Django 6.0.5 on 2026-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0002_workorderitem_batch_ref_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workorderitem',
            index=models.Index(fields=['quality_grade_ref', 'recorded_at'], name='crafting_wo_quality_ae926b_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderitem',
            index=models.Index(fields=['quality_defect_ref', 'recorded_at'], name='crafting_wo_quality_17a84e_idx'),
        ),
    ]
