# Generated by Django 6.0.5 on 2026-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0003_workorderitem_crafting_wo_quality_ae926b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ref',
            field=models.SlugField(help_text='Identificador único (ex: croissant-v1)', unique=True, verbose_name='Ref'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='input_sku',
            field=models.CharField(db_index=True, help_text='Referência do material de entrada', max_length=100, verbose_name='Insumo'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='finished',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Set no finish, imutável depois', max_digits=12, null=True, verbose_name='Quantidade Concluída'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='operator_ref',
            field=models.CharField(blank=True, help_text="'user:joao'", max_length=100, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Planejado atual (mutável via adjust enquanto planned)', max_digits=12, verbose_name='Quantidade Planejada'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='rev',
            field=models.PositiveIntegerField(default=0, help_text='Optimistic concurrency counter', verbose_name='Revisão'),
        ),
        migrations.AlterField(
            model_name='workorderevent',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Chave de Idempotência'),
        ),
        migrations.AlterField(
            model_name='workorderevent',
            name='seq',
            field=models.PositiveIntegerField(verbose_name='Sequência'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='item_ref',
            field=models.CharField(help_text='SKU ou identificador do material', max_length=100, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='kind',
            field=models.CharField(choices=[('requirement', 'Requisito'), ('consumption', 'Consumo'), ('output', 'Saída'), ('waste', 'Perda')], max_length=15, verbose_name='Tipo'),
        ),
    ]
