# Generated by Django 6.0.5 on 2026-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0005_backfill_stock_ledger_markers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='output_sku',
            field=models.CharField(help_text='SKU ao qual esta ficha técnica/BOM se aplica.', max_length=100, verbose_name='SKU produzido'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='input_sku',
            field=models.CharField(help_text='Referência do material de entrada', max_length=100, verbose_name='Insumo'),
        ),
    ]
