# Generated by Django 6.0.5 on 2026-09-03 09:26

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0006_alter_recipe_output_sku_alter_recipeitem_input_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(help_text='Identificador único; igual ao ref da ficha técnica quando publicada.', unique=True, verbose_name='Ref')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('bread', 'Pão'), ('viennoiserie', 'Viennoiserie'), ('sweet_dough', 'Massa doce'), ('filling', 'Recheio'), ('cream', 'Creme'), ('sauce', 'Molho'), ('beverage', 'Bebida'), ('other', 'Outra')], default='other', max_length=20, verbose_name='Tipo')),
                ('output_sku', models.CharField(blank=True, default='', help_text='Vazio = receita sem SKU, só conhecimento.', max_length=100, verbose_name='SKU produzido')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arquivada')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
                'db_table': 'crafting_recipe_entry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('superseded', 'Substituída')], default='draft', max_length=12, verbose_name='Status')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='O que mudou')),
                ('yield_quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Rendimento da fórmula tal como escrita.', max_digits=12, verbose_name='Rendimento')),
                ('yield_unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('un', 'un.'), ('L', 'L'), ('ml', 'ml')], default='kg', max_length=5, verbose_name='Unidade do rendimento')),
                ('formula', models.JSONField(blank=True, default=dict, verbose_name='Fórmula')),
                ('origin', models.JSONField(blank=True, default=dict, help_text='A receita como chegou (quantidades, unidades, texto). Imutável.', verbose_name='Como foi informada')),
                ('source', models.JSONField(blank=True, default=dict, help_text='{kind: manual|note|photo|ficha|import, text?, language?, image_name?, model?}', verbose_name='Origem')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='Etapas')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='Criado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicada em')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='craftsman.recipeentry', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'versão de receita',
                'verbose_name_plural': 'versões de receita',
                'db_table': 'crafting_recipe_version',
                'ordering': ['entry', '-number'],
            },
        ),
        migrations.AddField(
            model_name='recipeentry',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='A última versão publicada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='craftsman.recipeversion', verbose_name='Versão atual'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('entry', 'number'), name='craft_recipeversion_entry_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('yield_quantity__gt', 0)), name='craft_recipeversion_yield_positive'),
        ),
        migrations.AddIndex(
            model_name='recipeentry',
            index=models.Index(fields=['output_sku'], name='crafting_re_output__07fc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeentry',
            index=models.Index(fields=['kind'], name='crafting_re_kind_9e1a6c_idx'),
        ),
    ]
