# Generated by Django 6.0.5 on 2026-09-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("craftsman", "0007_recipe_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("planned", "Planejado"),
                    ("planning_confirmed", "Planejamento confirmado"),
                    ("adjusted", "Ajustado"),
                    ("started", "Iniciado"),
                    ("step_advanced", "Passo avançado"),
                    ("oven_armed", "Enfornado"),
                    ("oven_concluded", "Retirado do forno"),
                    ("oven_abandoned", "Medição de forno abandonada"),
                    ("shortage_overridden", "Falta sobreposta"),
                    ("finished", "Concluído"),
                    ("voided", "Cancelado"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
