# Generated by Django 6.1.1 on 2026-09-24 00:14

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0011_alter_workorderevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='usable_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Quanto do insumo BRUTO sobra depois de limpar: cebola 84%, tomilho só folhas 60%, suco de limão 40%. 100% = nada se perde no preparo.', max_digits=5, verbose_name='Aproveitamento (%)'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade LÍQUIDA para o rendimento base da ficha técnica: o que entra no produto, já limpo. O que sai do estoque é a bruta, derivada de `usable_pct`.', max_digits=12, verbose_name='Quantidade'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('usable_pct__gt', 0), ('usable_pct__lte', 100)), name='craft_recipeitem_usable_pct_range'),
        ),
    ]
