# Generated by Django 6.1.1 on 2026-09-24 10:48

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0012_recipeitem_usable_pct_alter_recipeitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeitem',
            name='craft_recipeitem_usable_pct_range',
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='usable_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Quanto do insumo BRUTO sobra depois de limpar, em FRAÇÃO: cebola 0,84, tomilho só folhas 0,60, suco de limão 0,40. 1 = nada se perde. ⚠️ Não confundir com o «fator de correção» da cozinha, que é o INVERSO deste (1 ÷ 0,84 = 1,19) — aqui o número é o que sobra, nunca o multiplicador de compra.', max_digits=5, verbose_name='Fator de aproveitamento'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade LÍQUIDA para o rendimento base da ficha técnica: o que entra no produto, já limpo. O que sai do estoque é a bruta, derivada de `usable_factor`.', max_digits=12, verbose_name='Quantidade'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('usable_factor__gt', 0), ('usable_factor__lte', 1)), name='craft_recipeitem_usable_factor_range'),
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='usable_pct',
        ),
    ]
