# Generated by Django 6.1.1 on 2026-09-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0013_remove_recipeitem_craft_recipeitem_usable_pct_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(choices=[('un', 'un.'), ('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('L', 'L'), ('ml', 'ml')], default='g', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='recipeversion',
            name='yield_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('un', 'un.'), ('L', 'L'), ('ml', 'ml')], default='g', max_length=5, verbose_name='Unidade do rendimento'),
        ),
    ]
