# Generated by Django 6.1.1 on 2026-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsman', '0015_steps_as_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderevent',
            name='kind',
            field=models.CharField(choices=[('planned', 'Planejado'), ('planning_confirmed', 'Planejamento confirmado'), ('adjusted', 'Ajustado'), ('started', 'Iniciado'), ('step_advanced', 'Etapa avançada'), ('oven_armed', 'Enfornado'), ('oven_concluded', 'Retirado do forno'), ('oven_abandoned', 'Medição de forno abandonada'), ('shortage_overridden', 'Falta sobreposta'), ('finished', 'Concluído'), ('quality_corrected', 'Qualidade corrigida'), ('quality_reviewed', 'Qualidade revisada'), ('voided', 'Cancelado')], max_length=20, verbose_name='Tipo'),
        ),
    ]
