# Generated by Django 6.1.1 on 2026-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("craftsman", "0016_step_advanced_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="finished",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Set no finish, imutável depois",
                max_digits=12,
                null=True,
                verbose_name="Quantidade realizada",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fechada em"
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Planejado atual (mutável via adjust enquanto planned)",
                max_digits=12,
                verbose_name="Quantidade planejada",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Aberta em"),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planejada"),
                    ("started", "Aberta"),
                    ("finished", "Fechada"),
                    ("void", "Cancelada"),
                ],
                default="planned",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="workorderevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("planned", "Planejado"),
                    ("planning_confirmed", "Planejamento confirmado"),
                    ("adjusted", "Ajustado"),
                    ("started", "Abertura"),
                    ("step_advanced", "Etapa avançada"),
                    ("oven_armed", "Enfornado"),
                    ("oven_concluded", "Retirado do forno"),
                    ("oven_abandoned", "Medição de forno abandonada"),
                    ("shortage_overridden", "Falta sobreposta"),
                    ("finished", "Fechamento"),
                    ("quality_corrected", "Qualidade corrigida"),
                    ("quality_reviewed", "Qualidade revisada"),
                    ("voided", "Cancelado"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
