# Generated by Django 6.0.5 on 2026-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='nonconformity_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentual resolvido na inspeção; 0 = preço cheio.', verbose_name='Desconto do lote (%)'),
        ),
        migrations.AddField(
            model_name='batch',
            name='nonconformity_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Motivo de não conformidade'),
        ),
    ]
