# Generated by Django 6.0.5 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockman", "0002_batch_nonconformity_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="quality_grade_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Referência opaca do grau resolvido na inspeção.",
                max_length=32,
                verbose_name="Grau de qualidade",
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["quality_grade_ref"],
                name="stocking_ba_quality_idx",
            ),
        ),
    ]
