// Production contract types. The structural shapes come from the generated
// mirror (app/generated/productionContract.ts — source of truth:
// shopman/backstage/projections/production.py, regenerated by
// `python manage.py export_production_schema` and drift-guarded in the Django
// CI). This module only narrows fields the backend types as plain `str`,
// keeps the surface's short aliases, and adds the API envelopes.

import type {
  ForecastRowProjection as ForecastRowContract,
  OperatorAlertProjection as OperatorAlertContract,
  OperatorAlertsProjection as OperatorAlertsContract,
  ProductionActionProjection,
  ProductionBlindMapProjection,
  ProductionBoardProjection,
  ProductionDashboardProjection,
  ProductionForecastProjection as ProductionForecastContract,
  ProductionKDSCardProjection as ProductionKDSCardContract,
  ProductionKDSProjection as ProductionKDSContract,
  ProductionMiseEnPlaceProjection,
  ProductionMaterialShortageErrorBody,
  ProductionMaterialShortageItem,
  ProductionOrderShortageErrorBody,
  ProductionReportsProjection,
  ProductionWeighingIngredientProjection,
  ProductionWeighingProjection,
  ProductionWeighingTicketProjection,
  QCKioskProjection,
} from "~/generated/productionContract";

export type {
  BaseRecipeOptionProjection,
  BaseRecipeUsageProjection,
  MiseEnPlaceBreakdownProjection,
  MiseEnPlaceLineProjection,
  OperatorProductivityRow,
  OrderCommitmentProjection,
  PositionOptionProjection,
  ProductionBlindMapProjection,
  ProductionBlindMapRowProjection,
  ProductionBoardProjection,
  ProductionCountsProjection,
  ProductionDashboardProjection,
  ProductionLateWorkOrderProjection,
  ProductionMutationCurrent,
  ProductionMatrixGroupProjection,
  ProductionMatrixGroupRowProjection,
  ProductionMatrixRowProjection,
  ProductionMiseEnPlaceProjection,
  ProductionReportsProjection,
  ProductionSuggestionProjection,
  ProductionSurfaceAccess,
  ProductionWeighingProjection,
  QCDefectProjection,
  QCGradeProjection,
  QCKioskProjection,
  QCOrderCardProjection,
  RecipeOptionProjection,
  RecipeWasteRow,
  WorkOrderCardProjection,
  WorkOrderReportRow,
} from "~/generated/productionContract";

export type ProductionTimerStatusCode = "on_time" | "warning" | "late";

// ── Live floor (KDS) ───────────────────────────────────────────────────────

export interface ProductionKDSCardProjection extends ProductionKDSCardContract {
  timer_status_code: ProductionTimerStatusCode;
}

export interface ProductionKDSProjection extends ProductionKDSContract {
  cards: ProductionKDSCardProjection[];
}

export interface ProductionKDSResponse {
  kds: ProductionKDSProjection;
}

// ── Planning board (matrix) ────────────────────────────────────────────────

export interface ProductionBoardResponse {
  board: ProductionBoardProjection;
}

// ── O PAINEL — previsão da produção (estilo aeroporto) ──────────────────────
// O status É a escada de confiança: Planejado → Previsto → Confirmado.

export type ForecastStatus = "scheduled" | "in_progress" | "delayed" | "arrived";

export interface ForecastRowProjection extends ForecastRowContract {
  status: ForecastStatus;
}

export interface ProductionForecastProjection extends ProductionForecastContract {
  rows: ForecastRowProjection[];
}

export interface ProductionForecastResponse {
  forecast: ProductionForecastProjection;
}

// ── Structured shortage envelope (material/order) ──────────────────────────
// Mirrors backstage/api/operations.py `_shortage_response` (HTTP 409).

export type MaterialShortageItem = ProductionMaterialShortageItem;
export type MaterialShortageError = ProductionMaterialShortageErrorBody;
export type OrderShortageError = ProductionOrderShortageErrorBody;

export type ProductionShortageError = MaterialShortageError | OrderShortageError;

// ── Operator alerts (shared backstage projection) ──────────────────────────

export type AlertActionProjection = ProductionActionProjection & {
  kind: "acknowledge_alert";
  payload_schema: "AlertAckMutationRequest";
  expected_rev: number;
  source_alert_ref: string;
  source_alert_effect: "acknowledges";
};

export interface AlertProjection extends Omit<OperatorAlertContract, "actions" | "severity"> {
  severity: "warning" | "error" | "critical";
  actions: AlertActionProjection[];
}

export interface AlertsResponse extends Omit<OperatorAlertsContract, "alerts"> {
  alerts: AlertProjection[];
}

// ── Mise en place (aggregated material needs) ───────────────────────────────

export interface MiseEnPlaceResponse {
  mise_en_place: ProductionMiseEnPlaceProjection;
}

// ── Weighing (per-prep tickets + blind codes) ───────────────────────────────
// Short aliases kept for the surface's components.

export type WeighingIngredientProjection = ProductionWeighingIngredientProjection;
export type WeighingTicketProjection = ProductionWeighingTicketProjection;

export interface WeighingResponse {
  weighing: ProductionWeighingProjection;
}

// ── Relatórios e gestão (persona GESTOR — página /reports) ──────────────────

export interface ProductionReportsResponse {
  reports: ProductionReportsProjection;
}

export interface ProductionManagementResponse {
  management: ProductionDashboardProjection;
}

export interface ProductionBlindMapResponse {
  blind_map: ProductionBlindMapProjection;
}

// ── Quiosque de QC (fechamento de fornada — ADR-017 §9) ─────────────────────

export interface ProductionQCResponse {
  qc: QCKioskProjection;
}
