// Recipe book contract types. The structural shapes come from the generated
// mirror (app/generated/recipeBookContract.ts — source of truth:
// shopman/backstage/projections/recipe_book.py, regenerated by
// `python manage.py export_recipe_book_schema`). This module only narrows the
// fields the backend types as plain `str`, declares the API envelopes
// (RECIPE-INVENTORY-PLAN §8) and the WRITE payload of a formula (§3) — the one
// shape the surface authors, everything else arrives screen-ready (ADR-014).

import type {
  FormulaLensProjection,
  IngredientOptionProjection,
  RecipeBookAccessProjection,
  RecipeBookListProjection,
  RecipeCaptureDraftProjection,
  RecipeCompareProjection,
  RecipeEntryDetailProjection,
  RecipeReferenceProjection,
  RecipeVersionProjection,
} from "~/generated/recipeBookContract";

export type {
  CaptureItemProjection,
  FormulaItemProjection,
  FormulaLensProjection,
  FormulaMetricProjection,
  FormulaPartProjection,
  FormulaWarningProjection,
  IngredientOptionProjection,
  KindOptionProjection,
  RecipeBookAccessProjection,
  RecipeBookListProjection,
  RecipeCaptureDraftProjection,
  RecipeCompareMetricProjection,
  RecipeCompareProjection,
  RecipeCompareRowProjection,
  RecipeEntryCardProjection,
  RecipeEntryDetailProjection,
  RecipeReferenceProjection,
  RecipeVersionProjection,
  ReferenceRangeProjection,
} from "~/generated/recipeBookContract";

// ── Vocabulário estreitado (o backend manda `str`) ──────────────────────────

/** Tom funcional das métricas, avisos e deltas: calmo por padrão. */
export type LensTone = "ok" | "warning" | "muted";

export type RecipeKind =
  | "bread"
  | "viennoiserie"
  | "sweet_dough"
  | "filling"
  | "cream"
  | "sauce"
  | "beverage"
  | "other";

export type VersionStatus = "draft" | "published" | "superseded";

export type AnchorKind = "flour" | "total" | "ingredient";

export type IngredientRole =
  | "flour"
  | "liquid"
  | "salt"
  | "yeast"
  | "fat"
  | "sugar"
  | "egg"
  | "dairy"
  | "inclusion"
  | "other";

export type FormulaUnit = "g" | "kg" | "ml" | "L" | "un";

export type PartKind = "preferment" | "autolyse" | "soaker" | "old_dough";

export type YieldUnit = "kg" | "g" | "un" | "L" | "ml";

// ── Payload de escrita: `RecipeVersion.formula` (§3) ────────────────────────

export interface FormulaAnchor {
  kind: AnchorKind;
  /** Só com `kind: "ingredient"`: o SKU-âncora (o leite de um creme). */
  sku?: string;
}

export interface FormulaItem {
  /** "" = ingrediente ainda não casado com insumo (permitido em rascunho). */
  sku: string;
  name: string;
  role: IngredientRole;
  quantity: number;
  unit: FormulaUnit;
  note?: string;
  /** Contagem (`un`) só entra na conta com gramas por unidade. */
  grams_per_unit?: number | null;
  /** Volume vira grama pela densidade; sem ela, 1,0 para líquido (com aviso). */
  density_g_per_ml?: number | null;
}

export interface FormulaPart {
  sku?: string;
  entry_ref?: string;
  kind: PartKind;
  /** Âncora `flour`: % da farinha total que passa pela parte. */
  flour_pct?: number | null;
  /** Sem âncora `flour`: a quantidade declarada. */
  quantity?: number | null;
  unit?: FormulaUnit;
  /** Só `old_dough`: teto da fórmula inteira. */
  cap_pct?: number | null;
}

export interface Formula {
  anchor: FormulaAnchor;
  basis_g: number | null;
  standardized: boolean;
  items: FormulaItem[];
  parts: FormulaPart[];
}

/** Corpo de `POST recipes/<ref>/versions/` e do `version` de `POST recipes/`. */
export interface VersionPayload {
  from_version?: number;
  formula: Formula;
  yield_quantity: string;
  yield_unit: string;
  steps?: string[];
  notes?: string;
  label?: string;
  origin?: Record<string, unknown>;
  source?: Record<string, unknown>;
}

/** Campos do rascunho aceitos por `PATCH recipes/<ref>/versions/<n>/`. */
export interface DraftPatch {
  formula?: Formula;
  yield_quantity?: string;
  yield_unit?: string;
  steps?: string[];
  notes?: string;
  label?: string;
}

/** Corpo de `POST recipes/`. */
export interface EntryCreatePayload {
  ref?: string;
  name: string;
  kind: string;
  output_sku: string;
  notes: string;
  version?: VersionPayload;
}

/** Corpo de `PATCH recipes/<ref>/`. */
export interface EntryPatch {
  name?: string;
  kind?: string;
  output_sku?: string;
  notes?: string;
  is_archived?: boolean;
}

/** Corpo de `POST recipes/capture/`. */
export interface CaptureImagePayload {
  data_base64: string;
  media_type: string;
}

// ── Envelopes da API (§8) ───────────────────────────────────────────────────

export interface RecipeBookListResponse {
  book: RecipeBookListProjection;
  access: RecipeBookAccessProjection;
}

export interface RecipeEntryResponse {
  entry: RecipeEntryDetailProjection;
  access?: RecipeBookAccessProjection;
}

export interface RecipeVersionResponse {
  entry: RecipeEntryDetailProjection;
  version: RecipeVersionProjection;
}

export interface LensResponse {
  lens: FormulaLensProjection;
}

export interface StandardizeResponse {
  formula: Formula;
  lens: FormulaLensProjection;
}

export interface CompareResponse {
  compare: RecipeCompareProjection;
}

export interface ReferenceResponse {
  reference: RecipeReferenceProjection;
}

export interface IngredientsResponse {
  options: IngredientOptionProjection[];
}

export interface CaptureResponse {
  draft: RecipeCaptureDraftProjection;
}

export interface AccessResponse {
  access: RecipeBookAccessProjection;
}
