# Generated by Django 6.0.5 on 2026-08-11 23:06

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('guestman', '0002_rename_customer_group_to_price_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaggedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='guestman.customertag', verbose_name='etiqueta')),
            ],
            options={
                'verbose_name': 'cliente etiquetado',
                'verbose_name_plural': 'clientes etiquetados',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Separe por vírgula. Ex: corredores, sem glúten, vizinho', through='guestman.TaggedCustomer', to='guestman.CustomerTag', verbose_name='etiquetas'),
        ),
    ]
