# Generated by Django 6.0.5 on 2026-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0003_customer_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ref',
            field=models.CharField(help_text='Referência única do cliente (ex: CLI-001)', max_length=50, unique=True, verbose_name='referência'),
        ),
    ]
