# Generated by Django 6.1.1 on 2026-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestman', '0004_alter_customer_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderErasureTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manychat', 'ManyChat')], max_length=32, verbose_name='provedor')),
                ('handle_type', models.CharField(choices=[('subscriber_id', 'identificador do assinante')], max_length=24, verbose_name='tipo do identificador')),
                ('digest', models.CharField(db_index=True, max_length=64, verbose_name='digest do identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
            ],
            options={
                'verbose_name': 'lápide de exclusão',
                'verbose_name_plural': 'lápides de exclusão',
                'constraints': [models.UniqueConstraint(fields=('provider', 'handle_type', 'digest'), name='guestman_provider_erasure_uq')],
            },
        ),
    ]
