# Generated by Django 6.0.5 on 2026-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(db_index=True, verbose_name='ID do cliente')),
                ('credential_id', models.CharField(db_index=True, max_length=512, unique=True, verbose_name='ID da credencial')),
                ('public_key', models.TextField(verbose_name='chave pública')),
                ('sign_count', models.BigIntegerField(default=0, verbose_name='contador de assinatura')),
                ('transports', models.JSONField(blank=True, default=list, verbose_name='transportes')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='apelido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='usada em')),
            ],
            options={
                'verbose_name': 'passkey',
                'verbose_name_plural': 'passkeys',
                'ordering': ['-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['customer_id', '-created_at'], name='doorman_pas_custome_5fa688_idx')],
            },
        ),
    ]
