# Generated by Django 6.0.5 on 2026-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0002_passkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='subject_type',
            field=models.CharField(choices=[('customer', 'cliente'), ('display', 'quadro')], db_index=True, default='customer', max_length=16, verbose_name='tipo de sujeito'),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='navegador'),
        ),
    ]
