# Generated by Django 6.0.5 on 2026-08-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'sessão de venda', 'verbose_name_plural': 'sessões de venda'},
        ),
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ('session_key', 'seq'), 'verbose_name': 'evento da sessão', 'verbose_name_plural': 'eventos da sessão'},
        ),
        migrations.AlterModelOptions(
            name='sessionitem',
            options={'verbose_name': 'item da sessão', 'verbose_name_plural': 'itens da sessão'},
        ),
    ]
