# Generated by Django 6.0.5 on 2026-08-15 15:28

import shopman.orderman.models.session
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0002_rename_session_to_sale_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directive',
            name='payload',
            field=models.JSONField(blank=True, default=dict, encoder=shopman.orderman.models.session.DecimalEncoder, help_text='Dados da tarefa. Schema depende do topic. Ex: stock.hold → {"sku": "PAO-FRANCES", "qty": 10}', verbose_name='dados da tarefa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=shopman.orderman.models.session.DecimalEncoder, help_text='Snapshot selado do pedido no momento da criação. Não editar manualmente.', verbose_name='retrato do pedido'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='payload',
            field=models.JSONField(default=dict, help_text='Dados do evento. Ex: {"new_status": "accepted"} ou {"error": "motivo"}', verbose_name='dados do evento'),
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='payload',
            field=models.JSONField(default=dict, help_text='Delta da ação. Ex: {"sku": "PAO", "qty_before": 3, "qty_after": 0}', verbose_name='dados do evento'),
        ),
    ]
