# Generated by Django 6.0.5 on 2026-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0003_rotulos_em_portugues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionitem',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='SKU'),
        ),
    ]
