# Generated by Django 6.0.5 on 2026-08-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderman', '0008_order_status_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='payload',
            field=models.JSONField(default=dict, help_text='Dados do evento. Ex: {"new_status": "accepted"} ou {"error": "motivo"}', verbose_name='payload'),
        ),
    ]
