# Generated by Django 6.0.5 on 2026-08-18 21:04

import django.db.models.deletion
import django.utils.timezone
import shopman.cashman.models.terminal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=80, unique=True, verbose_name='ref')),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='rótulo')),
                ('channel_ref', models.CharField(default=shopman.cashman.models.terminal._default_channel_ref, max_length=80, verbose_name='canal')),
                ('location_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='local')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Configuração do aparelho (hardware, trava). Schema em docs/reference/data-schemas.md.', verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'terminal',
                'verbose_name_plural': 'terminais',
                'ordering': ['ref'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aberto em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=10, verbose_name='status')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='cashman.terminal', verbose_name='terminal')),
            ],
            options={
                'verbose_name': 'turno de caixa',
                'verbose_name_plural': 'turnos de caixa',
                'ordering': ['-opened_at'],
                'permissions': [('operate_pos', 'Pode operar o PDV (abrir/fechar caixa, sangria, balcão)'), ('audit_shift', 'Pode auditar turnos de caixa (esperado, diferença)'), ('adjust_shift', 'Pode autorizar exceções do caixa (retirada, destrave, correção)'), ('manage_operators', 'Pode gerir operadores (resetar PIN, provisionar)')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='quando')),
                ('kind', models.CharField(choices=[('float_in', 'Fundo de troco'), ('sale', 'Venda'), ('cod_settled', 'Acerto de entrega'), ('cash_in', 'Entrada de caixa'), ('refund', 'Devolução'), ('cash_out', 'Saída de caixa'), ('count', 'Contagem de fechamento'), ('count_correction', 'Correção da contagem'), ('drawer_open', 'Gaveta aberta sem venda'), ('drawer_unlock', 'Trava da gaveta liberada'), ('change_requested', 'Troco pedido'), ('change_served', 'Troco atendido'), ('change_cancelled', 'Pedido de troco cancelado'), ('receipt_result', 'Resultado do comprovante'), ('note', 'Anotação')], max_length=24, verbose_name='tipo')),
                ('amount_q', models.BigIntegerField(default=0, help_text='Efeito no saldo da gaveta, assinado. Zero quando o evento não mexe em dinheiro.', verbose_name='efeito (centavos)')),
                ('order_ref', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='ref do pedido')),
                ('payment_ref', models.CharField(blank=True, default='', help_text='Ref do PaymentIntent no payman (venda, devolução, acerto de entrega).', max_length=64, verbose_name='ref do pagamento')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='motivo')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='O específico de cada tipo. Schema em docs/reference/data-schemas.md.', verbose_name='detalhe')),
                ('approved_by', models.ForeignKey(blank=True, help_text='A segunda assinatura: sangria, destrave, troco atendido, correção.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries_approved', to=settings.AUTH_USER_MODEL, verbose_name='autorizado por')),
                ('operator', models.ForeignKey(help_text='Quem agiu: o do turno, ou o gerente num fechamento supervisório.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('parent', models.ForeignKey(blank=True, help_text='O lançamento que este atende, resolve ou corrige.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='cashman.entry', verbose_name='responde a')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='cashman.shift', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'lançamento de caixa',
                'verbose_name_plural': 'lançamentos de caixa',
                'ordering': ['at', 'id'],
                'indexes': [models.Index(fields=['shift', 'id'], name='cashman_entry_shift_id_idx'), models.Index(fields=['operator', 'at'], name='cashman_entry_op_at_idx'), models.Index(fields=['kind', 'at'], name='cashman_entry_kind_at_idx'), models.Index(fields=['at'], name='cashman_entry_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount_q__gt', 0), ('kind__in', ['float_in', 'cod_settled', 'cash_in'])), models.Q(('amount_q__gte', 0), ('kind', 'sale')), models.Q(('amount_q__lt', 0), ('kind__in', ['refund', 'cash_out'])), ('kind__in', ['count', 'count_correction']), models.Q(('amount_q', 0), ('kind__in', ['drawer_open', 'drawer_unlock', 'change_requested', 'change_served', 'change_cancelled', 'receipt_result', 'note'])), _connector='OR'), name='cashman_entry_sign_by_kind')],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['opened_at'], name='cashman_shift_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['closed_at'], name='cashman_shift_closed_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('operator',), name='cashman_shift_open_operator_uq'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('terminal',), name='cashman_shift_open_terminal_uq'),
        ),
    ]
