# Generated by Django 6.0.5 on 2026-08-19 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashman', '0002_courier_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='cashman_entry_sign_by_kind',
        ),
        migrations.AlterField(
            model_name='entry',
            name='kind',
            field=models.CharField(choices=[('float_in', 'Fundo de troco'), ('sale', 'Venda'), ('cod_settled', 'Acerto de entrega'), ('account_settled', 'Acerto de conta'), ('cash_in', 'Entrada de caixa'), ('refund', 'Devolução'), ('cash_out', 'Saída de caixa'), ('courier_out', 'Troco levado pelo entregador'), ('courier_in', 'Troco de volta do entregador'), ('count', 'Contagem de fechamento'), ('count_correction', 'Correção da contagem'), ('drawer_open', 'Gaveta aberta sem venda'), ('drawer_unlock', 'Trava da gaveta liberada'), ('change_requested', 'Troco pedido'), ('change_served', 'Troco atendido'), ('change_cancelled', 'Pedido de troco cancelado'), ('receipt_result', 'Resultado do comprovante'), ('note', 'Anotação')], max_length=24, verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_q__gt', 0), ('kind__in', ['float_in', 'cod_settled', 'account_settled', 'cash_in'])), models.Q(('amount_q__gte', 0), ('kind__in', ['sale', 'courier_in'])), models.Q(('amount_q__lt', 0), ('kind__in', ['refund', 'cash_out', 'courier_out'])), ('kind__in', ['count', 'count_correction']), models.Q(('amount_q', 0), ('kind__in', ['drawer_open', 'drawer_unlock', 'change_requested', 'change_served', 'change_cancelled', 'receipt_result', 'note'])), _connector='OR'), name='cashman_entry_sign_by_kind'),
        ),
    ]
