# Generated by Django 6.0.5 on 2026-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashman', '0005_shift_custody_is_the_drawer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Configuração do dispositivo (hardware, trava). Schema em docs/reference/data-schemas.md.', verbose_name='metadados'),
        ),
    ]
