# Generated by Django 6.0.5 on 2026-08-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinsight',
            name='rfm_segment',
            field=models.CharField(blank=True, choices=[('champion', 'campeão'), ('loyal_customer', 'cliente fiel'), ('recent_customer', 'cliente recente'), ('regular', 'regular'), ('at_risk', 'em risco'), ('lost', 'perdido')], help_text='Segmento RFM calculado a partir dos scores R/F/M.', max_length=50, verbose_name='segmento RFM'),
        ),
    ]
