# Generated by Django 6.0.5 on 2026-08-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_insights', '0002_alter_customerinsight_rfm_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinsight',
            name='rfm_segment',
            field=models.CharField(blank=True, choices=[('champion', 'Campeão'), ('loyal_customer', 'Cliente fiel'), ('recent_customer', 'Cliente recente'), ('regular', 'Regular'), ('at_risk', 'Em risco'), ('lost', 'Perdido')], help_text='Segmento RFM calculado a partir dos scores R/F/M.', max_length=50, verbose_name='segmento RFM'),
        ),
    ]
