# Generated by Django 6.0.5 on 2026-09-09

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


def _btree_indexes():
    return (
        models.Index(
            fields=["last_order_at"],
            name="customer_ins_last_order_idx",
        ),
        models.Index(
            fields=["rfm_segment", "customer"],
            name="customer_ins_rfm_seg_idx",
        ),
        models.Index(
            fields=["churn_risk", "customer"],
            name="customer_ins_churn_idx",
        ),
    )


def _favorites_gin_index():
    return GinIndex(
        fields=["favorite_products"],
        name="customer_ins_favorites_gin",
    )


def add_audience_indexes(apps, schema_editor):
    model = apps.get_model("customer_insights", "CustomerInsight")
    if schema_editor.connection.vendor == "postgresql":
        for index in (*_btree_indexes(), _favorites_gin_index()):
            schema_editor.add_index(model, index, concurrently=True)
        return
    for index in _btree_indexes():
        schema_editor.add_index(model, index)


def remove_audience_indexes(apps, schema_editor):
    model = apps.get_model("customer_insights", "CustomerInsight")
    if schema_editor.connection.vendor == "postgresql":
        for index in reversed((*_btree_indexes(), _favorites_gin_index())):
            schema_editor.remove_index(model, index, concurrently=True)
        return
    for index in reversed(_btree_indexes()):
        schema_editor.remove_index(model, index)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("customer_insights", "0003_alter_customerinsight_rfm_segment"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_audience_indexes,
                    remove_audience_indexes,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="customerinsight",
                    index=models.Index(
                        fields=["last_order_at"],
                        name="customer_ins_last_order_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="customerinsight",
                    index=models.Index(
                        fields=["rfm_segment", "customer"],
                        name="customer_ins_rfm_seg_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="customerinsight",
                    index=models.Index(
                        fields=["churn_risk", "customer"],
                        name="customer_ins_churn_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="customerinsight",
                    index=GinIndex(
                        fields=["favorite_products"],
                        name="customer_ins_favorites_gin",
                    ),
                ),
            ],
        ),
    ]
