# Generated by Django 6.0.5 on 2026-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refsequence',
            name='sequence_name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='nome da sequência'),
        ),
    ]
