// KDS contract types. The structural shapes come from the generated mirror
// (app/generated/kdsContract.ts — source of truth:
// shopman/backstage/projections/kds.py, regenerated by
// `python manage.py export_kds_schema` and drift-guarded in the Django CI).
// This module only narrows fields the backend types as plain `str` and adds
// the API envelopes (shopman/backstage/api/kds.py response shapes).
//
// A Saída não tem quadro na Cozinha (SUITE-UX §15 e §16: ela mora no Gestor), e o
// quadro é sempre o de hoje (a prévia de outra data foi para a Produção/Encomendas).

import type {
  KDSBoardProjection as KDSBoardContract,
  KDSCustomerStatusProjection,
  KDSInstanceSummaryProjection,
  KDSTicketProjection as KDSTicketContract,
} from "~/generated/kdsContract";

export type {
  KDSCustomerOrderProjection,
  KDSCustomerStatusProjection,
  KDSInstanceSummaryProjection,
  KDSItemProjection,
} from "~/generated/kdsContract";

export type KDSTimerClass = "timer-ok" | "timer-warning" | "timer-late";

export interface KDSTicketProjection extends KDSTicketContract {
  timer_class: KDSTimerClass;
}

export interface KDSBoardProjection extends KDSBoardContract {
  tickets: KDSTicketProjection[];
  cancelled_tickets: KDSTicketProjection[];
  recent_done: KDSTicketProjection[]; // para recall (desfazer o Pronto)
}

// API envelopes (shopman/backstage/api/kds.py response shapes).
export interface KDSIndexResponse { instances: KDSInstanceSummaryProjection[] }
export interface KDSBoardResponse { board: KDSBoardProjection }
export interface KDSTicketResponse { ticket: KDSTicketProjection }
export interface KDSCustomerStatusResponse { status: KDSCustomerStatusProjection }
export interface KDSStationSettingsResponse { density: string; sound_enabled: boolean }
