# Generated by Django 6.0.5 on 2026-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='amount_q',
            field=models.BigIntegerField(verbose_name='valor (centavos)'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='autorizado em'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='motivo do cancelamento'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelado em'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='capturado em'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expira em'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='gateway'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dados de resposta do gateway. Populado automaticamente. Ex: {"pix_qr_code": "00020126...", "txid": "abc123"}', verbose_name='dados do gateway'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='gateway_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ID do gateway'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='chave de idempotência'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='method',
            field=models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro'), ('card', 'Cartão'), ('external', 'Externo')], max_length=20, verbose_name='forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='order_ref',
            field=models.CharField(db_index=True, max_length=64, verbose_name='ref do pedido'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ID do gateway'),
        ),
    ]
