# Generated by Django 6.0.5 on 2026-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0002_rotulos_em_portugues'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='motivo'),
        ),
    ]
