# Generated by Django 6.0.5 on 2026-08-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0003_motivo_do_reembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='chave de idempotência'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='pay_transaction_idempotency_key_unique'),
        ),
    ]
