# Generated by Django 6.0.5 on 2026-08-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0004_estorno_idempotente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='method',
            field=models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro'), ('card', 'Cartão'), ('external', 'Externo'), ('account', 'Em conta')], max_length=20, verbose_name='forma de pagamento'),
        ),
    ]
