# Generated by Django 6.0.5 on 2026-09-02 18:30

"""O vocabulário de pagamento do BALCÃO: crédito, débito e link.

Na loja online o cartão é indistinto — o gateway sabe se foi crédito ou débito e
a diferença não muda nada para quem comprou. No balcão ela importa: prazo de
recebimento e taxa da adquirente são outros, e é isso que o fechamento do dia
separa. Os dois liquidam SEM gateway: a maquininha é física e o operador atesta.

`link` é o oposto — o pedido remoto anotado no PDV, cuja cobrança vive numa URL
que o cliente abre depois. Nasce `pending` e é o webhook que o captura.

Só `choices`: nenhuma coluna muda, e nada é reescrito. O `card` gravado continua
válido e legível — vira o vocabulário do histórico e da loja online.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payman', '0005_account_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='method',
            field=models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro'), ('card', 'Cartão'), ('credit', 'Crédito'), ('debit', 'Débito'), ('link', 'Link de pagamento'), ('external', 'Externo'), ('account', 'Em conta')], max_length=20, verbose_name='forma de pagamento'),
        ),
    ]
