# Generated by Django 6.1.1 on 2026-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0003_collection_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='is_sellable',
            field=models.BooleanField(db_index=True, default=True, help_text='A casa decidiu vender este SKU (Não = venda pausada). Comprar é outro cadastro, no Compras.', verbose_name='vendável'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(db_index=True, default=True, help_text='A casa decidiu vender este SKU (Não = venda pausada). Comprar é outro cadastro, no Compras.', verbose_name='vendável'),
        ),
    ]
