# Generated by Django 6.0.5 on 2026-09-17 20:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpreference',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='0.00 a 1.00 · confiança na preferência inferida', max_digits=3, verbose_name='confiança'),
        ),
    ]
