# Generated by Django 6.0.5 on 2026-08-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(help_text='Identificador do insumo (ex.: FARINHA-T65).', max_length=64, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ref',
            field=models.CharField(help_text='Identificador do fornecedor (ex.: SUP-MOINHO-SP).', max_length=64, unique=True, verbose_name='Referência'),
        ),
    ]
