# Generated by Django 6.0.5 on 2026-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='suppliermaterialcost',
            constraint=models.CheckConstraint(condition=models.Q(('cost_q__gt', 0)), name='buyman_cost_positive', violation_error_message='O custo precisa ser maior que zero.'),
        ),
    ]
