# Generated by Django 6.0.5 on 2026-08-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0003_alter_material_sku_alter_supplier_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Como o operador chama isto: 'saco 25 kg', 'cartela', 'ovos'. É o texto que aparece na tela, tal como escrito aqui.", max_length=60, verbose_name='Rótulo')),
                ('to_base_factor', models.DecimalField(decimal_places=6, help_text='Quanto UM desta embalagem/contagem vale na unidade-base do insumo. Saco de 25 kg com base kg: 25. Ovo com base kg: 0,05.', max_digits=16, verbose_name='Fator para a unidade-base')),
                ('kind', models.CharField(choices=[('conventional', 'convencionada'), ('approximate', 'aproximada')], default='conventional', help_text="Convencionada = exata por declaração do fornecedor. Aproximada = equivalência física, e o número carrega '≈' até a tela.", max_length=16, verbose_name='Tipo')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='buyman.material', verbose_name='Insumo')),
                ('supplier', models.ForeignKey(blank=True, help_text='Vazio = vale para qualquer fornecedor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_conversions', to='buyman.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'conversão de insumo',
                'verbose_name_plural': 'conversões de insumo',
                'ordering': ['material', 'label'],
                'constraints': [models.CheckConstraint(condition=models.Q(('to_base_factor__gt', 0)), name='buyman_conversion_factor_positive', violation_error_message='O fator precisa ser maior que zero — fator zero ou negativo transformaria a conversão num número sem sentido.'), models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('material', 'supplier', 'label'), name='buyman_conversion_label_unique_per_supplier', violation_error_message='Este insumo já tem uma conversão com este rótulo para este fornecedor. Edite a existente em vez de criar uma segunda.'), models.UniqueConstraint(condition=models.Q(('supplier__isnull', True)), fields=('material', 'label'), name='buyman_conversion_label_unique_any_supplier', violation_error_message='Este insumo já tem uma conversão com este rótulo valendo para qualquer fornecedor. Edite a existente ou dê um rótulo próprio.')],
            },
        ),
    ]
