# Generated by Django 6.0.5 on 2026-08-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0004_materialconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermaterialcost',
            name='conversion',
            field=models.ForeignKey(blank=True, help_text="A conversão declarada que descreve como este insumo foi comprado ('saco 25 kg', 'cartela'). Vazio = comprado na própria unidade-base.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='buyman.materialconversion', verbose_name='Unidade de compra'),
        ),
        migrations.AlterField(
            model_name='suppliermaterialcost',
            name='cost_q',
            field=models.BigIntegerField(help_text='Custo de UMA unidade de compra, em centavos — o número da nota. O custo por unidade-base é derivado pela conversão.', verbose_name='Custo (centavos)'),
        ),
    ]
