# Generated by Django 6.0.5 on 2026-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0006_materialconversion_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='ref',
            field=models.CharField(help_text='Identificador do fornecedor (ex.: moinho-sp).', max_length=64, unique=True, verbose_name='Referência'),
        ),
    ]
