# Generated by Django 6.0.5 on 2026-09-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0007_alter_supplier_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='trade_name',
            field=models.CharField(blank=True, default='', help_text="Como a casa chama este fornecedor no dia a dia ('Tamura'). É este nome que aparece nas mensagens — ninguém cumprimenta uma razão social.", max_length=120, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Caixa geral da empresa. Só é usada quando nenhum contato atende o assunto.', max_length=254, verbose_name='E-mail da central'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='O nome do contrato e da nota fiscal.', max_length=200, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Telefone geral da empresa, usado como último recurso.', max_length=32, verbose_name='Telefone da central'),
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Como a pessoa se apresenta — é assim que a mensagem vai cumprimentá-la.', max_length=200, verbose_name='Nome')),
                ('role', models.CharField(choices=[('sales', 'Comercial'), ('finance', 'Financeiro'), ('quality', 'Qualidade'), ('general', 'Geral')], db_index=True, default='general', help_text="Decide qual documento chega a esta pessoa: o pedido de compra vai para o comercial, a recusa de recebimento para a qualidade. 'Geral' recebe o que não tiver dono.", max_length=16, verbose_name='Papel')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Telefone/WhatsApp')),
                ('is_primary', models.BooleanField(default=False, help_text='O contato preferido deste papel. Um por papel.', verbose_name='Principal')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', help_text='Horário em que atende, quem substitui nas férias, o que for útil.', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='buyman.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'contato do fornecedor',
                'verbose_name_plural': 'contatos do fornecedor',
                'ordering': ['supplier', 'role', '-is_primary', 'name'],
                'indexes': [models.Index(fields=['supplier', 'role', 'is_active'], name='buyman_supp_supplie_01fcd3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('supplier', 'role'), name='buyman_one_primary_contact_per_role'), models.CheckConstraint(condition=models.Q(('email', ''), ('phone', ''), _negated=True), name='buyman_contact_needs_a_way_to_reach', violation_error_message='Informe e-mail ou telefone para este contato.')],
            },
        ),
    ]
