# Generated by Django 6.1.1 on 2026-09-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0009_contacts_from_supplier_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(help_text='Identificador do insumo (ex.: FARINHA-NOVARA-T55).', max_length=64, unique=True, verbose_name='SKU'),
        ),
    ]
