# Generated by Django 6.1.1 on 2026-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyman', '0009_contacts_from_supplier_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialconversion',
            name='source',
            field=models.CharField(blank=True, choices=[('invoice', 'lida na nota fiscal'), ('owner', 'declarada pelo dono'), ('house_scale', 'pesada na casa'), ('estimate', 'estimativa — falta calibrar')], default='', help_text='De onde saiu o número. Vazio = ninguém declarou, e nesse caso ele conta como pendente de calibragem junto com as estimativas.', max_length=16, verbose_name='Procedência do fator'),
        ),
    ]
