# Generated by Django 6.0.5 on 2026-08-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Valor fixo')], max_length=10, verbose_name='tipo')),
                ('value', models.IntegerField(help_text='Percentual (0-100) ou valor fixo em centavos', verbose_name='valor')),
                ('valid_from', models.DateTimeField(verbose_name='válido de')),
                ('valid_until', models.DateTimeField(verbose_name='válido até')),
                ('skus', models.JSONField(blank=True, default=list, help_text='SKUs afetados (vazio = todos). Ex: ["PAO-FRANCES", "CROISSANT"]', verbose_name='SKUs')),
                ('collections', models.JSONField(blank=True, default=list, help_text='Collection refs afetados (vazio = todos). Ex: ["paes-artesanais", "confeitaria"]', verbose_name='coleções')),
                ('min_order_q', models.IntegerField(default=0, help_text='Valor mínimo do pedido em centavos (0 = sem mínimo)', verbose_name='pedido mínimo (centavos)')),
                ('fulfillment_types', models.JSONField(blank=True, default=list, help_text='Tipos de entrega (vazio = todos). Ex: ["delivery", "pickup"]', verbose_name='tipos de entrega')),
                ('customer_segments', models.JSONField(blank=True, default=list, help_text='Segmentos RFM para targeting (vazio = todos). Ex: ["champions", "loyal"]', verbose_name='segmentos de cliente')),
                ('birthday_only', models.BooleanField(default=False, help_text='Se marcado, desconto aplicável somente no dia do aniversário do cliente.', verbose_name='apenas aniversariantes')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'promoção',
                'verbose_name_plural': 'promoções',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ref', models.CharField(db_index=True, max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer_ref', 'sku'), name='uniq_customer_favorite')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDistanceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance_km', models.DecimalField(decimal_places=2, help_text='Limite superior inclusivo da faixa, em km (ex.: 3.00 cobre até 3 km).', max_digits=6, verbose_name='distância máxima (km)')),
                ('fee_q', models.PositiveIntegerField(default=0, help_text='Taxa em centavos. 0 = entrega grátis.', verbose_name='taxa de entrega (centavos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Desempate entre faixas com o mesmo limite. Menor = maior prioridade.', verbose_name='ordem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_distance_bands', to='shop.shop', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'faixa de distância de entrega',
                'verbose_name_plural': 'faixas de distância de entrega',
                'ordering': ['max_distance_km', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('zone_type', models.CharField(choices=[('cep_prefix', 'Prefixo de CEP'), ('neighborhood', 'Bairro')], default='cep_prefix', max_length=20, verbose_name='tipo de zona')),
                ('match_value', models.CharField(help_text="Para 'Prefixo de CEP': dígitos iniciais sem hífen (ex: '860' cobre 860xx-xxx). Para 'Bairro': nome exato do bairro (comparação sem maiúsculas/minúsculas). ", max_length=100, verbose_name='valor de correspondência')),
                ('mode', models.CharField(choices=[('override', 'Sobrepor taxa (fixa)'), ('exclude', 'Não entregar (bloquear)')], default='override', help_text="'Sobrepor taxa': usa a taxa fixa abaixo no lugar da faixa de distância. 'Não entregar': bloqueia o checkout para este CEP/bairro.", max_length=20, verbose_name='modo')),
                ('fee_q', models.PositiveIntegerField(default=0, help_text="Taxa em centavos no modo 'Sobrepor taxa'. 0 = entrega grátis.", verbose_name='taxa de entrega (centavos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Menor número = maior prioridade dentro do mesmo tipo.', verbose_name='ordem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='shop.shop', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'zona de entrega',
                'verbose_name_plural': 'zonas de entrega',
                'ordering': ['zone_type', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='código')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = ilimitado', verbose_name='usos máximos')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='usos realizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='storefront.promotion', verbose_name='promoção')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
            },
        ),
        migrations.CreateModel(
            name='StockAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('alert_type', models.CharField(choices=[('stock_back', 'voltou ao estoque'), ('production_ready', 'saiu do forno')], default='stock_back', max_length=24)),
                ('channel_ref', models.CharField(default='web', max_length=32)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=64)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'aviso de reposição',
                'verbose_name_plural': 'avisos de reposição',
                'indexes': [models.Index(fields=['sku', 'notified_at'], name='storefront__sku_a4e9b8_idx'), models.Index(fields=['sku', 'alert_type', 'notified_at'], name='storefront__sku_e32054_idx')],
            },
        ),
    ]
