# Generated by Django 6.0.5 on 2026-08-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ref', models.CharField(db_index=True, max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer_ref', 'sku'), name='uniq_customer_favorite')],
            },
        ),
        migrations.CreateModel(
            name='StockAlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('alert_type', models.CharField(choices=[('stock_back', 'voltou ao estoque'), ('production_ready', 'saiu do forno')], default='stock_back', max_length=24)),
                ('channel_ref', models.CharField(default='web', max_length=32)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=64)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'aviso de reposição',
                'verbose_name_plural': 'avisos de reposição',
                'indexes': [models.Index(fields=['sku', 'notified_at'], name='storefront__sku_a4e9b8_idx'), models.Index(fields=['sku', 'alert_type', 'notified_at'], name='storefront__sku_e32054_idx')],
            },
        ),
    ]
