# Generated by Django 6.0.5 on 2026-08-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockalertsubscription',
            name='alert_type',
            field=models.CharField(choices=[('stock_back', 'voltou ao estoque'), ('production_ready', 'saiu do forno')], default='stock_back', max_length=24, verbose_name='tipo de aviso'),
        ),
        migrations.AlterField(
            model_name='stockalertsubscription',
            name='channel_ref',
            field=models.CharField(default='web', max_length=32, verbose_name='ref do canal'),
        ),
        migrations.AlterField(
            model_name='stockalertsubscription',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='telefone de contato'),
        ),
        migrations.AlterField(
            model_name='stockalertsubscription',
            name='customer_ref',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ref do cliente'),
        ),
        migrations.AlterField(
            model_name='stockalertsubscription',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='avisado em'),
        ),
        migrations.AlterField(
            model_name='stockalertsubscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='pedido em'),
        ),
    ]
