# Generated by Django 6.0.5 on 2026-09-11 15:05

import hashlib
import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def consolidate_active_subscriptions(apps, schema_editor):
    """Keep the newest live opt-in when one-shot history left duplicates."""
    Subscription = apps.get_model("storefront", "StockAlertSubscription")
    groups = {}
    migrated_at = timezone.now()
    proof_rank = models.Case(
        models.When(proof_status="verified", then=models.Value(0)),
        default=models.Value(1),
        output_field=models.IntegerField(),
    )
    rows = Subscription.objects.filter(revoked_at__isnull=True).order_by(
        proof_rank,
        "-subscribed_at",
        "-pk",
    )
    for row in rows.iterator():
        key = (row.sku, row.alert_type, row.channel_ref, row.target_key)
        if key not in groups:
            groups[key] = row.pk
            continue
        row.revoked_at = migrated_at
        row.revoke_reason = "superseded_during_persistent_migration"
        row.revocation_evidence_hash = hashlib.sha256(
            f"{row.ref}:{migrated_at.isoformat()}:{row.revoke_reason}".encode()
        ).hexdigest()
        row.save(update_fields=["revoked_at", "revoke_reason", "revocation_evidence_hash"])


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0004_stock_alert_dispatch_claim"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAlertDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("purpose", models.CharField(default="stock_availability", max_length=32)),
                ("delivery_channel", models.CharField(default="whatsapp", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "na fila"),
                            ("claimed", "em envio"),
                            ("accepted", "aceita"),
                            ("retryable", "tentar novamente"),
                            ("indeterminate", "resultado incerto"),
                            ("suppressed", "suprimida"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("directive_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("provider_receipt_ref", models.CharField(blank=True, max_length=160)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockAlertOccurrence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("sku", models.CharField(db_index=True, max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("stock_back", "voltou ao estoque"), ("production_ready", "saiu do forno")],
                        max_length=24,
                    ),
                ),
                ("channel_ref", models.CharField(default="web", max_length=32)),
                ("semantic_key", models.CharField(max_length=160, unique=True)),
                ("source_ref", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "aguardando validação"),
                            ("eligible", "elegível"),
                            ("blocked", "bloqueada"),
                            ("closed", "encerrada"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=100)),
                ("available_qty", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="stockalertsubscription",
            name="storefront_stock_alert_pending_target_uq",
        ),
        migrations.AddField(
            model_name="stockalertsubscription",
            name="pause_reason",
            field=models.CharField(blank=True, db_default="", max_length=100, verbose_name="motivo da pausa"),
        ),
        migrations.AddField(
            model_name="stockalertsubscription",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="pausado em"),
        ),
        migrations.RunPython(consolidate_active_subscriptions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="stockalertsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("sku", "alert_type", "channel_ref", "target_key"),
                name="storefront_stock_alert_active_target_uq",
            ),
        ),
        migrations.AddField(
            model_name="stockalertdelivery",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="storefront.stockalertsubscription",
            ),
        ),
        migrations.AddIndex(
            model_name="stockalertoccurrence",
            index=models.Index(fields=["sku", "event_type", "closed_at"], name="storefront__sku_4a3d57_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockalertoccurrence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True), ("event_type", "stock_back")),
                fields=("sku", "event_type", "channel_ref"),
                name="storefront_stock_alert_open_cycle_uq",
            ),
        ),
        migrations.AddField(
            model_name="stockalertdelivery",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="storefront.stockalertoccurrence",
            ),
        ),
        migrations.AddIndex(
            model_name="stockalertdelivery",
            index=models.Index(fields=["status", "created_at"], name="storefront__status_297894_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockalertdelivery",
            constraint=models.UniqueConstraint(
                fields=("subscription", "occurrence", "purpose", "delivery_channel"),
                name="storefront_stock_alert_delivery_uq",
            ),
        ),
    ]
