# Generated by Django 6.0.5 on 2026-09-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storefront", "0005_stockalertdelivery_stockalertoccurrence_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockalertdelivery",
            options={
                "verbose_name": "entrega de aviso de produto",
                "verbose_name_plural": "entregas de avisos de produto",
            },
        ),
        migrations.AlterModelOptions(
            name="stockalertoccurrence",
            options={
                "verbose_name": "ocorrência de aviso de produto",
                "verbose_name_plural": "ocorrências de avisos de produto",
            },
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="aceita em"),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="assumida em"),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="delivery_channel",
            field=models.CharField(default="whatsapp", max_length=20, verbose_name="canal de entrega"),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="directive_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="id da diretiva"),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=100, verbose_name="código do último erro"),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="storefront.stockalertoccurrence",
                verbose_name="ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="provider_receipt_ref",
            field=models.CharField(blank=True, max_length=160, verbose_name="referência no provedor"),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="purpose",
            field=models.CharField(default="stock_availability", max_length=32, verbose_name="finalidade"),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "na fila"),
                    ("claimed", "em envio"),
                    ("accepted", "aceita"),
                    ("retryable", "tentar novamente"),
                    ("indeterminate", "resultado incerto"),
                    ("suppressed", "suprimida"),
                ],
                default="queued",
                max_length=20,
                verbose_name="situação",
            ),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="storefront.stockalertsubscription",
                verbose_name="assinatura",
            ),
        ),
        migrations.AlterField(
            model_name="stockalertdelivery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="available_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True, verbose_name="quantidade disponível"
            ),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="channel_ref",
            field=models.CharField(default="web", max_length=32, verbose_name="ref do canal"),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="encerrada em"),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="event_type",
            field=models.CharField(
                choices=[("stock_back", "voltou ao estoque"), ("production_ready", "saiu do forno")],
                max_length=24,
                verbose_name="tipo de ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="semantic_key",
            field=models.CharField(max_length=160, unique=True, verbose_name="chave semântica"),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="source_ref",
            field=models.CharField(blank=True, max_length=100, verbose_name="referência de origem"),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "aguardando validação"),
                    ("eligible", "elegível"),
                    ("blocked", "bloqueada"),
                    ("closed", "encerrada"),
                ],
                default="pending",
                max_length=16,
                verbose_name="situação",
            ),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="status_reason",
            field=models.CharField(blank=True, max_length=100, verbose_name="motivo da situação"),
        ),
        migrations.AlterField(
            model_name="stockalertoccurrence",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
        ),
        migrations.AlterField(
            model_name="stockalertsubscription",
            name="dispatch_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="envio aceito em"),
        ),
        migrations.AlterField(
            model_name="stockalertsubscription",
            name="dispatch_claimed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="envio assumido em"),
        ),
    ]
