# Generated by Django 6.1.1 on 2026-09-23 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0066_lote_no_gatilho_e_no_prazo"),
        ("storefront", "0009_stock_alert_adult_declaration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.SlugField(
                        max_length=40, unique=True, verbose_name="referência"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "description",
                    models.CharField(
                        help_text="O que conta como esta intenção. Os classificadores leem esta frase.",
                        max_length=240,
                        verbose_name="descrição",
                    ),
                ),
                (
                    "sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Deixar passar custa caro (reclamação, alergia, pedir uma pessoa). O placar mede à parte.",
                        verbose_name="sensível",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="posição"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "intenção",
                "verbose_name_plural": "intenções",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="IntentPilotReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="medido em"),
                ),
                (
                    "samples",
                    models.PositiveIntegerField(verbose_name="mensagens conferidas"),
                ),
                (
                    "contenders",
                    models.CharField(max_length=240, verbose_name="concorrentes"),
                ),
                (
                    "skipped",
                    models.TextField(blank=True, verbose_name="fora do placar"),
                ),
                ("report", models.TextField(verbose_name="placar")),
            ],
            options={
                "verbose_name": "placar das intenções",
                "verbose_name_plural": "placares das intenções",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageIntentSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "a rotular"),
                            ("proposed", "sugerida"),
                            ("labeled", "conferida"),
                            ("skipped", "pulada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="observação"
                    ),
                ),
                (
                    "suggested_by",
                    models.CharField(
                        blank=True,
                        help_text="Modelo que pré-marcou as intenções. Vazio quando uma pessoa marcou do zero.",
                        max_length=60,
                        verbose_name="sugerida por",
                    ),
                ),
                (
                    "labeled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="conferida em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="sorteada em"),
                ),
                (
                    "intents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Todas as que a mensagem carrega. Nenhuma marcada + conferida = conversa sem intenção da lista.",
                        related_name="samples",
                        to="storefront.intentcategory",
                        verbose_name="intenções",
                    ),
                ),
                (
                    "labeled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="conferida por",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intent_sample",
                        to="shop.conversationmessage",
                        verbose_name="mensagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem para rotular",
                "verbose_name_plural": "mensagens para rotular",
                "ordering": ["status", "id"],
            },
        ),
    ]
