# Generated by Django 6.1.1 on 2026-09-28

from django.db import migrations, models

import shopman.storefront.models.continuum


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0010_intent_pilot"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogStructureHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_ref", models.CharField(max_length=32, unique=True)),
                ("stream_id", models.CharField(max_length=128)),
                (
                    "epoch",
                    models.CharField(
                        default=shopman.storefront.models.continuum.new_catalog_epoch,
                        max_length=64,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(default=0)),
                ("state_token", models.CharField(blank=True, max_length=128)),
                ("state_digest", models.CharField(blank=True, max_length=80)),
                ("etag", models.CharField(blank=True, max_length=96)),
                ("message", models.JSONField(default=dict)),
                ("dirty", models.BooleanField(default=True)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cabeça estrutural do cardápio",
                "verbose_name_plural": "cabeças estruturais do cardápio",
            },
        ),
    ]
