# Generated by Django 6.0.5 on 2026-09-08 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_merge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mergeaudit',
            options={'ordering': ['-merged_at'], 'verbose_name': 'unificação de cadastros', 'verbose_name_plural': 'unificações de cadastros'},
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='actor',
            field=models.CharField(blank=True, max_length=200, verbose_name='quem unificou'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='evidence',
            field=models.JSONField(default=dict, verbose_name='justificativa'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='loyalty_merged',
            field=models.BooleanField(default=False, verbose_name='fidelidade somada'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='merged_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='unificado em'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='migrated_addresses',
            field=models.PositiveIntegerField(default=0, verbose_name='endereços migrados'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='migrated_consents',
            field=models.PositiveIntegerField(default=0, verbose_name='consentimentos migrados'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='migrated_contact_points',
            field=models.PositiveIntegerField(default=0, verbose_name='contatos migrados'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='migrated_external_identities',
            field=models.PositiveIntegerField(default=0, verbose_name='identidades externas migradas'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='migrated_identifiers',
            field=models.PositiveIntegerField(default=0, verbose_name='identificadores migrados'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='migrated_preferences',
            field=models.PositiveIntegerField(default=0, verbose_name='preferências migradas'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='migrated_timeline_events',
            field=models.PositiveIntegerField(default=0, verbose_name='eventos de histórico migrados'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='desfeito em'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='reverted_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='quem desfez'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='snapshot',
            field=models.JSONField(default=dict, help_text='O que foi movido, por categoria — é daqui que o desfazer devolve.', verbose_name='retrato para desfazer'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='source_id',
            field=models.UUIDField(verbose_name='id do cadastro absorvido'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='source_ref',
            field=models.CharField(max_length=50, verbose_name='cadastro absorvido'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='status',
            field=models.CharField(choices=[('completed', 'Unificada'), ('reverted', 'Desfeita')], default='completed', max_length=20, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='target_id',
            field=models.UUIDField(verbose_name='id do cadastro que ficou'),
        ),
        migrations.AlterField(
            model_name='mergeaudit',
            name='target_ref',
            field=models.CharField(max_length=50, verbose_name='cadastro que ficou'),
        ),
    ]
