"""Backstage API URL configuration."""

from __future__ import annotations

from django.urls import path

from .alerts import AlertAckView, AlertListView
from .bi import (
    BICashView,
    BIChangeView,
    BIConsumptionProfilesView,
    BICustomersView,
    BIExploreView,
    BIForecastView,
    BIProductionView,
    BISalesView,
    BIScenariosView,
    BIViewDetailView,
    BIViewListView,
)
from .catalog import (
    CatalogAiAssistView,
    CatalogBulkPriceView,
    CatalogBulkView,
    CatalogCellView,
    CatalogMatrixView,
    CatalogProductDetailView,
    CatalogProductView,
    CatalogReorderCollectionsView,
    CatalogReorderItemsView,
    CatalogResyncView,
    CatalogSocialView,
    CatalogSyncStatusView,
)
from .feeds import (
    FeedActiveView,
    FeedBoardView,
    FeedCollectionsView,
)
from .hub import HubView
from .kds import (
    KDSBoardView,
    KDSCustomerStatusView,
    KDSExpeditionActionView,
    KDSIndexView,
    KDSTicketAcknowledgeView,
    KDSTicketDoneView,
    KDSTicketItemView,
    KDSTicketRecallView,
)
from .marketing import (
    AnnouncementApproveView,
    AnnouncementDetailView,
    AnnouncementRejectView,
    AnnouncementRewriteView,
    AnnouncementTemplateDetailView,
    AnnouncementTemplateListView,
    AudienceCountView,
    CampaignBoardView,
    CampaignDetailView,
    CampaignFireView,
    CampaignHistoryView,
    CampaignListView,
    CampaignOptionsView,
    PlatformsView,
    PreviewView,
    WhatsAppTemplateView,
    WhatsAppTestSendView,
)
from .notifications import (
    NotificationActionView,
    NotificationListView,
    NotificationReadView,
)
from .operations import (
    DayClosingView,
    OperationEpisodeAnswerView,
    OperatorEligibleView,
    OperatorLockView,
    OperatorLoginView,
    OperatorPinChangeView,
    OperatorPinResetView,
    OperatorSessionView,
    OperatorUnlockView,
    OrderAdvanceView,
    OrderAssignView,
    OrderCancellationReasonsView,
    OrderCancelView,
    OrderCommentView,
    OrderConfirmView,
    OrderCourierCancelView,
    OrderCourierDispatchView,
    OrderCourierQuoteView,
    OrderDetailView,
    OrderNotesView,
    OrderQueueView,
    OrderRejectView,
    OrderRequeueFiscalView,
    OrderSettleDeliveryCashView,
    OrderUnassignView,
    POSCancelRecentSaleView,
    POSCashCloseBlockingView,
    POSCashCloseView,
    POSCashDrawerOpenView,
    POSCashDrawerUnlockView,
    POSCashOpenView,
    POSCashReceiptView,
    POSCashRefundView,
    POSCashReportView,
    POSChangeRequestCancelView,
    POSChangeRequestServeView,
    POSChangeRequestView,
    POSCloseSaleView,
    POSCustomerLookupView,
    POSCustomerResolveView,
    POSCustomerSearchView,
    POSMovementView,
    POSPaymentStatusView,
    POSReviewSaleView,
    POSTabClearView,
    POSTabCreateView,
    POSTabFireView,
    POSTabMoveLinesView,
    POSTabOpenView,
    POSTabRenameView,
    POSTabSaveView,
    POSTabUnfireView,
    POSView,
    ProductionBlindMapView,
    ProductionBoardView,
    ProductionForecastView,
    ProductionKDSView,
    ProductionManagementView,
    ProductionMiseEnPlaceView,
    ProductionQCView,
    ProductionReportsView,
    ProductionWeighingView,
    WorkOrderAdvanceStepView,
    WorkOrderFinishView,
    WorkOrderOvenArmView,
    WorkOrderOvenConcludeView,
    WorkOrderPlanView,
    WorkOrderQuickFinishView,
    WorkOrderStartView,
    WorkOrderVoidView,
)
from .telemetry import ClientErrorView

urlpatterns = [
    # Telemetria — erro de cliente das superfícies de operador (operator-kit)
    path("client-error/", ClientErrorView.as_view(), name="api-backstage-client-error"),
    # Central de Apps — launcher do operador (surfaces/hub-nuxt)
    path("hub/", HubView.as_view(), name="api-backstage-hub"),
    # KDS
    path("kds/", KDSIndexView.as_view(), name="api-backstage-kds-index"),
    path("kds/cliente/", KDSCustomerStatusView.as_view(), name="api-backstage-kds-customer"),
    path("kds/<slug:ref>/", KDSBoardView.as_view(), name="api-backstage-kds-board"),
    path("kds/tickets/<int:ticket_pk>/items/", KDSTicketItemView.as_view(), name="api-backstage-kds-ticket-item"),
    path("kds/tickets/<int:ticket_pk>/done/", KDSTicketDoneView.as_view(), name="api-backstage-kds-ticket-done"),
    path("kds/tickets/<int:ticket_pk>/recall/", KDSTicketRecallView.as_view(), name="api-backstage-kds-ticket-recall"),
    path("kds/tickets/<int:ticket_pk>/acknowledge/", KDSTicketAcknowledgeView.as_view(), name="api-backstage-kds-ticket-acknowledge"),
    path("kds/expedition/<int:order_pk>/action/", KDSExpeditionActionView.as_view(), name="api-backstage-kds-expedition"),
    # Operations — read views
    path("pos/", POSView.as_view(), name="api-backstage-pos"),
    # Operador (PIN/crachá) — genérico, compartilhado por todas as surfaces (inclui POS)
    path("operator/login/", OperatorLoginView.as_view(), name="api-backstage-operator-login"),
    path("operator/session/", OperatorSessionView.as_view(), name="api-backstage-operator-session"),
    path("operator/eligible/", OperatorEligibleView.as_view(), name="api-backstage-operator-eligible"),
    path("operator/unlock/", OperatorUnlockView.as_view(), name="api-backstage-operator-unlock"),
    path("operator/lock/", OperatorLockView.as_view(), name="api-backstage-operator-lock"),
    path("operator/pin/change/", OperatorPinChangeView.as_view(), name="api-backstage-operator-pin-change"),
    path("operator/pin/reset/", OperatorPinResetView.as_view(), name="api-backstage-operator-pin-reset"),
    path("production/", ProductionBoardView.as_view(), name="api-backstage-production"),
    path("production/kds/", ProductionKDSView.as_view(), name="api-backstage-production-kds"),
    path("production/qc/", ProductionQCView.as_view(), name="api-backstage-production-qc"),
    path("production/forecast/", ProductionForecastView.as_view(), name="api-backstage-production-forecast"),
    path(
        "production/mise-en-place/",
        ProductionMiseEnPlaceView.as_view(),
        name="api-backstage-production-mise-en-place",
    ),
    path(
        "production/weighing/",
        ProductionWeighingView.as_view(),
        name="api-backstage-production-weighing",
    ),
    # Produção — persona GESTOR (perm fina backstage.view_production_reports)
    path(
        "production/reports/",
        ProductionReportsView.as_view(),
        name="api-backstage-production-reports",
    ),
    path(
        "production/management/",
        ProductionManagementView.as_view(),
        name="api-backstage-production-management",
    ),
    path(
        "production/weighing/blind-map/",
        ProductionBlindMapView.as_view(),
        name="api-backstage-production-blind-map",
    ),
    # B.I. — persona gestor (perm fina backstage.view_bi, ADR-021)
    path("bi/production/", BIProductionView.as_view(), name="api-backstage-bi-production"),
    path("bi/sales/", BISalesView.as_view(), name="api-backstage-bi-sales"),
    path("bi/cash/", BICashView.as_view(), name="api-backstage-bi-cash"),
    path("bi/customers/", BICustomersView.as_view(), name="api-backstage-bi-customers"),
    path("bi/explore/", BIExploreView.as_view(), name="api-backstage-bi-explore"),
    path(
        "bi/consumption-profiles/",
        BIConsumptionProfilesView.as_view(),
        name="api-backstage-bi-consumption-profiles",
    ),
    path("bi/forecast/", BIForecastView.as_view(), name="api-backstage-bi-forecast"),
    path("bi/change/", BIChangeView.as_view(), name="api-backstage-bi-change"),
    path("bi/views/", BIViewListView.as_view(), name="api-backstage-bi-views"),
    path("bi/views/<int:pk>/", BIViewDetailView.as_view(), name="api-backstage-bi-view"),
    path("bi/scenarios/", BIScenariosView.as_view(), name="api-backstage-bi-scenarios"),
    path("closing/", DayClosingView.as_view(), name="api-backstage-closing"),
    path(
        "closing/episodes/<int:episode_id>/",
        OperationEpisodeAnswerView.as_view(),
        name="api-backstage-closing-episode",
    ),
    path("orders/", OrderQueueView.as_view(), name="api-backstage-orders"),
    # Catalog matrix (produto × superfície)
    path("catalog/", CatalogMatrixView.as_view(), name="api-backstage-catalog"),
    path("catalog/cell/", CatalogCellView.as_view(), name="api-backstage-catalog-cell"),
    path("catalog/product/", CatalogProductView.as_view(), name="api-backstage-catalog-product"),
    path("catalog/product/<str:sku>/", CatalogProductDetailView.as_view(), name="api-backstage-catalog-product-detail"),
    path("catalog/bulk/", CatalogBulkView.as_view(), name="api-backstage-catalog-bulk"),
    path("catalog/bulk-price/", CatalogBulkPriceView.as_view(), name="api-backstage-catalog-bulk-price"),
    path("catalog/reorder-collections/", CatalogReorderCollectionsView.as_view(), name="api-backstage-catalog-reorder-collections"),
    path("catalog/reorder-items/", CatalogReorderItemsView.as_view(), name="api-backstage-catalog-reorder-items"),
    path("catalog/sync-status/", CatalogSyncStatusView.as_view(), name="api-backstage-catalog-sync-status"),
    path("catalog/resync/", CatalogResyncView.as_view(), name="api-backstage-catalog-resync"),
    path("catalog/social/", CatalogSocialView.as_view(), name="api-backstage-catalog-social"),
    path("catalog/ai-assist/", CatalogAiAssistView.as_view(), name="api-backstage-catalog-ai-assist"),
    # Feeds (menuboard/Google/Meta)
    path("feeds/", FeedBoardView.as_view(), name="api-backstage-feeds"),
    path("feeds/active/", FeedActiveView.as_view(), name="api-backstage-feeds-active"),
    path("feeds/collections/", FeedCollectionsView.as_view(), name="api-backstage-feeds-collections"),
    # Orders — operator actions
    path("orders/<str:ref>/", OrderDetailView.as_view(), name="api-backstage-order-detail"),
    path("orders/<str:ref>/advance/", OrderAdvanceView.as_view(), name="api-backstage-order-advance"),
    path("orders/<str:ref>/confirm/", OrderConfirmView.as_view(), name="api-backstage-order-confirm"),
    path("orders/<str:ref>/reject/", OrderRejectView.as_view(), name="api-backstage-order-reject"),
    path("orders/<str:ref>/cancel/", OrderCancelView.as_view(), name="api-backstage-order-cancel"),
    path("orders/<str:ref>/cancellation-reasons/", OrderCancellationReasonsView.as_view(), name="api-backstage-order-cancellation-reasons"),
    path("orders/<str:ref>/settle-delivery-cash/", OrderSettleDeliveryCashView.as_view(), name="api-backstage-order-settle-delivery-cash"),
    path("orders/<str:ref>/requeue-fiscal/", OrderRequeueFiscalView.as_view(), name="api-backstage-order-requeue-fiscal"),
    path("orders/<str:ref>/notes/", OrderNotesView.as_view(), name="api-backstage-order-notes"),
    path("orders/<str:ref>/courier-dispatch/", OrderCourierDispatchView.as_view(), name="api-backstage-order-courier-dispatch"),
    path("orders/<str:ref>/courier-cancel/", OrderCourierCancelView.as_view(), name="api-backstage-order-courier-cancel"),
    path("orders/<str:ref>/courier-quote/", OrderCourierQuoteView.as_view(), name="api-backstage-order-courier-quote"),
    path("orders/<str:ref>/assign/", OrderAssignView.as_view(), name="api-backstage-order-assign"),
    path("orders/<str:ref>/unassign/", OrderUnassignView.as_view(), name="api-backstage-order-unassign"),
    path("orders/<str:ref>/comment/", OrderCommentView.as_view(), name="api-backstage-order-comment"),
    # Operator alerts
    path("alerts/", AlertListView.as_view(), name="api-backstage-alerts"),
    path("alerts/<int:pk>/ack/", AlertAckView.as_view(), name="api-backstage-alert-ack"),
    # Notificações PESSOAIS (vs. alerts, que são da loja): o gestor recebe o
    # pedido de aprovação onde estiver. Push pelo canal SSE ``user-<id>``.
    path("notifications/", NotificationListView.as_view(), name="api-backstage-notifications"),
    path(
        "notifications/<int:pk>/read/",
        NotificationReadView.as_view(),
        name="api-backstage-notification-read",
    ),
    path(
        "notifications/<int:pk>/action/",
        NotificationActionView.as_view(),
        name="api-backstage-notification-action",
    ),
    # Campanha — marketing operacional (surfaces/marketing-nuxt). Gate próprio
    # (`shop.manage_campaigns`): o gestor de marketing não é o de pedidos.
    path("marketing/", CampaignBoardView.as_view(), name="api-backstage-marketing"),
    path("marketing/audience/count/", AudienceCountView.as_view(), name="api-backstage-marketing-audience-count"),
    path("marketing/history/", CampaignHistoryView.as_view(), name="api-backstage-marketing-history"),
    path("marketing/options/", CampaignOptionsView.as_view(), name="api-backstage-marketing-options"),
    path("marketing/platforms/", PlatformsView.as_view(), name="api-backstage-marketing-platforms"),
    path("marketing/preview/", PreviewView.as_view(), name="api-backstage-marketing-preview"),
    path("marketing/rules/", CampaignListView.as_view(), name="api-backstage-marketing-rules"),
    path("marketing/rules/<int:pk>/", CampaignDetailView.as_view(), name="api-backstage-marketing-rule"),
    path("marketing/rules/<int:pk>/fire/", CampaignFireView.as_view(), name="api-backstage-marketing-fire"),
    path("marketing/whatsapp-template/", WhatsAppTemplateView.as_view(), name="api-backstage-marketing-wa-template"),
    path("marketing/whatsapp-template/test/", WhatsAppTestSendView.as_view(), name="api-backstage-marketing-whatsapp-test"),
    path("marketing/templates/", AnnouncementTemplateListView.as_view(), name="api-backstage-marketing-templates"),
    path("marketing/templates/<int:pk>/", AnnouncementTemplateDetailView.as_view(), name="api-backstage-marketing-template"),
    path("marketing/announcements/<int:pk>/", AnnouncementDetailView.as_view(), name="api-backstage-marketing-announcement"),
    path("marketing/announcements/<int:pk>/approve/", AnnouncementApproveView.as_view(), name="api-backstage-marketing-approve"),
    path("marketing/announcements/<int:pk>/reject/", AnnouncementRejectView.as_view(), name="api-backstage-marketing-reject"),
    path("marketing/announcements/<int:pk>/rewrite/", AnnouncementRewriteView.as_view(), name="api-backstage-marketing-rewrite"),
    # Production — work order actions
    path("production/plan/", WorkOrderPlanView.as_view(), name="api-backstage-wo-plan"),
    path("production/<int:wo_id>/start/", WorkOrderStartView.as_view(), name="api-backstage-wo-start"),
    path("production/<int:wo_id>/finish/", WorkOrderFinishView.as_view(), name="api-backstage-wo-finish"),
    path("production/<int:wo_id>/advance-step/", WorkOrderAdvanceStepView.as_view(), name="api-backstage-wo-advance"),
    path("production/quick-finish/", WorkOrderQuickFinishView.as_view(), name="api-backstage-wo-quick-finish"),
    path("production/<int:wo_id>/void/", WorkOrderVoidView.as_view(), name="api-backstage-wo-void"),
    # Forno — o timer do kiosk declara; o servidor carimba (ADR-021 §4)
    path("production/<int:wo_id>/oven/arm/", WorkOrderOvenArmView.as_view(), name="api-backstage-wo-oven-arm"),
    path("production/<int:wo_id>/oven/conclude/", WorkOrderOvenConcludeView.as_view(), name="api-backstage-wo-oven-conclude"),
    # POS — cash session actions
    path("pos/cash/open/", POSCashOpenView.as_view(), name="api-backstage-pos-cash-open"),
    path("pos/cash/close/", POSCashCloseView.as_view(), name="api-backstage-pos-cash-close"),
    path("pos/cash/close-blocking/", POSCashCloseBlockingView.as_view(), name="api-backstage-pos-cash-close-blocking"),
    path("pos/cash/movement/", POSMovementView.as_view(), name="api-backstage-pos-cash-movement"),
    path("pos/cash/report/", POSCashReportView.as_view(), name="api-backstage-pos-cash-report"),
    path("pos/cash/drawer-open/", POSCashDrawerOpenView.as_view(), name="api-backstage-pos-cash-drawer-open"),
    # A trava vive no PDV (é ele que lê a gaveta); o destrave passa aqui para
    # ficar no livro com quem liberou.
    path("pos/cash/drawer-unlock/", POSCashDrawerUnlockView.as_view(), name="api-backstage-pos-cash-drawer-unlock"),
    # Cancelar não é devolver: o dinheiro de venda cancelada sai pela gaveta de
    # quem devolve, com PIN, e só então Payman e livro registram.
    path("pos/cash/refund/<str:order_ref>/", POSCashRefundView.as_view(), name="api-backstage-pos-cash-refund"),
    # Pedido de troco: o dinheiro não anda, o troco vem até o balcão. Net zero —
    # nenhuma destas rotas cria movimento nem mexe no esperado do fechamento.
    path(
        "pos/cash/change-request/",
        POSChangeRequestView.as_view(),
        name="api-backstage-pos-change-request",
    ),
    path(
        "pos/cash/change-request/<str:request_ref>/serve/",
        POSChangeRequestServeView.as_view(),
        name="api-backstage-pos-change-request-serve",
    ),
    path(
        "pos/cash/change-request/<str:request_ref>/cancel/",
        POSChangeRequestCancelView.as_view(),
        name="api-backstage-pos-change-request-cancel",
    ),
    path(
        "pos/cash/entry/<int:entry_id>/receipt/",
        POSCashReceiptView.as_view(),
        name="api-backstage-pos-cash-receipt",
    ),
    # POS — tab (comanda) lifecycle
    path("pos/tabs/", POSTabCreateView.as_view(), name="api-backstage-pos-tab-create"),
    path("pos/tabs/<str:tab_ref>/open/", POSTabOpenView.as_view(), name="api-backstage-pos-tab-open"),
    path("pos/tabs/save/", POSTabSaveView.as_view(), name="api-backstage-pos-tab-save"),
    path("pos/tabs/rename/", POSTabRenameView.as_view(), name="api-backstage-pos-tab-rename"),
    path("pos/tabs/move-lines/", POSTabMoveLinesView.as_view(), name="api-backstage-pos-tab-move-lines"),
    path("pos/tabs/fire/", POSTabFireView.as_view(), name="api-backstage-pos-tab-fire"),
    path("pos/tabs/unfire/", POSTabUnfireView.as_view(), name="api-backstage-pos-tab-unfire"),
    path("pos/tabs/<str:session_key>/clear/", POSTabClearView.as_view(), name="api-backstage-pos-tab-clear"),
    path("pos/sale/review/", POSReviewSaleView.as_view(), name="api-backstage-pos-review-sale"),
    path("pos/sale/close/", POSCloseSaleView.as_view(), name="api-backstage-pos-close-sale"),
    path("pos/sale/recent/cancel/", POSCancelRecentSaleView.as_view(), name="api-backstage-pos-cancel-recent-sale"),
    path("pos/payment/<str:ref>/status/", POSPaymentStatusView.as_view(), name="api-backstage-pos-payment-status"),
    path("pos/customer/lookup/", POSCustomerLookupView.as_view(), name="api-backstage-pos-customer-lookup"),
    path("pos/customer/search/", POSCustomerSearchView.as_view(), name="api-backstage-pos-customer-search"),
    path("pos/customer/resolve/", POSCustomerResolveView.as_view(), name="api-backstage-pos-customer-resolve"),
]
